// ================================================================================================
// 核心交易协议定义（EUTXO 模型）
// ================================================================================================
// 重要说明（共识协议纯净性约束）：
// - 本文件仅定义“上链的共识数据结构”（交易、输入/输出、锁定条件、证明等）。
// - Host ABI / SDK 侧用于跨边界传输的 DTO（如批量输出描述、扩展转账意图等），不得添加到本 proto 中，
//   应放置于应用层（如 pkg/types 或独立 hostabi proto 包）以避免污染共识层协议。
// - LockingConditionList 相关编解码已迁出至 Host ABI 层实现（pkg/types + pkg/utils），后续如需 Protobuf 版本，
//   也应放到非共识命名空间（如 pb/hostabi/…）。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.1
// source: pb/blockchain/block/transaction/transaction.proto

package transaction

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransactionHashService_ComputeHash_FullMethodName           = "/pb.blockchain.core.TransactionHashService/ComputeHash"
	TransactionHashService_ValidateHash_FullMethodName          = "/pb.blockchain.core.TransactionHashService/ValidateHash"
	TransactionHashService_ComputeSignatureHash_FullMethodName  = "/pb.blockchain.core.TransactionHashService/ComputeSignatureHash"
	TransactionHashService_ValidateSignatureHash_FullMethodName = "/pb.blockchain.core.TransactionHashService/ValidateSignatureHash"
)

// TransactionHashServiceClient is the client API for TransactionHashService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// *
// TransactionHashService - 确定性交易哈希服务
type TransactionHashServiceClient interface {
	// 计算交易哈希（确定性）
	// 固定算法：SHA-256，标准序列化
	// 用于交易ID和标准哈希计算，排除签名字段
	ComputeHash(ctx context.Context, in *ComputeHashRequest, opts ...grpc.CallOption) (*ComputeHashResponse, error)
	// 验证交易哈希（确定性）
	// 重新计算哈希并与期望值比较
	ValidateHash(ctx context.Context, in *ValidateHashRequest, opts ...grpc.CallOption) (*ValidateHashResponse, error)
	// 计算签名哈希（用于签名和验证）
	// 固定算法：SHA-256，根据 SIGHASH 类型修改交易结构
	// 支持 SIGHASH_ALL/NONE/SINGLE 和 ANYONECANPAY 组合
	// 用于签名时的哈希计算，排除签名字段并根据 SIGHASH 类型选择性包含输入输出
	ComputeSignatureHash(ctx context.Context, in *ComputeSignatureHashRequest, opts ...grpc.CallOption) (*ComputeSignatureHashResponse, error)
	// 验证签名哈希（用于签名验证）
	// 重新计算签名哈希并与期望值比较
	ValidateSignatureHash(ctx context.Context, in *ValidateSignatureHashRequest, opts ...grpc.CallOption) (*ValidateSignatureHashResponse, error)
}

type transactionHashServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionHashServiceClient(cc grpc.ClientConnInterface) TransactionHashServiceClient {
	return &transactionHashServiceClient{cc}
}

func (c *transactionHashServiceClient) ComputeHash(ctx context.Context, in *ComputeHashRequest, opts ...grpc.CallOption) (*ComputeHashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComputeHashResponse)
	err := c.cc.Invoke(ctx, TransactionHashService_ComputeHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionHashServiceClient) ValidateHash(ctx context.Context, in *ValidateHashRequest, opts ...grpc.CallOption) (*ValidateHashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateHashResponse)
	err := c.cc.Invoke(ctx, TransactionHashService_ValidateHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionHashServiceClient) ComputeSignatureHash(ctx context.Context, in *ComputeSignatureHashRequest, opts ...grpc.CallOption) (*ComputeSignatureHashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComputeSignatureHashResponse)
	err := c.cc.Invoke(ctx, TransactionHashService_ComputeSignatureHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionHashServiceClient) ValidateSignatureHash(ctx context.Context, in *ValidateSignatureHashRequest, opts ...grpc.CallOption) (*ValidateSignatureHashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateSignatureHashResponse)
	err := c.cc.Invoke(ctx, TransactionHashService_ValidateSignatureHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionHashServiceServer is the server API for TransactionHashService service.
// All implementations must embed UnimplementedTransactionHashServiceServer
// for forward compatibility.
//
// *
// TransactionHashService - 确定性交易哈希服务
type TransactionHashServiceServer interface {
	// 计算交易哈希（确定性）
	// 固定算法：SHA-256，标准序列化
	// 用于交易ID和标准哈希计算，排除签名字段
	ComputeHash(context.Context, *ComputeHashRequest) (*ComputeHashResponse, error)
	// 验证交易哈希（确定性）
	// 重新计算哈希并与期望值比较
	ValidateHash(context.Context, *ValidateHashRequest) (*ValidateHashResponse, error)
	// 计算签名哈希（用于签名和验证）
	// 固定算法：SHA-256，根据 SIGHASH 类型修改交易结构
	// 支持 SIGHASH_ALL/NONE/SINGLE 和 ANYONECANPAY 组合
	// 用于签名时的哈希计算，排除签名字段并根据 SIGHASH 类型选择性包含输入输出
	ComputeSignatureHash(context.Context, *ComputeSignatureHashRequest) (*ComputeSignatureHashResponse, error)
	// 验证签名哈希（用于签名验证）
	// 重新计算签名哈希并与期望值比较
	ValidateSignatureHash(context.Context, *ValidateSignatureHashRequest) (*ValidateSignatureHashResponse, error)
	mustEmbedUnimplementedTransactionHashServiceServer()
}

// UnimplementedTransactionHashServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransactionHashServiceServer struct{}

func (UnimplementedTransactionHashServiceServer) ComputeHash(context.Context, *ComputeHashRequest) (*ComputeHashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ComputeHash not implemented")
}
func (UnimplementedTransactionHashServiceServer) ValidateHash(context.Context, *ValidateHashRequest) (*ValidateHashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateHash not implemented")
}
func (UnimplementedTransactionHashServiceServer) ComputeSignatureHash(context.Context, *ComputeSignatureHashRequest) (*ComputeSignatureHashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ComputeSignatureHash not implemented")
}
func (UnimplementedTransactionHashServiceServer) ValidateSignatureHash(context.Context, *ValidateSignatureHashRequest) (*ValidateSignatureHashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateSignatureHash not implemented")
}
func (UnimplementedTransactionHashServiceServer) mustEmbedUnimplementedTransactionHashServiceServer() {
}
func (UnimplementedTransactionHashServiceServer) testEmbeddedByValue() {}

// UnsafeTransactionHashServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionHashServiceServer will
// result in compilation errors.
type UnsafeTransactionHashServiceServer interface {
	mustEmbedUnimplementedTransactionHashServiceServer()
}

func RegisterTransactionHashServiceServer(s grpc.ServiceRegistrar, srv TransactionHashServiceServer) {
	// If the following call panics, it indicates UnimplementedTransactionHashServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransactionHashService_ServiceDesc, srv)
}

func _TransactionHashService_ComputeHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionHashServiceServer).ComputeHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionHashService_ComputeHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionHashServiceServer).ComputeHash(ctx, req.(*ComputeHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionHashService_ValidateHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionHashServiceServer).ValidateHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionHashService_ValidateHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionHashServiceServer).ValidateHash(ctx, req.(*ValidateHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionHashService_ComputeSignatureHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeSignatureHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionHashServiceServer).ComputeSignatureHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionHashService_ComputeSignatureHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionHashServiceServer).ComputeSignatureHash(ctx, req.(*ComputeSignatureHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionHashService_ValidateSignatureHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateSignatureHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionHashServiceServer).ValidateSignatureHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionHashService_ValidateSignatureHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionHashServiceServer).ValidateSignatureHash(ctx, req.(*ValidateSignatureHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionHashService_ServiceDesc is the grpc.ServiceDesc for TransactionHashService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionHashService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.blockchain.core.TransactionHashService",
	HandlerType: (*TransactionHashServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ComputeHash",
			Handler:    _TransactionHashService_ComputeHash_Handler,
		},
		{
			MethodName: "ValidateHash",
			Handler:    _TransactionHashService_ValidateHash_Handler,
		},
		{
			MethodName: "ComputeSignatureHash",
			Handler:    _TransactionHashService_ComputeSignatureHash_Handler,
		},
		{
			MethodName: "ValidateSignatureHash",
			Handler:    _TransactionHashService_ValidateSignatureHash_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/blockchain/block/transaction/transaction.proto",
}
