// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: pb/network/transport/envelope.proto

package transport

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RpcResponse_Status int32

const (
	RpcResponse_OK    RpcResponse_Status = 0
	RpcResponse_ERROR RpcResponse_Status = 1
)

// Enum value maps for RpcResponse_Status.
var (
	RpcResponse_Status_name = map[int32]string{
		0: "OK",
		1: "ERROR",
	}
	RpcResponse_Status_value = map[string]int32{
		"OK":    0,
		"ERROR": 1,
	}
)

func (x RpcResponse_Status) Enum() *RpcResponse_Status {
	p := new(RpcResponse_Status)
	*p = x
	return p
}

func (x RpcResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RpcResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_network_transport_envelope_proto_enumTypes[0].Descriptor()
}

func (RpcResponse_Status) Type() protoreflect.EnumType {
	return &file_pb_network_transport_envelope_proto_enumTypes[0]
}

func (x RpcResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RpcResponse_Status.Descriptor instead.
func (RpcResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_pb_network_transport_envelope_proto_rawDescGZIP(), []int{2, 0}
}

// 通用载体：网络元信息 + 不透明业务载荷
type Envelope struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Version    uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ProtocolId string                 `protobuf:"bytes,2,opt,name=protocol_id,json=protocolId,proto3" json:"protocol_id,omitempty"` // 流式协议ID
	// 🎯 破坏性重构：Topic 结构化字段（替代原 string topic）
	// 原 topic 字段已废弃，使用以下结构化字段：
	// - namespace: 网络命名空间（如 "public-testnet-demo" / "mainnet-public"）
	// - domain:    协议域（如 "consensus" / "blockchain" / "network"）
	// - name:      主题名（如 "latest_block" / "tx_announce"）
	// - version:   版本号（如 "v1" / "v2"）
	Namespace    string `protobuf:"bytes,13,opt,name=namespace,proto3" json:"namespace,omitempty"`                           // 网络命名空间（新增）
	Domain       string `protobuf:"bytes,14,opt,name=domain,proto3" json:"domain,omitempty"`                                 // 协议域（新增）
	Name         string `protobuf:"bytes,15,opt,name=name,proto3" json:"name,omitempty"`                                     // 主题名（新增）
	TopicVersion string `protobuf:"bytes,16,opt,name=topic_version,json=topicVersion,proto3" json:"topic_version,omitempty"` // 主题版本（新增，避免与 Envelope.version 冲突）
	// ⚠️ 废弃字段（保留以兼容旧版本，但不应再使用）
	Topic         string `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`                                      // [废弃] 订阅主题，使用 namespace/domain/name/topic_version 替代
	ContentType   string `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`       // e.g. application/pb;type=BlockRange
	Encoding      string `protobuf:"bytes,5,opt,name=encoding,proto3" json:"encoding,omitempty"`                                // "pb" | "json" | "raw"
	Compression   string `protobuf:"bytes,6,opt,name=compression,proto3" json:"compression,omitempty"`                          // "none" | "gzip" | "snappy"
	Payload       []byte `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`                                  // 业务负载
	CorrelationId string `protobuf:"bytes,8,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"` // 请求链路ID
	FromPeerId    string `protobuf:"bytes,9,opt,name=from_peer_id,json=fromPeerId,proto3" json:"from_peer_id,omitempty"`
	Timestamp     uint64 `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`              // ms
	DedupKey      string `protobuf:"bytes,11,opt,name=dedup_key,json=dedupKey,proto3" json:"dedup_key,omitempty"` // 去重键
	Signature     []byte `protobuf:"bytes,12,opt,name=signature,proto3" json:"signature,omitempty"`               // 签名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_pb_network_transport_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_transport_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_pb_network_transport_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Envelope) GetProtocolId() string {
	if x != nil {
		return x.ProtocolId
	}
	return ""
}

func (x *Envelope) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Envelope) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Envelope) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Envelope) GetTopicVersion() string {
	if x != nil {
		return x.TopicVersion
	}
	return ""
}

func (x *Envelope) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Envelope) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Envelope) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

func (x *Envelope) GetCompression() string {
	if x != nil {
		return x.Compression
	}
	return ""
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Envelope) GetFromPeerId() string {
	if x != nil {
		return x.FromPeerId
	}
	return ""
}

func (x *Envelope) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Envelope) GetDedupKey() string {
	if x != nil {
		return x.DedupKey
	}
	return ""
}

func (x *Envelope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// 流式请求
type RpcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // 唯一请求ID
	Envelope      *Envelope              `protobuf:"bytes,2,opt,name=envelope,proto3" json:"envelope,omitempty"`                    // 业务载荷容器
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcRequest) Reset() {
	*x = RpcRequest{}
	mi := &file_pb_network_transport_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcRequest) ProtoMessage() {}

func (x *RpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_transport_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcRequest.ProtoReflect.Descriptor instead.
func (*RpcRequest) Descriptor() ([]byte, []int) {
	return file_pb_network_transport_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *RpcRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RpcRequest) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

// 流式响应
type RpcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        RpcResponse_Status     `protobuf:"varint,2,opt,name=status,proto3,enum=pb.network.transport.RpcResponse_Status" json:"status,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`         // 协议/业务自定义错误码空间（Network不解释）
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 简述
	Envelope      *Envelope              `protobuf:"bytes,5,opt,name=envelope,proto3" json:"envelope,omitempty"`                             // 成功时承载回包；错误时可为空
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcResponse) Reset() {
	*x = RpcResponse{}
	mi := &file_pb_network_transport_envelope_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcResponse) ProtoMessage() {}

func (x *RpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_transport_envelope_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcResponse.ProtoReflect.Descriptor instead.
func (*RpcResponse) Descriptor() ([]byte, []int) {
	return file_pb_network_transport_envelope_proto_rawDescGZIP(), []int{2}
}

func (x *RpcResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RpcResponse) GetStatus() RpcResponse_Status {
	if x != nil {
		return x.Status
	}
	return RpcResponse_OK
}

func (x *RpcResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *RpcResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RpcResponse) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

// 心跳
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // ms
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_pb_network_transport_envelope_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_transport_envelope_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_pb_network_transport_envelope_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 大报文分片（可选）
type StreamChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Index         uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"` // 0-based
	Total         uint32                 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Compression   string                 `protobuf:"bytes,4,opt,name=compression,proto3" json:"compression,omitempty"` // 分片压缩策略（可选）
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`               // 分片数据（可为Envelope序列化字节）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamChunk) Reset() {
	*x = StreamChunk{}
	mi := &file_pb_network_transport_envelope_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChunk) ProtoMessage() {}

func (x *StreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_transport_envelope_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChunk.ProtoReflect.Descriptor instead.
func (*StreamChunk) Descriptor() ([]byte, []int) {
	return file_pb_network_transport_envelope_proto_rawDescGZIP(), []int{4}
}

func (x *StreamChunk) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *StreamChunk) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *StreamChunk) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *StreamChunk) GetCompression() string {
	if x != nil {
		return x.Compression
	}
	return ""
}

func (x *StreamChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_pb_network_transport_envelope_proto protoreflect.FileDescriptor

const file_pb_network_transport_envelope_proto_rawDesc = "" +
	"\n" +
	"#pb/network/transport/envelope.proto\x12\x14pb.network.transport\"\xe7\x03\n" +
	"\bEnvelope\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1f\n" +
	"\vprotocol_id\x18\x02 \x01(\tR\n" +
	"protocolId\x12\x1c\n" +
	"\tnamespace\x18\r \x01(\tR\tnamespace\x12\x16\n" +
	"\x06domain\x18\x0e \x01(\tR\x06domain\x12\x12\n" +
	"\x04name\x18\x0f \x01(\tR\x04name\x12#\n" +
	"\rtopic_version\x18\x10 \x01(\tR\ftopicVersion\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x1a\n" +
	"\bencoding\x18\x05 \x01(\tR\bencoding\x12 \n" +
	"\vcompression\x18\x06 \x01(\tR\vcompression\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\x12%\n" +
	"\x0ecorrelation_id\x18\b \x01(\tR\rcorrelationId\x12 \n" +
	"\ffrom_peer_id\x18\t \x01(\tR\n" +
	"fromPeerId\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\x04R\ttimestamp\x12\x1b\n" +
	"\tdedup_key\x18\v \x01(\tR\bdedupKey\x12\x1c\n" +
	"\tsignature\x18\f \x01(\fR\tsignature\"g\n" +
	"\n" +
	"RpcRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12:\n" +
	"\benvelope\x18\x02 \x01(\v2\x1e.pb.network.transport.EnvelopeR\benvelope\"\x8b\x02\n" +
	"\vRpcResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12@\n" +
	"\x06status\x18\x02 \x01(\x0e2(.pb.network.transport.RpcResponse.StatusR\x06status\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\x05R\terrorCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12:\n" +
	"\benvelope\x18\x05 \x01(\v2\x1e.pb.network.transport.EnvelopeR\benvelope\"\x1b\n" +
	"\x06Status\x12\x06\n" +
	"\x02OK\x10\x00\x12\t\n" +
	"\x05ERROR\x10\x01\")\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\"\x8e\x01\n" +
	"\vStreamChunk\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\x12\x14\n" +
	"\x05total\x18\x03 \x01(\rR\x05total\x12 \n" +
	"\vcompression\x18\x04 \x01(\tR\vcompression\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04dataB+Z)github.com/weisyn/v1/pb/network/transportb\x06proto3"

var (
	file_pb_network_transport_envelope_proto_rawDescOnce sync.Once
	file_pb_network_transport_envelope_proto_rawDescData []byte
)

func file_pb_network_transport_envelope_proto_rawDescGZIP() []byte {
	file_pb_network_transport_envelope_proto_rawDescOnce.Do(func() {
		file_pb_network_transport_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_network_transport_envelope_proto_rawDesc), len(file_pb_network_transport_envelope_proto_rawDesc)))
	})
	return file_pb_network_transport_envelope_proto_rawDescData
}

var file_pb_network_transport_envelope_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_network_transport_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pb_network_transport_envelope_proto_goTypes = []any{
	(RpcResponse_Status)(0), // 0: pb.network.transport.RpcResponse.Status
	(*Envelope)(nil),        // 1: pb.network.transport.Envelope
	(*RpcRequest)(nil),      // 2: pb.network.transport.RpcRequest
	(*RpcResponse)(nil),     // 3: pb.network.transport.RpcResponse
	(*Heartbeat)(nil),       // 4: pb.network.transport.Heartbeat
	(*StreamChunk)(nil),     // 5: pb.network.transport.StreamChunk
}
var file_pb_network_transport_envelope_proto_depIdxs = []int32{
	1, // 0: pb.network.transport.RpcRequest.envelope:type_name -> pb.network.transport.Envelope
	0, // 1: pb.network.transport.RpcResponse.status:type_name -> pb.network.transport.RpcResponse.Status
	1, // 2: pb.network.transport.RpcResponse.envelope:type_name -> pb.network.transport.Envelope
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pb_network_transport_envelope_proto_init() }
func file_pb_network_transport_envelope_proto_init() {
	if File_pb_network_transport_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_network_transport_envelope_proto_rawDesc), len(file_pb_network_transport_envelope_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_network_transport_envelope_proto_goTypes,
		DependencyIndexes: file_pb_network_transport_envelope_proto_depIdxs,
		EnumInfos:         file_pb_network_transport_envelope_proto_enumTypes,
		MessageInfos:      file_pb_network_transport_envelope_proto_msgTypes,
	}.Build()
	File_pb_network_transport_envelope_proto = out.File
	file_pb_network_transport_envelope_proto_goTypes = nil
	file_pb_network_transport_envelope_proto_depIdxs = nil
}
