// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: pb/network/transport/message.proto

package transport

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType 定义基础P2P网络消息类型
type P2PMessage_MessageType int32

const (
	P2PMessage_UNKNOWN            P2PMessage_MessageType = 0
	P2PMessage_HANDSHAKE_REQUEST  P2PMessage_MessageType = 1 // 握手请求
	P2PMessage_HANDSHAKE_RESPONSE P2PMessage_MessageType = 2 // 握手响应
	P2PMessage_PING               P2PMessage_MessageType = 3 // Ping消息
	P2PMessage_PONG               P2PMessage_MessageType = 4 // Pong消息
	P2PMessage_DISCONNECT         P2PMessage_MessageType = 5 // 断开连接消息
	P2PMessage_PEERS_REQUEST      P2PMessage_MessageType = 6 // 节点请求
	P2PMessage_PEERS_RESPONSE     P2PMessage_MessageType = 7 // 节点响应
	P2PMessage_APPLICATION        P2PMessage_MessageType = 8 // 应用层消息(由高层协议处理)
)

// Enum value maps for P2PMessage_MessageType.
var (
	P2PMessage_MessageType_name = map[int32]string{
		0: "UNKNOWN",
		1: "HANDSHAKE_REQUEST",
		2: "HANDSHAKE_RESPONSE",
		3: "PING",
		4: "PONG",
		5: "DISCONNECT",
		6: "PEERS_REQUEST",
		7: "PEERS_RESPONSE",
		8: "APPLICATION",
	}
	P2PMessage_MessageType_value = map[string]int32{
		"UNKNOWN":            0,
		"HANDSHAKE_REQUEST":  1,
		"HANDSHAKE_RESPONSE": 2,
		"PING":               3,
		"PONG":               4,
		"DISCONNECT":         5,
		"PEERS_REQUEST":      6,
		"PEERS_RESPONSE":     7,
		"APPLICATION":        8,
	}
)

func (x P2PMessage_MessageType) Enum() *P2PMessage_MessageType {
	p := new(P2PMessage_MessageType)
	*p = x
	return p
}

func (x P2PMessage_MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (P2PMessage_MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_network_transport_message_proto_enumTypes[0].Descriptor()
}

func (P2PMessage_MessageType) Type() protoreflect.EnumType {
	return &file_pb_network_transport_message_proto_enumTypes[0]
}

func (x P2PMessage_MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use P2PMessage_MessageType.Descriptor instead.
func (P2PMessage_MessageType) EnumDescriptor() ([]byte, []int) {
	return file_pb_network_transport_message_proto_rawDescGZIP(), []int{0, 0}
}

type DisconnectMessage_DisconnectReason int32

const (
	DisconnectMessage_UNKNOWN              DisconnectMessage_DisconnectReason = 0
	DisconnectMessage_NORMAL_CLOSURE       DisconnectMessage_DisconnectReason = 1 // 正常关闭
	DisconnectMessage_PROTOCOL_BREACH      DisconnectMessage_DisconnectReason = 2 // 协议违规
	DisconnectMessage_USELESS_PEER         DisconnectMessage_DisconnectReason = 3 // 无用节点
	DisconnectMessage_TOO_MANY_PEERS       DisconnectMessage_DisconnectReason = 4 // 节点过多
	DisconnectMessage_DIFFERENT_NETWORK    DisconnectMessage_DisconnectReason = 5 // 不同的网络
	DisconnectMessage_INCOMPATIBLE_VERSION DisconnectMessage_DisconnectReason = 6 // 不兼容的版本
	DisconnectMessage_CLIENT_QUITTING      DisconnectMessage_DisconnectReason = 7 // 客户端退出
)

// Enum value maps for DisconnectMessage_DisconnectReason.
var (
	DisconnectMessage_DisconnectReason_name = map[int32]string{
		0: "UNKNOWN",
		1: "NORMAL_CLOSURE",
		2: "PROTOCOL_BREACH",
		3: "USELESS_PEER",
		4: "TOO_MANY_PEERS",
		5: "DIFFERENT_NETWORK",
		6: "INCOMPATIBLE_VERSION",
		7: "CLIENT_QUITTING",
	}
	DisconnectMessage_DisconnectReason_value = map[string]int32{
		"UNKNOWN":              0,
		"NORMAL_CLOSURE":       1,
		"PROTOCOL_BREACH":      2,
		"USELESS_PEER":         3,
		"TOO_MANY_PEERS":       4,
		"DIFFERENT_NETWORK":    5,
		"INCOMPATIBLE_VERSION": 6,
		"CLIENT_QUITTING":      7,
	}
)

func (x DisconnectMessage_DisconnectReason) Enum() *DisconnectMessage_DisconnectReason {
	p := new(DisconnectMessage_DisconnectReason)
	*p = x
	return p
}

func (x DisconnectMessage_DisconnectReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DisconnectMessage_DisconnectReason) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_network_transport_message_proto_enumTypes[1].Descriptor()
}

func (DisconnectMessage_DisconnectReason) Type() protoreflect.EnumType {
	return &file_pb_network_transport_message_proto_enumTypes[1]
}

func (x DisconnectMessage_DisconnectReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DisconnectMessage_DisconnectReason.Descriptor instead.
func (DisconnectMessage_DisconnectReason) EnumDescriptor() ([]byte, []int) {
	return file_pb_network_transport_message_proto_rawDescGZIP(), []int{5, 0}
}

// P2PMessage P2P网络基础消息包装器
type P2PMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          P2PMessage_MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=pb.network.transport.P2PMessage_MessageType" json:"type,omitempty"` // 消息类型
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`                        // 消息ID
	Timestamp     uint64                 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                        // 时间戳
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                                             // 消息载荷
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`                                         // 可选签名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P2PMessage) Reset() {
	*x = P2PMessage{}
	mi := &file_pb_network_transport_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P2PMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2PMessage) ProtoMessage() {}

func (x *P2PMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_transport_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2PMessage.ProtoReflect.Descriptor instead.
func (*P2PMessage) Descriptor() ([]byte, []int) {
	return file_pb_network_transport_message_proto_rawDescGZIP(), []int{0}
}

func (x *P2PMessage) GetType() P2PMessage_MessageType {
	if x != nil {
		return x.Type
	}
	return P2PMessage_UNKNOWN
}

func (x *P2PMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *P2PMessage) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *P2PMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *P2PMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// HandshakeRequest 握手请求
type HandshakeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PeerId          string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`                            // 节点ID (base58编码的libp2p peer.ID)
	Version         string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                                        // 协议版本
	Capabilities    *NodeCapabilities      `protobuf:"bytes,3,opt,name=capabilities,proto3" json:"capabilities,omitempty"`                              // 节点能力(使用node.proto中定义的类型)
	NetworkId       []byte                 `protobuf:"bytes,4,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`                   // 网络ID
	ListenAddresses []string               `protobuf:"bytes,5,rep,name=listen_addresses,json=listenAddresses,proto3" json:"listen_addresses,omitempty"` // 监听地址列表 (multiaddr格式)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_pb_network_transport_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_transport_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_pb_network_transport_message_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *HandshakeRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HandshakeRequest) GetCapabilities() *NodeCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *HandshakeRequest) GetNetworkId() []byte {
	if x != nil {
		return x.NetworkId
	}
	return nil
}

func (x *HandshakeRequest) GetListenAddresses() []string {
	if x != nil {
		return x.ListenAddresses
	}
	return nil
}

// HandshakeResponse 握手响应
type HandshakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accept        bool                   `protobuf:"varint,1,opt,name=accept,proto3" json:"accept,omitempty"` // 是否接受连接
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`  // 拒绝原因(如果不接受)
	Peers         []string               `protobuf:"bytes,3,rep,name=peers,proto3" json:"peers,omitempty"`    // 推荐节点列表 (multiaddr格式，包含peer ID)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_pb_network_transport_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_transport_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_pb_network_transport_message_proto_rawDescGZIP(), []int{2}
}

func (x *HandshakeResponse) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

func (x *HandshakeResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *HandshakeResponse) GetPeers() []string {
	if x != nil {
		return x.Peers
	}
	return nil
}

// Ping 消息
type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_pb_network_transport_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_transport_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_pb_network_transport_message_proto_rawDescGZIP(), []int{3}
}

func (x *Ping) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Pong 消息
type Pong struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Timestamp         uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                          // 时间戳
	OriginalTimestamp uint64                 `protobuf:"varint,2,opt,name=original_timestamp,json=originalTimestamp,proto3" json:"original_timestamp,omitempty"` // 原始Ping的时间戳
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_pb_network_transport_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_transport_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_pb_network_transport_message_proto_rawDescGZIP(), []int{4}
}

func (x *Pong) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Pong) GetOriginalTimestamp() uint64 {
	if x != nil {
		return x.OriginalTimestamp
	}
	return 0
}

// DisconnectMessage 断开连接消息
type DisconnectMessage struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Reason        DisconnectMessage_DisconnectReason `protobuf:"varint,1,opt,name=reason,proto3,enum=pb.network.transport.DisconnectMessage_DisconnectReason" json:"reason,omitempty"` // 断开原因
	Message       string                             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                                             // 附加消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectMessage) Reset() {
	*x = DisconnectMessage{}
	mi := &file_pb_network_transport_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectMessage) ProtoMessage() {}

func (x *DisconnectMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_transport_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectMessage.ProtoReflect.Descriptor instead.
func (*DisconnectMessage) Descriptor() ([]byte, []int) {
	return file_pb_network_transport_message_proto_rawDescGZIP(), []int{5}
}

func (x *DisconnectMessage) GetReason() DisconnectMessage_DisconnectReason {
	if x != nil {
		return x.Reason
	}
	return DisconnectMessage_UNKNOWN
}

func (x *DisconnectMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// PeersRequestMessage 节点请求消息
type PeersRequestMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MaxPeers       uint32                 `protobuf:"varint,1,opt,name=max_peers,json=maxPeers,proto3" json:"max_peers,omitempty"`                  // 最大返回节点数
	RequestedRoles []string               `protobuf:"bytes,2,rep,name=requested_roles,json=requestedRoles,proto3" json:"requested_roles,omitempty"` // 请求特定角色的节点
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PeersRequestMessage) Reset() {
	*x = PeersRequestMessage{}
	mi := &file_pb_network_transport_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeersRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeersRequestMessage) ProtoMessage() {}

func (x *PeersRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_transport_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeersRequestMessage.ProtoReflect.Descriptor instead.
func (*PeersRequestMessage) Descriptor() ([]byte, []int) {
	return file_pb_network_transport_message_proto_rawDescGZIP(), []int{6}
}

func (x *PeersRequestMessage) GetMaxPeers() uint32 {
	if x != nil {
		return x.MaxPeers
	}
	return 0
}

func (x *PeersRequestMessage) GetRequestedRoles() []string {
	if x != nil {
		return x.RequestedRoles
	}
	return nil
}

// PeersResponseMessage 节点响应消息
type PeersResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"` // 节点信息列表(使用node.proto中定义的PeerInfo类型)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeersResponseMessage) Reset() {
	*x = PeersResponseMessage{}
	mi := &file_pb_network_transport_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeersResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeersResponseMessage) ProtoMessage() {}

func (x *PeersResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_transport_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeersResponseMessage.ProtoReflect.Descriptor instead.
func (*PeersResponseMessage) Descriptor() ([]byte, []int) {
	return file_pb_network_transport_message_proto_rawDescGZIP(), []int{7}
}

func (x *PeersResponseMessage) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

var File_pb_network_transport_message_proto protoreflect.FileDescriptor

const file_pb_network_transport_message_proto_rawDesc = "" +
	"\n" +
	"\"pb/network/transport/message.proto\x12\x14pb.network.transport\x1a\x1fpb/network/transport/node.proto\"\xeb\x02\n" +
	"\n" +
	"P2PMessage\x12@\n" +
	"\x04type\x18\x01 \x01(\x0e2,.pb.network.transport.P2PMessage.MessageTypeR\x04type\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\"\xa5\x01\n" +
	"\vMessageType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x15\n" +
	"\x11HANDSHAKE_REQUEST\x10\x01\x12\x16\n" +
	"\x12HANDSHAKE_RESPONSE\x10\x02\x12\b\n" +
	"\x04PING\x10\x03\x12\b\n" +
	"\x04PONG\x10\x04\x12\x0e\n" +
	"\n" +
	"DISCONNECT\x10\x05\x12\x11\n" +
	"\rPEERS_REQUEST\x10\x06\x12\x12\n" +
	"\x0ePEERS_RESPONSE\x10\a\x12\x0f\n" +
	"\vAPPLICATION\x10\b\"\xdb\x01\n" +
	"\x10HandshakeRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12J\n" +
	"\fcapabilities\x18\x03 \x01(\v2&.pb.network.transport.NodeCapabilitiesR\fcapabilities\x12\x1d\n" +
	"\n" +
	"network_id\x18\x04 \x01(\fR\tnetworkId\x12)\n" +
	"\x10listen_addresses\x18\x05 \x03(\tR\x0flistenAddresses\"Y\n" +
	"\x11HandshakeResponse\x12\x16\n" +
	"\x06accept\x18\x01 \x01(\bR\x06accept\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x14\n" +
	"\x05peers\x18\x03 \x03(\tR\x05peers\"$\n" +
	"\x04Ping\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\"S\n" +
	"\x04Pong\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12-\n" +
	"\x12original_timestamp\x18\x02 \x01(\x04R\x11originalTimestamp\"\xb6\x02\n" +
	"\x11DisconnectMessage\x12P\n" +
	"\x06reason\x18\x01 \x01(\x0e28.pb.network.transport.DisconnectMessage.DisconnectReasonR\x06reason\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb4\x01\n" +
	"\x10DisconnectReason\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x12\n" +
	"\x0eNORMAL_CLOSURE\x10\x01\x12\x13\n" +
	"\x0fPROTOCOL_BREACH\x10\x02\x12\x10\n" +
	"\fUSELESS_PEER\x10\x03\x12\x12\n" +
	"\x0eTOO_MANY_PEERS\x10\x04\x12\x15\n" +
	"\x11DIFFERENT_NETWORK\x10\x05\x12\x18\n" +
	"\x14INCOMPATIBLE_VERSION\x10\x06\x12\x13\n" +
	"\x0fCLIENT_QUITTING\x10\a\"[\n" +
	"\x13PeersRequestMessage\x12\x1b\n" +
	"\tmax_peers\x18\x01 \x01(\rR\bmaxPeers\x12'\n" +
	"\x0frequested_roles\x18\x02 \x03(\tR\x0erequestedRoles\"L\n" +
	"\x14PeersResponseMessage\x124\n" +
	"\x05peers\x18\x01 \x03(\v2\x1e.pb.network.transport.PeerInfoR\x05peersB+Z)github.com/weisyn/v1/pb/network/transportb\x06proto3"

var (
	file_pb_network_transport_message_proto_rawDescOnce sync.Once
	file_pb_network_transport_message_proto_rawDescData []byte
)

func file_pb_network_transport_message_proto_rawDescGZIP() []byte {
	file_pb_network_transport_message_proto_rawDescOnce.Do(func() {
		file_pb_network_transport_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_network_transport_message_proto_rawDesc), len(file_pb_network_transport_message_proto_rawDesc)))
	})
	return file_pb_network_transport_message_proto_rawDescData
}

var file_pb_network_transport_message_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pb_network_transport_message_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pb_network_transport_message_proto_goTypes = []any{
	(P2PMessage_MessageType)(0),             // 0: pb.network.transport.P2PMessage.MessageType
	(DisconnectMessage_DisconnectReason)(0), // 1: pb.network.transport.DisconnectMessage.DisconnectReason
	(*P2PMessage)(nil),                      // 2: pb.network.transport.P2PMessage
	(*HandshakeRequest)(nil),                // 3: pb.network.transport.HandshakeRequest
	(*HandshakeResponse)(nil),               // 4: pb.network.transport.HandshakeResponse
	(*Ping)(nil),                            // 5: pb.network.transport.Ping
	(*Pong)(nil),                            // 6: pb.network.transport.Pong
	(*DisconnectMessage)(nil),               // 7: pb.network.transport.DisconnectMessage
	(*PeersRequestMessage)(nil),             // 8: pb.network.transport.PeersRequestMessage
	(*PeersResponseMessage)(nil),            // 9: pb.network.transport.PeersResponseMessage
	(*NodeCapabilities)(nil),                // 10: pb.network.transport.NodeCapabilities
	(*PeerInfo)(nil),                        // 11: pb.network.transport.PeerInfo
}
var file_pb_network_transport_message_proto_depIdxs = []int32{
	0,  // 0: pb.network.transport.P2PMessage.type:type_name -> pb.network.transport.P2PMessage.MessageType
	10, // 1: pb.network.transport.HandshakeRequest.capabilities:type_name -> pb.network.transport.NodeCapabilities
	1,  // 2: pb.network.transport.DisconnectMessage.reason:type_name -> pb.network.transport.DisconnectMessage.DisconnectReason
	11, // 3: pb.network.transport.PeersResponseMessage.peers:type_name -> pb.network.transport.PeerInfo
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_pb_network_transport_message_proto_init() }
func file_pb_network_transport_message_proto_init() {
	if File_pb_network_transport_message_proto != nil {
		return
	}
	file_pb_network_transport_node_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_network_transport_message_proto_rawDesc), len(file_pb_network_transport_message_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_network_transport_message_proto_goTypes,
		DependencyIndexes: file_pb_network_transport_message_proto_depIdxs,
		EnumInfos:         file_pb_network_transport_message_proto_enumTypes,
		MessageInfos:      file_pb_network_transport_message_proto_msgTypes,
	}.Build()
	File_pb_network_transport_message_proto = out.File
	file_pb_network_transport_message_proto_goTypes = nil
	file_pb_network_transport_message_proto_depIdxs = nil
}
