// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: pb/network/transport/node.proto

package transport

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeRole 节点角色枚举
type NodeRole int32

const (
	NodeRole_ROLE_UNKNOWN    NodeRole = 0
	NodeRole_ROLE_FULL_NODE  NodeRole = 1 // 全节点
	NodeRole_ROLE_LIGHT_NODE NodeRole = 2 // 轻节点
	NodeRole_ROLE_BOOTSTRAP  NodeRole = 3 // 引导节点
	NodeRole_ROLE_RELAY      NodeRole = 4 // 中继节点
	NodeRole_ROLE_VALIDATOR  NodeRole = 5 // 验证节点
	NodeRole_ROLE_ARCHIVE    NodeRole = 6 // 归档节点
)

// Enum value maps for NodeRole.
var (
	NodeRole_name = map[int32]string{
		0: "ROLE_UNKNOWN",
		1: "ROLE_FULL_NODE",
		2: "ROLE_LIGHT_NODE",
		3: "ROLE_BOOTSTRAP",
		4: "ROLE_RELAY",
		5: "ROLE_VALIDATOR",
		6: "ROLE_ARCHIVE",
	}
	NodeRole_value = map[string]int32{
		"ROLE_UNKNOWN":    0,
		"ROLE_FULL_NODE":  1,
		"ROLE_LIGHT_NODE": 2,
		"ROLE_BOOTSTRAP":  3,
		"ROLE_RELAY":      4,
		"ROLE_VALIDATOR":  5,
		"ROLE_ARCHIVE":    6,
	}
)

func (x NodeRole) Enum() *NodeRole {
	p := new(NodeRole)
	*p = x
	return p
}

func (x NodeRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeRole) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_network_transport_node_proto_enumTypes[0].Descriptor()
}

func (NodeRole) Type() protoreflect.EnumType {
	return &file_pb_network_transport_node_proto_enumTypes[0]
}

func (x NodeRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeRole.Descriptor instead.
func (NodeRole) EnumDescriptor() ([]byte, []int) {
	return file_pb_network_transport_node_proto_rawDescGZIP(), []int{0}
}

// NodeInfo 节点基础信息
type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                // 节点ID (base58编码的libp2p peer.ID)
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                      // 节点软件版本
	Protocols     []string               `protobuf:"bytes,3,rep,name=protocols,proto3" json:"protocols,omitempty"`                  // 支持的协议
	Addresses     []string               `protobuf:"bytes,4,rep,name=addresses,proto3" json:"addresses,omitempty"`                  // 节点地址列表 (multiaddr格式)
	NetworkId     []byte                 `protobuf:"bytes,5,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"` // 网络ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_pb_network_transport_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_transport_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_pb_network_transport_node_proto_rawDescGZIP(), []int{0}
}

func (x *NodeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *NodeInfo) GetProtocols() []string {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *NodeInfo) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *NodeInfo) GetNetworkId() []byte {
	if x != nil {
		return x.NetworkId
	}
	return nil
}

// NodeCapabilities 节点能力
type NodeCapabilities struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Roles              []NodeRole             `protobuf:"varint,1,rep,packed,name=roles,proto3,enum=pb.network.transport.NodeRole" json:"roles,omitempty"`          // 节点角色
	SupportedProtocols []string               `protobuf:"bytes,2,rep,name=supported_protocols,json=supportedProtocols,proto3" json:"supported_protocols,omitempty"` // 支持的协议
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NodeCapabilities) Reset() {
	*x = NodeCapabilities{}
	mi := &file_pb_network_transport_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCapabilities) ProtoMessage() {}

func (x *NodeCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_transport_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCapabilities.ProtoReflect.Descriptor instead.
func (*NodeCapabilities) Descriptor() ([]byte, []int) {
	return file_pb_network_transport_node_proto_rawDescGZIP(), []int{1}
}

func (x *NodeCapabilities) GetRoles() []NodeRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *NodeCapabilities) GetSupportedProtocols() []string {
	if x != nil {
		return x.SupportedProtocols
	}
	return nil
}

// PeerInfo 对等节点信息
type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                        // 节点ID (base58编码的libp2p peer.ID)
	Addresses     []string               `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`                                                                          // 地址列表 (multiaddr格式)
	Capabilities  *NodeCapabilities      `protobuf:"bytes,3,opt,name=capabilities,proto3" json:"capabilities,omitempty"`                                                                    // 节点能力
	Direction     string                 `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`                                                                          // 连接方向 ("inbound" 或 "outbound")
	LatencyMs     int64                  `protobuf:"varint,5,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`                                                        // 延迟(毫秒)
	IsTrusted     bool                   `protobuf:"varint,6,opt,name=is_trusted,json=isTrusted,proto3" json:"is_trusted,omitempty"`                                                        // 是否是可信节点
	ConnectedTime uint64                 `protobuf:"varint,7,opt,name=connected_time,json=connectedTime,proto3" json:"connected_time,omitempty"`                                            // 连接时间
	LastSeen      uint64                 `protobuf:"varint,8,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`                                                           // 最后可见时间
	Version       string                 `protobuf:"bytes,9,opt,name=version,proto3" json:"version,omitempty"`                                                                              // 软件版本
	Metadata      map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 附加元数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_pb_network_transport_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_transport_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_pb_network_transport_node_proto_rawDescGZIP(), []int{2}
}

func (x *PeerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PeerInfo) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *PeerInfo) GetCapabilities() *NodeCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *PeerInfo) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *PeerInfo) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *PeerInfo) GetIsTrusted() bool {
	if x != nil {
		return x.IsTrusted
	}
	return false
}

func (x *PeerInfo) GetConnectedTime() uint64 {
	if x != nil {
		return x.ConnectedTime
	}
	return 0
}

func (x *PeerInfo) GetLastSeen() uint64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *PeerInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PeerInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// PeerListRequest 节点列表请求
type PeerListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxPeers      int32                  `protobuf:"varint,1,opt,name=max_peers,json=maxPeers,proto3" json:"max_peers,omitempty"`          // 返回的最大节点数
	Capabilities  []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`                   // 过滤的能力
	IncludeSelf   bool                   `protobuf:"varint,3,opt,name=include_self,json=includeSelf,proto3" json:"include_self,omitempty"` // 是否包含自己
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerListRequest) Reset() {
	*x = PeerListRequest{}
	mi := &file_pb_network_transport_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerListRequest) ProtoMessage() {}

func (x *PeerListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_transport_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerListRequest.ProtoReflect.Descriptor instead.
func (*PeerListRequest) Descriptor() ([]byte, []int) {
	return file_pb_network_transport_node_proto_rawDescGZIP(), []int{3}
}

func (x *PeerListRequest) GetMaxPeers() int32 {
	if x != nil {
		return x.MaxPeers
	}
	return 0
}

func (x *PeerListRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *PeerListRequest) GetIncludeSelf() bool {
	if x != nil {
		return x.IncludeSelf
	}
	return false
}

// PeerListResponse 节点列表响应
type PeerListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`                              // 节点列表
	Self          *NodeInfo              `protobuf:"bytes,2,opt,name=self,proto3" json:"self,omitempty"`                                // 本节点信息
	TotalPeers    int32                  `protobuf:"varint,3,opt,name=total_peers,json=totalPeers,proto3" json:"total_peers,omitempty"` // 总节点数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerListResponse) Reset() {
	*x = PeerListResponse{}
	mi := &file_pb_network_transport_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerListResponse) ProtoMessage() {}

func (x *PeerListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_transport_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerListResponse.ProtoReflect.Descriptor instead.
func (*PeerListResponse) Descriptor() ([]byte, []int) {
	return file_pb_network_transport_node_proto_rawDescGZIP(), []int{4}
}

func (x *PeerListResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *PeerListResponse) GetSelf() *NodeInfo {
	if x != nil {
		return x.Self
	}
	return nil
}

func (x *PeerListResponse) GetTotalPeers() int32 {
	if x != nil {
		return x.TotalPeers
	}
	return 0
}

// BanPeerRequest 禁止节点请求
type BanPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"` // 节点ID
	Duration      uint64                 `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`          // 禁止时长(秒)，0表示永久
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`               // 禁止原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanPeerRequest) Reset() {
	*x = BanPeerRequest{}
	mi := &file_pb_network_transport_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanPeerRequest) ProtoMessage() {}

func (x *BanPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_transport_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanPeerRequest.ProtoReflect.Descriptor instead.
func (*BanPeerRequest) Descriptor() ([]byte, []int) {
	return file_pb_network_transport_node_proto_rawDescGZIP(), []int{5}
}

func (x *BanPeerRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *BanPeerRequest) GetDuration() uint64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *BanPeerRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// BanPeerResponse 禁止节点响应
type BanPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 结果消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanPeerResponse) Reset() {
	*x = BanPeerResponse{}
	mi := &file_pb_network_transport_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanPeerResponse) ProtoMessage() {}

func (x *BanPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_transport_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanPeerResponse.ProtoReflect.Descriptor instead.
func (*BanPeerResponse) Descriptor() ([]byte, []int) {
	return file_pb_network_transport_node_proto_rawDescGZIP(), []int{6}
}

func (x *BanPeerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BanPeerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pb_network_transport_node_proto protoreflect.FileDescriptor

const file_pb_network_transport_node_proto_rawDesc = "" +
	"\n" +
	"\x1fpb/network/transport/node.proto\x12\x14pb.network.transport\"\x8f\x01\n" +
	"\bNodeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1c\n" +
	"\tprotocols\x18\x03 \x03(\tR\tprotocols\x12\x1c\n" +
	"\taddresses\x18\x04 \x03(\tR\taddresses\x12\x1d\n" +
	"\n" +
	"network_id\x18\x05 \x01(\fR\tnetworkId\"y\n" +
	"\x10NodeCapabilities\x124\n" +
	"\x05roles\x18\x01 \x03(\x0e2\x1e.pb.network.transport.NodeRoleR\x05roles\x12/\n" +
	"\x13supported_protocols\x18\x02 \x03(\tR\x12supportedProtocols\"\xc5\x03\n" +
	"\bPeerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\taddresses\x18\x02 \x03(\tR\taddresses\x12J\n" +
	"\fcapabilities\x18\x03 \x01(\v2&.pb.network.transport.NodeCapabilitiesR\fcapabilities\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\tR\tdirection\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x05 \x01(\x03R\tlatencyMs\x12\x1d\n" +
	"\n" +
	"is_trusted\x18\x06 \x01(\bR\tisTrusted\x12%\n" +
	"\x0econnected_time\x18\a \x01(\x04R\rconnectedTime\x12\x1b\n" +
	"\tlast_seen\x18\b \x01(\x04R\blastSeen\x12\x18\n" +
	"\aversion\x18\t \x01(\tR\aversion\x12H\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2,.pb.network.transport.PeerInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"u\n" +
	"\x0fPeerListRequest\x12\x1b\n" +
	"\tmax_peers\x18\x01 \x01(\x05R\bmaxPeers\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\x12!\n" +
	"\finclude_self\x18\x03 \x01(\bR\vincludeSelf\"\x9d\x01\n" +
	"\x10PeerListResponse\x124\n" +
	"\x05peers\x18\x01 \x03(\v2\x1e.pb.network.transport.PeerInfoR\x05peers\x122\n" +
	"\x04self\x18\x02 \x01(\v2\x1e.pb.network.transport.NodeInfoR\x04self\x12\x1f\n" +
	"\vtotal_peers\x18\x03 \x01(\x05R\n" +
	"totalPeers\"]\n" +
	"\x0eBanPeerRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\x04R\bduration\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"E\n" +
	"\x0fBanPeerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\x8f\x01\n" +
	"\bNodeRole\x12\x10\n" +
	"\fROLE_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eROLE_FULL_NODE\x10\x01\x12\x13\n" +
	"\x0fROLE_LIGHT_NODE\x10\x02\x12\x12\n" +
	"\x0eROLE_BOOTSTRAP\x10\x03\x12\x0e\n" +
	"\n" +
	"ROLE_RELAY\x10\x04\x12\x12\n" +
	"\x0eROLE_VALIDATOR\x10\x05\x12\x10\n" +
	"\fROLE_ARCHIVE\x10\x06B+Z)github.com/weisyn/v1/pb/network/transportb\x06proto3"

var (
	file_pb_network_transport_node_proto_rawDescOnce sync.Once
	file_pb_network_transport_node_proto_rawDescData []byte
)

func file_pb_network_transport_node_proto_rawDescGZIP() []byte {
	file_pb_network_transport_node_proto_rawDescOnce.Do(func() {
		file_pb_network_transport_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_network_transport_node_proto_rawDesc), len(file_pb_network_transport_node_proto_rawDesc)))
	})
	return file_pb_network_transport_node_proto_rawDescData
}

var file_pb_network_transport_node_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_network_transport_node_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pb_network_transport_node_proto_goTypes = []any{
	(NodeRole)(0),            // 0: pb.network.transport.NodeRole
	(*NodeInfo)(nil),         // 1: pb.network.transport.NodeInfo
	(*NodeCapabilities)(nil), // 2: pb.network.transport.NodeCapabilities
	(*PeerInfo)(nil),         // 3: pb.network.transport.PeerInfo
	(*PeerListRequest)(nil),  // 4: pb.network.transport.PeerListRequest
	(*PeerListResponse)(nil), // 5: pb.network.transport.PeerListResponse
	(*BanPeerRequest)(nil),   // 6: pb.network.transport.BanPeerRequest
	(*BanPeerResponse)(nil),  // 7: pb.network.transport.BanPeerResponse
	nil,                      // 8: pb.network.transport.PeerInfo.MetadataEntry
}
var file_pb_network_transport_node_proto_depIdxs = []int32{
	0, // 0: pb.network.transport.NodeCapabilities.roles:type_name -> pb.network.transport.NodeRole
	2, // 1: pb.network.transport.PeerInfo.capabilities:type_name -> pb.network.transport.NodeCapabilities
	8, // 2: pb.network.transport.PeerInfo.metadata:type_name -> pb.network.transport.PeerInfo.MetadataEntry
	3, // 3: pb.network.transport.PeerListResponse.peers:type_name -> pb.network.transport.PeerInfo
	1, // 4: pb.network.transport.PeerListResponse.self:type_name -> pb.network.transport.NodeInfo
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pb_network_transport_node_proto_init() }
func file_pb_network_transport_node_proto_init() {
	if File_pb_network_transport_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_network_transport_node_proto_rawDesc), len(file_pb_network_transport_node_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_network_transport_node_proto_goTypes,
		DependencyIndexes: file_pb_network_transport_node_proto_depIdxs,
		EnumInfos:         file_pb_network_transport_node_proto_enumTypes,
		MessageInfos:      file_pb_network_transport_node_proto_msgTypes,
	}.Build()
	File_pb_network_transport_node_proto = out.File
	file_pb_network_transport_node_proto_goTypes = nil
	file_pb_network_transport_node_proto_depIdxs = nil
}
