// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: pb/hostabi/txplanning.proto

package hostabi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UnlockPlan 解锁计划
//
// 职责：为交易的所有输入生成签名任务列表
type UnlockPlan struct {
	state             protoimpl.MessageState    `protogen:"open.v1"`
	TxId              []byte                    `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`                                                                                                                      // 交易ID
	SignTasks         []*SignTask               `protobuf:"bytes,2,rep,name=sign_tasks,json=signTasks,proto3" json:"sign_tasks,omitempty"`                                                                                                       // 签名任务列表
	SignTasksBySigner map[string]*SignTaskGroup `protobuf:"bytes,3,rep,name=sign_tasks_by_signer,json=signTasksBySigner,proto3" json:"sign_tasks_by_signer,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 按signer分组的任务
	Metadata          map[string]string         `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`                                               // 元数据
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UnlockPlan) Reset() {
	*x = UnlockPlan{}
	mi := &file_pb_hostabi_txplanning_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockPlan) ProtoMessage() {}

func (x *UnlockPlan) ProtoReflect() protoreflect.Message {
	mi := &file_pb_hostabi_txplanning_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockPlan.ProtoReflect.Descriptor instead.
func (*UnlockPlan) Descriptor() ([]byte, []int) {
	return file_pb_hostabi_txplanning_proto_rawDescGZIP(), []int{0}
}

func (x *UnlockPlan) GetTxId() []byte {
	if x != nil {
		return x.TxId
	}
	return nil
}

func (x *UnlockPlan) GetSignTasks() []*SignTask {
	if x != nil {
		return x.SignTasks
	}
	return nil
}

func (x *UnlockPlan) GetSignTasksBySigner() map[string]*SignTaskGroup {
	if x != nil {
		return x.SignTasksBySigner
	}
	return nil
}

func (x *UnlockPlan) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// SignTask 签名任务
//
// 描述单个签名任务的所有信息
type SignTask struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	InputIndices        []uint32               `protobuf:"varint,1,rep,packed,name=input_indices,json=inputIndices,proto3" json:"input_indices,omitempty"`                // 输入索引列表（跨输入去重）
	LockType            string                 `protobuf:"bytes,2,opt,name=lock_type,json=lockType,proto3" json:"lock_type,omitempty"`                                    // 锁定类型（single_key/multi_key/contract等）
	SignerHint          string                 `protobuf:"bytes,3,opt,name=signer_hint,json=signerHint,proto3" json:"signer_hint,omitempty"`                              // 签名者提示（local/kms/hsm/multi_sig等）
	SigningAlgorithm    string                 `protobuf:"bytes,4,opt,name=signing_algorithm,json=signingAlgorithm,proto3" json:"signing_algorithm,omitempty"`            // 签名算法
	SighashType         string                 `protobuf:"bytes,5,opt,name=sighash_type,json=sighashType,proto3" json:"sighash_type,omitempty"`                           // 签名哈希类型
	RequiredPublicKeys  [][]byte               `protobuf:"bytes,6,rep,name=required_public_keys,json=requiredPublicKeys,proto3" json:"required_public_keys,omitempty"`    // 需要的公钥列表
	RequiredSignatures  uint32                 `protobuf:"varint,7,opt,name=required_signatures,json=requiredSignatures,proto3" json:"required_signatures,omitempty"`     // 需要的签名数量（多签）
	RequiredAddressHash []byte                 `protobuf:"bytes,8,opt,name=required_address_hash,json=requiredAddressHash,proto3" json:"required_address_hash,omitempty"` // 需要的地址哈希（P2PKH）
	ContractAddress     []byte                 `protobuf:"bytes,9,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`               // 合约地址（合约锁定）
	ContractMethod      string                 `protobuf:"bytes,10,opt,name=contract_method,json=contractMethod,proto3" json:"contract_method,omitempty"`                 // 合约方法（合约锁定）
	DelegationOwner     []byte                 `protobuf:"bytes,11,opt,name=delegation_owner,json=delegationOwner,proto3" json:"delegation_owner,omitempty"`              // 委托所有者（委托锁定）
	AllowedDelegates    [][]byte               `protobuf:"bytes,12,rep,name=allowed_delegates,json=allowedDelegates,proto3" json:"allowed_delegates,omitempty"`           // 允许的委托者（委托锁定）
	ThresholdN          uint32                 `protobuf:"varint,13,opt,name=threshold_n,json=thresholdN,proto3" json:"threshold_n,omitempty"`                            // 门限签名总数N
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SignTask) Reset() {
	*x = SignTask{}
	mi := &file_pb_hostabi_txplanning_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignTask) ProtoMessage() {}

func (x *SignTask) ProtoReflect() protoreflect.Message {
	mi := &file_pb_hostabi_txplanning_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignTask.ProtoReflect.Descriptor instead.
func (*SignTask) Descriptor() ([]byte, []int) {
	return file_pb_hostabi_txplanning_proto_rawDescGZIP(), []int{1}
}

func (x *SignTask) GetInputIndices() []uint32 {
	if x != nil {
		return x.InputIndices
	}
	return nil
}

func (x *SignTask) GetLockType() string {
	if x != nil {
		return x.LockType
	}
	return ""
}

func (x *SignTask) GetSignerHint() string {
	if x != nil {
		return x.SignerHint
	}
	return ""
}

func (x *SignTask) GetSigningAlgorithm() string {
	if x != nil {
		return x.SigningAlgorithm
	}
	return ""
}

func (x *SignTask) GetSighashType() string {
	if x != nil {
		return x.SighashType
	}
	return ""
}

func (x *SignTask) GetRequiredPublicKeys() [][]byte {
	if x != nil {
		return x.RequiredPublicKeys
	}
	return nil
}

func (x *SignTask) GetRequiredSignatures() uint32 {
	if x != nil {
		return x.RequiredSignatures
	}
	return 0
}

func (x *SignTask) GetRequiredAddressHash() []byte {
	if x != nil {
		return x.RequiredAddressHash
	}
	return nil
}

func (x *SignTask) GetContractAddress() []byte {
	if x != nil {
		return x.ContractAddress
	}
	return nil
}

func (x *SignTask) GetContractMethod() string {
	if x != nil {
		return x.ContractMethod
	}
	return ""
}

func (x *SignTask) GetDelegationOwner() []byte {
	if x != nil {
		return x.DelegationOwner
	}
	return nil
}

func (x *SignTask) GetAllowedDelegates() [][]byte {
	if x != nil {
		return x.AllowedDelegates
	}
	return nil
}

func (x *SignTask) GetThresholdN() uint32 {
	if x != nil {
		return x.ThresholdN
	}
	return 0
}

// SignTaskGroup 签名任务组（按signer分组）
type SignTaskGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignerHint    string                 `protobuf:"bytes,1,opt,name=signer_hint,json=signerHint,proto3" json:"signer_hint,omitempty"` // 签名者提示
	Tasks         []*SignTask            `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`                             // 任务列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignTaskGroup) Reset() {
	*x = SignTaskGroup{}
	mi := &file_pb_hostabi_txplanning_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignTaskGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignTaskGroup) ProtoMessage() {}

func (x *SignTaskGroup) ProtoReflect() protoreflect.Message {
	mi := &file_pb_hostabi_txplanning_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignTaskGroup.ProtoReflect.Descriptor instead.
func (*SignTaskGroup) Descriptor() ([]byte, []int) {
	return file_pb_hostabi_txplanning_proto_rawDescGZIP(), []int{2}
}

func (x *SignTaskGroup) GetSignerHint() string {
	if x != nil {
		return x.SignerHint
	}
	return ""
}

func (x *SignTaskGroup) GetTasks() []*SignTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

var File_pb_hostabi_txplanning_proto protoreflect.FileDescriptor

const file_pb_hostabi_txplanning_proto_rawDesc = "" +
	"\n" +
	"\x1bpb/hostabi/txplanning.proto\x12\n" +
	"pb.hostabi\"\x96\x03\n" +
	"\n" +
	"UnlockPlan\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\fR\x04txId\x123\n" +
	"\n" +
	"sign_tasks\x18\x02 \x03(\v2\x14.pb.hostabi.SignTaskR\tsignTasks\x12^\n" +
	"\x14sign_tasks_by_signer\x18\x03 \x03(\v2-.pb.hostabi.UnlockPlan.SignTasksBySignerEntryR\x11signTasksBySigner\x12@\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2$.pb.hostabi.UnlockPlan.MetadataEntryR\bmetadata\x1a_\n" +
	"\x16SignTasksBySignerEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.pb.hostabi.SignTaskGroupR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa1\x04\n" +
	"\bSignTask\x12#\n" +
	"\rinput_indices\x18\x01 \x03(\rR\finputIndices\x12\x1b\n" +
	"\tlock_type\x18\x02 \x01(\tR\blockType\x12\x1f\n" +
	"\vsigner_hint\x18\x03 \x01(\tR\n" +
	"signerHint\x12+\n" +
	"\x11signing_algorithm\x18\x04 \x01(\tR\x10signingAlgorithm\x12!\n" +
	"\fsighash_type\x18\x05 \x01(\tR\vsighashType\x120\n" +
	"\x14required_public_keys\x18\x06 \x03(\fR\x12requiredPublicKeys\x12/\n" +
	"\x13required_signatures\x18\a \x01(\rR\x12requiredSignatures\x122\n" +
	"\x15required_address_hash\x18\b \x01(\fR\x13requiredAddressHash\x12)\n" +
	"\x10contract_address\x18\t \x01(\fR\x0fcontractAddress\x12'\n" +
	"\x0fcontract_method\x18\n" +
	" \x01(\tR\x0econtractMethod\x12)\n" +
	"\x10delegation_owner\x18\v \x01(\fR\x0fdelegationOwner\x12+\n" +
	"\x11allowed_delegates\x18\f \x03(\fR\x10allowedDelegates\x12\x1f\n" +
	"\vthreshold_n\x18\r \x01(\rR\n" +
	"thresholdN\"\\\n" +
	"\rSignTaskGroup\x12\x1f\n" +
	"\vsigner_hint\x18\x01 \x01(\tR\n" +
	"signerHint\x12*\n" +
	"\x05tasks\x18\x02 \x03(\v2\x14.pb.hostabi.SignTaskR\x05tasksB!Z\x1fgithub.com/weisyn/v1/pb/hostabib\x06proto3"

var (
	file_pb_hostabi_txplanning_proto_rawDescOnce sync.Once
	file_pb_hostabi_txplanning_proto_rawDescData []byte
)

func file_pb_hostabi_txplanning_proto_rawDescGZIP() []byte {
	file_pb_hostabi_txplanning_proto_rawDescOnce.Do(func() {
		file_pb_hostabi_txplanning_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_hostabi_txplanning_proto_rawDesc), len(file_pb_hostabi_txplanning_proto_rawDesc)))
	})
	return file_pb_hostabi_txplanning_proto_rawDescData
}

var file_pb_hostabi_txplanning_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pb_hostabi_txplanning_proto_goTypes = []any{
	(*UnlockPlan)(nil),    // 0: pb.hostabi.UnlockPlan
	(*SignTask)(nil),      // 1: pb.hostabi.SignTask
	(*SignTaskGroup)(nil), // 2: pb.hostabi.SignTaskGroup
	nil,                   // 3: pb.hostabi.UnlockPlan.SignTasksBySignerEntry
	nil,                   // 4: pb.hostabi.UnlockPlan.MetadataEntry
}
var file_pb_hostabi_txplanning_proto_depIdxs = []int32{
	1, // 0: pb.hostabi.UnlockPlan.sign_tasks:type_name -> pb.hostabi.SignTask
	3, // 1: pb.hostabi.UnlockPlan.sign_tasks_by_signer:type_name -> pb.hostabi.UnlockPlan.SignTasksBySignerEntry
	4, // 2: pb.hostabi.UnlockPlan.metadata:type_name -> pb.hostabi.UnlockPlan.MetadataEntry
	1, // 3: pb.hostabi.SignTaskGroup.tasks:type_name -> pb.hostabi.SignTask
	2, // 4: pb.hostabi.UnlockPlan.SignTasksBySignerEntry.value:type_name -> pb.hostabi.SignTaskGroup
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pb_hostabi_txplanning_proto_init() }
func file_pb_hostabi_txplanning_proto_init() {
	if File_pb_hostabi_txplanning_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_hostabi_txplanning_proto_rawDesc), len(file_pb_hostabi_txplanning_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_hostabi_txplanning_proto_goTypes,
		DependencyIndexes: file_pb_hostabi_txplanning_proto_depIdxs,
		MessageInfos:      file_pb_hostabi_txplanning_proto_msgTypes,
	}.Build()
	File_pb_hostabi_txplanning_proto = out.File
	file_pb_hostabi_txplanning_proto_goTypes = nil
	file_pb_hostabi_txplanning_proto_depIdxs = nil
}
