// ================================================================================================
// UTXO 子系统协议（严格遵循主流UTXO原则的扩展实现）
// ================================================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: pb/blockchain/utxo/utxo.proto

package utxo

import (
	transaction "github.com/weisyn/v1/pb/blockchain/block/transaction"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// UTXOCategory - UTXO类型分类（严格对应Transaction.TxOutput的三种类型）
//
// 🎯 分类依据：根据TxOutput.output_content的类型自动推导
// • AssetOutput → UTXO_CATEGORY_ASSET
// • ResourceOutput → UTXO_CATEGORY_RESOURCE
// • StateOutput → UTXO_CATEGORY_STATE
type UTXOCategory int32

const (
	UTXOCategory_UTXO_CATEGORY_UNKNOWN  UTXOCategory = 0 // 未知类型（不应出现）
	UTXOCategory_UTXO_CATEGORY_ASSET    UTXOCategory = 1 // 价值载体：来自AssetOutput
	UTXOCategory_UTXO_CATEGORY_RESOURCE UTXOCategory = 2 // 能力载体：来自ResourceOutput
	UTXOCategory_UTXO_CATEGORY_STATE    UTXOCategory = 3 // 证据载体：来自StateOutput
)

// Enum value maps for UTXOCategory.
var (
	UTXOCategory_name = map[int32]string{
		0: "UTXO_CATEGORY_UNKNOWN",
		1: "UTXO_CATEGORY_ASSET",
		2: "UTXO_CATEGORY_RESOURCE",
		3: "UTXO_CATEGORY_STATE",
	}
	UTXOCategory_value = map[string]int32{
		"UTXO_CATEGORY_UNKNOWN":  0,
		"UTXO_CATEGORY_ASSET":    1,
		"UTXO_CATEGORY_RESOURCE": 2,
		"UTXO_CATEGORY_STATE":    3,
	}
)

func (x UTXOCategory) Enum() *UTXOCategory {
	p := new(UTXOCategory)
	*p = x
	return p
}

func (x UTXOCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UTXOCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_blockchain_utxo_utxo_proto_enumTypes[0].Descriptor()
}

func (UTXOCategory) Type() protoreflect.EnumType {
	return &file_pb_blockchain_utxo_utxo_proto_enumTypes[0]
}

func (x UTXOCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UTXOCategory.Descriptor instead.
func (UTXOCategory) EnumDescriptor() ([]byte, []int) {
	return file_pb_blockchain_utxo_utxo_proto_rawDescGZIP(), []int{0}
}

// *
// UTXOLifecycleStatus - UTXO生命周期状态（简化明确）
//
// 🎯 设计理念：反映UTXO在区块链系统中的实际状态，支持并发引用机制
//
// 📋 状态转换规则：
// • AssetUTXO: AVAILABLE → CONSUMED（简单消费模式）
// • ResourceUTXO: AVAILABLE → REFERENCED（引用时）→ AVAILABLE（引用结束）→ CONSUMED（最终消费）
// • StateUTXO: AVAILABLE → EXPIRED（TTL过期）→ AVAILABLE（可继续使用或被清理）
//
// ⚠️ 状态转换约束：
// • AVAILABLE: 所有操作均可执行（引用、消费）
// • REFERENCED: 只能引用，不能消费（ResourceUTXO专用）
// • CONSUMED: 终态，UTXO已从可用集合移除
// • EXPIRED: StateUTXO专用，过期但仍可查询
type UTXOLifecycleStatus int32

const (
	UTXOLifecycleStatus_UTXO_LIFECYCLE_UNKNOWN    UTXOLifecycleStatus = 0 // 未知状态（不应出现，用于错误检测）
	UTXOLifecycleStatus_UTXO_LIFECYCLE_AVAILABLE  UTXOLifecycleStatus = 1 // 可用状态：可被引用或消费
	UTXOLifecycleStatus_UTXO_LIFECYCLE_REFERENCED UTXOLifecycleStatus = 2 // 被引用状态：ResourceUTXO正在被并发引用
	UTXOLifecycleStatus_UTXO_LIFECYCLE_CONSUMED   UTXOLifecycleStatus = 3 // 已消费状态：UTXO已被花费，从可用集合移除
	UTXOLifecycleStatus_UTXO_LIFECYCLE_EXPIRED    UTXOLifecycleStatus = 4 // 已过期状态：StateUTXO的TTL已到期（但仍可访问）
)

// Enum value maps for UTXOLifecycleStatus.
var (
	UTXOLifecycleStatus_name = map[int32]string{
		0: "UTXO_LIFECYCLE_UNKNOWN",
		1: "UTXO_LIFECYCLE_AVAILABLE",
		2: "UTXO_LIFECYCLE_REFERENCED",
		3: "UTXO_LIFECYCLE_CONSUMED",
		4: "UTXO_LIFECYCLE_EXPIRED",
	}
	UTXOLifecycleStatus_value = map[string]int32{
		"UTXO_LIFECYCLE_UNKNOWN":    0,
		"UTXO_LIFECYCLE_AVAILABLE":  1,
		"UTXO_LIFECYCLE_REFERENCED": 2,
		"UTXO_LIFECYCLE_CONSUMED":   3,
		"UTXO_LIFECYCLE_EXPIRED":    4,
	}
)

func (x UTXOLifecycleStatus) Enum() *UTXOLifecycleStatus {
	p := new(UTXOLifecycleStatus)
	*p = x
	return p
}

func (x UTXOLifecycleStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UTXOLifecycleStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_blockchain_utxo_utxo_proto_enumTypes[1].Descriptor()
}

func (UTXOLifecycleStatus) Type() protoreflect.EnumType {
	return &file_pb_blockchain_utxo_utxo_proto_enumTypes[1]
}

func (x UTXOLifecycleStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UTXOLifecycleStatus.Descriptor instead.
func (UTXOLifecycleStatus) EnumDescriptor() ([]byte, []int) {
	return file_pb_blockchain_utxo_utxo_proto_rawDescGZIP(), []int{1}
}

// *
// ████████████████████████████████████████████████████████████████████████████████████████████
// UTXO - 业务导向的状态记录（解决实际问题而非追求设计完备）
// ████████████████████████████████████████████████████████████████████████████████████████████
//
// 🎯 核心使命：解决用户真实业务需求
// • 支持高效的余额查询："我有多少WES？多少TokenA？"
// • 支持资源状态管理："我的合约在哪？能否被消费？"
// • 支持并发安全控制：确保ResourceUTXO不会被意外移除
// • 支持交易验证约束：提供验证所需的状态信息
//
// 📋 数据源头约束（严格执行）：
// • **业务内容**：完全来自pb.blockchain.core.TxOutput，不增删改
// • **约束信息**：仅包含影响交易验证的状态（如引用计数）
// • **删除冗余**：移除可计算的统计信息和描述性字段
//
// 🔄 生命周期约束：
// 1. **创建**：Transaction执行 → 产生TxOutput → 创建对应UTXO
// 2. **可用**：status=AVAILABLE → 可被引用或消费
// 3. **引用**（仅ResourceUTXO）：is_reference_only=true → reference_count++，禁止消费
// 4. **消费**：is_reference_only=false → 移除UTXO（ResourceUTXO需reference_count=0）
//
// 💡 设计约束（防止功能蔓延）：
// • **约束驱动**：只存储影响交易验证的状态信息
// • **业务支撑**：为核心查询提供基础数据，复杂查询在API层实现
// • **可计算排除**：不存储可通过遍历区块链计算的信息
// • **描述性排除**：不存储纯描述性、对约束无影响的信息
// ████████████████████████████████████████████████████████████████████████████████████████████
type UTXO struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ==================== 🎯 核心身份标识 ====================
	Outpoint     *transaction.OutPoint `protobuf:"bytes,1,opt,name=outpoint,proto3" json:"outpoint,omitempty"`                                       // UTXO唯一位置引用（tx_hash + output_index）
	Category     UTXOCategory          `protobuf:"varint,2,opt,name=category,proto3,enum=pb.blockchain.utxo.UTXOCategory" json:"category,omitempty"` // UTXO类型（Asset/Resource/State）
	OwnerAddress []byte                `protobuf:"bytes,3,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`           // 所有者地址（20字节WES地址）
	// ==================== ⏰ 创建信息 ====================
	BlockHeight      uint64 `protobuf:"varint,4,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`                // 创建区块高度（从1开始递增）
	CreatedTimestamp uint64 `protobuf:"varint,5,opt,name=created_timestamp,json=createdTimestamp,proto3" json:"created_timestamp,omitempty"` // 创建时间戳（Unix时间，秒）
	// ==================== 🔄 通用状态信息 ====================
	Status UTXOLifecycleStatus `protobuf:"varint,10,opt,name=status,proto3,enum=pb.blockchain.utxo.UTXOLifecycleStatus" json:"status,omitempty"` // 生命周期状态（影响交易验证）
	// ==================== 🎯 类型特定的约束信息（oneof优化）====================
	//
	// Types that are valid to be assigned to TypeSpecificConstraints:
	//
	//	*UTXO_AssetConstraints
	//	*UTXO_ResourceConstraints
	//	*UTXO_StateConstraints
	TypeSpecificConstraints isUTXO_TypeSpecificConstraints `protobuf_oneof:"type_specific_constraints"`
	// ==================== 📦 TxOutput内容存储策略 ====================
	//
	// Types that are valid to be assigned to ContentStrategy:
	//
	//	*UTXO_CachedOutput
	//	*UTXO_ReferenceOnly
	ContentStrategy isUTXO_ContentStrategy `protobuf_oneof:"content_strategy"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UTXO) Reset() {
	*x = UTXO{}
	mi := &file_pb_blockchain_utxo_utxo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UTXO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UTXO) ProtoMessage() {}

func (x *UTXO) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blockchain_utxo_utxo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UTXO.ProtoReflect.Descriptor instead.
func (*UTXO) Descriptor() ([]byte, []int) {
	return file_pb_blockchain_utxo_utxo_proto_rawDescGZIP(), []int{0}
}

func (x *UTXO) GetOutpoint() *transaction.OutPoint {
	if x != nil {
		return x.Outpoint
	}
	return nil
}

func (x *UTXO) GetCategory() UTXOCategory {
	if x != nil {
		return x.Category
	}
	return UTXOCategory_UTXO_CATEGORY_UNKNOWN
}

func (x *UTXO) GetOwnerAddress() []byte {
	if x != nil {
		return x.OwnerAddress
	}
	return nil
}

func (x *UTXO) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *UTXO) GetCreatedTimestamp() uint64 {
	if x != nil {
		return x.CreatedTimestamp
	}
	return 0
}

func (x *UTXO) GetStatus() UTXOLifecycleStatus {
	if x != nil {
		return x.Status
	}
	return UTXOLifecycleStatus_UTXO_LIFECYCLE_UNKNOWN
}

func (x *UTXO) GetTypeSpecificConstraints() isUTXO_TypeSpecificConstraints {
	if x != nil {
		return x.TypeSpecificConstraints
	}
	return nil
}

func (x *UTXO) GetAssetConstraints() *AssetUTXOConstraints {
	if x != nil {
		if x, ok := x.TypeSpecificConstraints.(*UTXO_AssetConstraints); ok {
			return x.AssetConstraints
		}
	}
	return nil
}

func (x *UTXO) GetResourceConstraints() *ResourceUTXOConstraints {
	if x != nil {
		if x, ok := x.TypeSpecificConstraints.(*UTXO_ResourceConstraints); ok {
			return x.ResourceConstraints
		}
	}
	return nil
}

func (x *UTXO) GetStateConstraints() *StateUTXOConstraints {
	if x != nil {
		if x, ok := x.TypeSpecificConstraints.(*UTXO_StateConstraints); ok {
			return x.StateConstraints
		}
	}
	return nil
}

func (x *UTXO) GetContentStrategy() isUTXO_ContentStrategy {
	if x != nil {
		return x.ContentStrategy
	}
	return nil
}

func (x *UTXO) GetCachedOutput() *transaction.TxOutput {
	if x != nil {
		if x, ok := x.ContentStrategy.(*UTXO_CachedOutput); ok {
			return x.CachedOutput
		}
	}
	return nil
}

func (x *UTXO) GetReferenceOnly() bool {
	if x != nil {
		if x, ok := x.ContentStrategy.(*UTXO_ReferenceOnly); ok {
			return x.ReferenceOnly
		}
	}
	return false
}

type isUTXO_TypeSpecificConstraints interface {
	isUTXO_TypeSpecificConstraints()
}

type UTXO_AssetConstraints struct {
	AssetConstraints *AssetUTXOConstraints `protobuf:"bytes,11,opt,name=asset_constraints,json=assetConstraints,proto3,oneof"` // AssetUTXO特定约束（当前为空，预留扩展）
}

type UTXO_ResourceConstraints struct {
	ResourceConstraints *ResourceUTXOConstraints `protobuf:"bytes,12,opt,name=resource_constraints,json=resourceConstraints,proto3,oneof"` // ResourceUTXO特定约束（引用计数等）
}

type UTXO_StateConstraints struct {
	StateConstraints *StateUTXOConstraints `protobuf:"bytes,13,opt,name=state_constraints,json=stateConstraints,proto3,oneof"` // StateUTXO特定约束（TTL等）
}

func (*UTXO_AssetConstraints) isUTXO_TypeSpecificConstraints() {}

func (*UTXO_ResourceConstraints) isUTXO_TypeSpecificConstraints() {}

func (*UTXO_StateConstraints) isUTXO_TypeSpecificConstraints() {}

type isUTXO_ContentStrategy interface {
	isUTXO_ContentStrategy()
}

type UTXO_CachedOutput struct {
	CachedOutput *transaction.TxOutput `protobuf:"bytes,20,opt,name=cached_output,json=cachedOutput,proto3,oneof"` // 热数据：缓存完整TxOutput（支持高效查询）
}

type UTXO_ReferenceOnly struct {
	ReferenceOnly bool `protobuf:"varint,21,opt,name=reference_only,json=referenceOnly,proto3,oneof"` // 冷数据：仅引用，查询时回溯获取内容
}

func (*UTXO_CachedOutput) isUTXO_ContentStrategy() {}

func (*UTXO_ReferenceOnly) isUTXO_ContentStrategy() {}

// *
// AssetUTXOConstraints - AssetUTXO特定的约束信息
//
// 🎯 设计理念：AssetUTXO相对简单，主要用于价值转移
// 当前为预留结构，未来可扩展锁定期、冻结状态等功能
type AssetUTXOConstraints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetUTXOConstraints) Reset() {
	*x = AssetUTXOConstraints{}
	mi := &file_pb_blockchain_utxo_utxo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetUTXOConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetUTXOConstraints) ProtoMessage() {}

func (x *AssetUTXOConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blockchain_utxo_utxo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetUTXOConstraints.ProtoReflect.Descriptor instead.
func (*AssetUTXOConstraints) Descriptor() ([]byte, []int) {
	return file_pb_blockchain_utxo_utxo_proto_rawDescGZIP(), []int{1}
}

// *
// ResourceUTXOConstraints - ResourceUTXO特定的约束信息
//
// 🎯 设计理念：ResourceUTXO需要支持并发引用机制，包含引用计数等约束
// 这些约束直接影响交易验证逻辑
type ResourceUTXOConstraints struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ReferenceCount          uint64                 `protobuf:"varint,1,opt,name=reference_count,json=referenceCount,proto3" json:"reference_count,omitempty"`                                    // 当前活跃引用计数
	MaxConcurrentReferences *uint64                `protobuf:"varint,2,opt,name=max_concurrent_references,json=maxConcurrentReferences,proto3,oneof" json:"max_concurrent_references,omitempty"` // 最大并发引用数限制（可选）
	TotalReferenceCount     *uint64                `protobuf:"varint,3,opt,name=total_reference_count,json=totalReferenceCount,proto3,oneof" json:"total_reference_count,omitempty"`             // 历史总引用次数（可选统计）
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ResourceUTXOConstraints) Reset() {
	*x = ResourceUTXOConstraints{}
	mi := &file_pb_blockchain_utxo_utxo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceUTXOConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUTXOConstraints) ProtoMessage() {}

func (x *ResourceUTXOConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blockchain_utxo_utxo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUTXOConstraints.ProtoReflect.Descriptor instead.
func (*ResourceUTXOConstraints) Descriptor() ([]byte, []int) {
	return file_pb_blockchain_utxo_utxo_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceUTXOConstraints) GetReferenceCount() uint64 {
	if x != nil {
		return x.ReferenceCount
	}
	return 0
}

func (x *ResourceUTXOConstraints) GetMaxConcurrentReferences() uint64 {
	if x != nil && x.MaxConcurrentReferences != nil {
		return *x.MaxConcurrentReferences
	}
	return 0
}

func (x *ResourceUTXOConstraints) GetTotalReferenceCount() uint64 {
	if x != nil && x.TotalReferenceCount != nil {
		return *x.TotalReferenceCount
	}
	return 0
}

// *
// StateUTXOConstraints - StateUTXO特定的约束信息
//
// 🎯 设计理念：StateUTXO可能包含TTL、过期策略等状态管理约束
// 支持零知识证明的状态记录和时效性管理
type StateUTXOConstraints struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TtlSeconds         *uint64                `protobuf:"varint,1,opt,name=ttl_seconds,json=ttlSeconds,proto3,oneof" json:"ttl_seconds,omitempty"`                           // 生存时间（秒）
	ExpiresAtTimestamp *uint64                `protobuf:"varint,2,opt,name=expires_at_timestamp,json=expiresAtTimestamp,proto3,oneof" json:"expires_at_timestamp,omitempty"` // 绝对过期时间戳
	RetentionPolicy    *uint32                `protobuf:"varint,3,opt,name=retention_policy,json=retentionPolicy,proto3,oneof" json:"retention_policy,omitempty"`            // 保留策略（位掩码）
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StateUTXOConstraints) Reset() {
	*x = StateUTXOConstraints{}
	mi := &file_pb_blockchain_utxo_utxo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateUTXOConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateUTXOConstraints) ProtoMessage() {}

func (x *StateUTXOConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blockchain_utxo_utxo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateUTXOConstraints.ProtoReflect.Descriptor instead.
func (*StateUTXOConstraints) Descriptor() ([]byte, []int) {
	return file_pb_blockchain_utxo_utxo_proto_rawDescGZIP(), []int{3}
}

func (x *StateUTXOConstraints) GetTtlSeconds() uint64 {
	if x != nil && x.TtlSeconds != nil {
		return *x.TtlSeconds
	}
	return 0
}

func (x *StateUTXOConstraints) GetExpiresAtTimestamp() uint64 {
	if x != nil && x.ExpiresAtTimestamp != nil {
		return *x.ExpiresAtTimestamp
	}
	return 0
}

func (x *StateUTXOConstraints) GetRetentionPolicy() uint32 {
	if x != nil && x.RetentionPolicy != nil {
		return *x.RetentionPolicy
	}
	return 0
}

// *
// ████████████████████████████████████████████████████████████████████████████████████████████
// UTXOSet - 最小必要功能的UTXO集合管理（避免功能蔓延）
// ████████████████████████████████████████████████████████████████████████████████████████████
//
// 🎯 唯一职责：UTXO集合的完整性保证
// • Merkle根验证：确保UTXO集合数据完整性
// • 这是区块链系统的基础要求，必须保留
//
// ❌ 移除的冗余功能：
// • 引用计数管理 → 已集成到UTXO.reference_count中，无需重复
// • 统计信息 → 可通过遍历UTXO集合计算，无需存储
// • 版本追踪 → 可通过区块高度推导，无需额外字段
//
// 💡 设计哲学：UTXO集合只负责完整性，不负责统计和监控
// ████████████████████████████████████████████████████████████████████████████████████████████
type UTXOSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ==================== 🔒 唯一必要功能：完整性保证 ====================
	MerkleRoot       []byte `protobuf:"bytes,1,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`                      // UTXO集合Merkle根（唯一必要的完整性验证）
	LastUpdateHeight uint64 `protobuf:"varint,2,opt,name=last_update_height,json=lastUpdateHeight,proto3" json:"last_update_height,omitempty"` // 最后更新区块高度（Merkle根对应的高度）
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UTXOSet) Reset() {
	*x = UTXOSet{}
	mi := &file_pb_blockchain_utxo_utxo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UTXOSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UTXOSet) ProtoMessage() {}

func (x *UTXOSet) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blockchain_utxo_utxo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UTXOSet.ProtoReflect.Descriptor instead.
func (*UTXOSet) Descriptor() ([]byte, []int) {
	return file_pb_blockchain_utxo_utxo_proto_rawDescGZIP(), []int{4}
}

func (x *UTXOSet) GetMerkleRoot() []byte {
	if x != nil {
		return x.MerkleRoot
	}
	return nil
}

func (x *UTXOSet) GetLastUpdateHeight() uint64 {
	if x != nil {
		return x.LastUpdateHeight
	}
	return 0
}

var File_pb_blockchain_utxo_utxo_proto protoreflect.FileDescriptor

const file_pb_blockchain_utxo_utxo_proto_rawDesc = "" +
	"\n" +
	"\x1dpb/blockchain/utxo/utxo.proto\x12\x12pb.blockchain.utxo\x1a1pb/blockchain/block/transaction/transaction.proto\"\xe7\x05\n" +
	"\x04UTXO\x128\n" +
	"\boutpoint\x18\x01 \x01(\v2\x1c.pb.blockchain.core.OutPointR\boutpoint\x12<\n" +
	"\bcategory\x18\x02 \x01(\x0e2 .pb.blockchain.utxo.UTXOCategoryR\bcategory\x12#\n" +
	"\rowner_address\x18\x03 \x01(\fR\fownerAddress\x12!\n" +
	"\fblock_height\x18\x04 \x01(\x04R\vblockHeight\x12+\n" +
	"\x11created_timestamp\x18\x05 \x01(\x04R\x10createdTimestamp\x12?\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2'.pb.blockchain.utxo.UTXOLifecycleStatusR\x06status\x12W\n" +
	"\x11asset_constraints\x18\v \x01(\v2(.pb.blockchain.utxo.AssetUTXOConstraintsH\x00R\x10assetConstraints\x12`\n" +
	"\x14resource_constraints\x18\f \x01(\v2+.pb.blockchain.utxo.ResourceUTXOConstraintsH\x00R\x13resourceConstraints\x12W\n" +
	"\x11state_constraints\x18\r \x01(\v2(.pb.blockchain.utxo.StateUTXOConstraintsH\x00R\x10stateConstraints\x12C\n" +
	"\rcached_output\x18\x14 \x01(\v2\x1c.pb.blockchain.core.TxOutputH\x01R\fcachedOutput\x12'\n" +
	"\x0ereference_only\x18\x15 \x01(\bH\x01R\rreferenceOnlyB\x1b\n" +
	"\x19type_specific_constraintsB\x12\n" +
	"\x10content_strategy\"\x16\n" +
	"\x14AssetUTXOConstraints\"\xf4\x01\n" +
	"\x17ResourceUTXOConstraints\x12'\n" +
	"\x0freference_count\x18\x01 \x01(\x04R\x0ereferenceCount\x12?\n" +
	"\x19max_concurrent_references\x18\x02 \x01(\x04H\x00R\x17maxConcurrentReferences\x88\x01\x01\x127\n" +
	"\x15total_reference_count\x18\x03 \x01(\x04H\x01R\x13totalReferenceCount\x88\x01\x01B\x1c\n" +
	"\x1a_max_concurrent_referencesB\x18\n" +
	"\x16_total_reference_count\"\xe1\x01\n" +
	"\x14StateUTXOConstraints\x12$\n" +
	"\vttl_seconds\x18\x01 \x01(\x04H\x00R\n" +
	"ttlSeconds\x88\x01\x01\x125\n" +
	"\x14expires_at_timestamp\x18\x02 \x01(\x04H\x01R\x12expiresAtTimestamp\x88\x01\x01\x12.\n" +
	"\x10retention_policy\x18\x03 \x01(\rH\x02R\x0fretentionPolicy\x88\x01\x01B\x0e\n" +
	"\f_ttl_secondsB\x17\n" +
	"\x15_expires_at_timestampB\x13\n" +
	"\x11_retention_policy\"X\n" +
	"\aUTXOSet\x12\x1f\n" +
	"\vmerkle_root\x18\x01 \x01(\fR\n" +
	"merkleRoot\x12,\n" +
	"\x12last_update_height\x18\x02 \x01(\x04R\x10lastUpdateHeight*w\n" +
	"\fUTXOCategory\x12\x19\n" +
	"\x15UTXO_CATEGORY_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13UTXO_CATEGORY_ASSET\x10\x01\x12\x1a\n" +
	"\x16UTXO_CATEGORY_RESOURCE\x10\x02\x12\x17\n" +
	"\x13UTXO_CATEGORY_STATE\x10\x03*\xa7\x01\n" +
	"\x13UTXOLifecycleStatus\x12\x1a\n" +
	"\x16UTXO_LIFECYCLE_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18UTXO_LIFECYCLE_AVAILABLE\x10\x01\x12\x1d\n" +
	"\x19UTXO_LIFECYCLE_REFERENCED\x10\x02\x12\x1b\n" +
	"\x17UTXO_LIFECYCLE_CONSUMED\x10\x03\x12\x1a\n" +
	"\x16UTXO_LIFECYCLE_EXPIRED\x10\x04B)Z'github.com/weisyn/v1/pb/blockchain/utxob\x06proto3"

var (
	file_pb_blockchain_utxo_utxo_proto_rawDescOnce sync.Once
	file_pb_blockchain_utxo_utxo_proto_rawDescData []byte
)

func file_pb_blockchain_utxo_utxo_proto_rawDescGZIP() []byte {
	file_pb_blockchain_utxo_utxo_proto_rawDescOnce.Do(func() {
		file_pb_blockchain_utxo_utxo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_blockchain_utxo_utxo_proto_rawDesc), len(file_pb_blockchain_utxo_utxo_proto_rawDesc)))
	})
	return file_pb_blockchain_utxo_utxo_proto_rawDescData
}

var file_pb_blockchain_utxo_utxo_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pb_blockchain_utxo_utxo_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pb_blockchain_utxo_utxo_proto_goTypes = []any{
	(UTXOCategory)(0),               // 0: pb.blockchain.utxo.UTXOCategory
	(UTXOLifecycleStatus)(0),        // 1: pb.blockchain.utxo.UTXOLifecycleStatus
	(*UTXO)(nil),                    // 2: pb.blockchain.utxo.UTXO
	(*AssetUTXOConstraints)(nil),    // 3: pb.blockchain.utxo.AssetUTXOConstraints
	(*ResourceUTXOConstraints)(nil), // 4: pb.blockchain.utxo.ResourceUTXOConstraints
	(*StateUTXOConstraints)(nil),    // 5: pb.blockchain.utxo.StateUTXOConstraints
	(*UTXOSet)(nil),                 // 6: pb.blockchain.utxo.UTXOSet
	(*transaction.OutPoint)(nil),    // 7: pb.blockchain.core.OutPoint
	(*transaction.TxOutput)(nil),    // 8: pb.blockchain.core.TxOutput
}
var file_pb_blockchain_utxo_utxo_proto_depIdxs = []int32{
	7, // 0: pb.blockchain.utxo.UTXO.outpoint:type_name -> pb.blockchain.core.OutPoint
	0, // 1: pb.blockchain.utxo.UTXO.category:type_name -> pb.blockchain.utxo.UTXOCategory
	1, // 2: pb.blockchain.utxo.UTXO.status:type_name -> pb.blockchain.utxo.UTXOLifecycleStatus
	3, // 3: pb.blockchain.utxo.UTXO.asset_constraints:type_name -> pb.blockchain.utxo.AssetUTXOConstraints
	4, // 4: pb.blockchain.utxo.UTXO.resource_constraints:type_name -> pb.blockchain.utxo.ResourceUTXOConstraints
	5, // 5: pb.blockchain.utxo.UTXO.state_constraints:type_name -> pb.blockchain.utxo.StateUTXOConstraints
	8, // 6: pb.blockchain.utxo.UTXO.cached_output:type_name -> pb.blockchain.core.TxOutput
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_pb_blockchain_utxo_utxo_proto_init() }
func file_pb_blockchain_utxo_utxo_proto_init() {
	if File_pb_blockchain_utxo_utxo_proto != nil {
		return
	}
	file_pb_blockchain_utxo_utxo_proto_msgTypes[0].OneofWrappers = []any{
		(*UTXO_AssetConstraints)(nil),
		(*UTXO_ResourceConstraints)(nil),
		(*UTXO_StateConstraints)(nil),
		(*UTXO_CachedOutput)(nil),
		(*UTXO_ReferenceOnly)(nil),
	}
	file_pb_blockchain_utxo_utxo_proto_msgTypes[2].OneofWrappers = []any{}
	file_pb_blockchain_utxo_utxo_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_blockchain_utxo_utxo_proto_rawDesc), len(file_pb_blockchain_utxo_utxo_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_blockchain_utxo_utxo_proto_goTypes,
		DependencyIndexes: file_pb_blockchain_utxo_utxo_proto_depIdxs,
		EnumInfos:         file_pb_blockchain_utxo_utxo_proto_enumTypes,
		MessageInfos:      file_pb_blockchain_utxo_utxo_proto_msgTypes,
	}.Build()
	File_pb_blockchain_utxo_utxo_proto = out.File
	file_pb_blockchain_utxo_utxo_proto_goTypes = nil
	file_pb_blockchain_utxo_utxo_proto_depIdxs = nil
}
