// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: pb/blockchain/block/transaction/resource/resource.proto

package resource

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// ResourceCategory - 顶层资源分类（严格符合顶层设计）
//
// 🎯 设计原则：可执行资源和静态资源平级
type ResourceCategory int32

const (
	ResourceCategory_RESOURCE_CATEGORY_UNKNOWN    ResourceCategory = 0
	ResourceCategory_RESOURCE_CATEGORY_EXECUTABLE ResourceCategory = 1 // 可执行资源（能力载体）
	ResourceCategory_RESOURCE_CATEGORY_STATIC     ResourceCategory = 2 // 静态资源（价值载体）
)

// Enum value maps for ResourceCategory.
var (
	ResourceCategory_name = map[int32]string{
		0: "RESOURCE_CATEGORY_UNKNOWN",
		1: "RESOURCE_CATEGORY_EXECUTABLE",
		2: "RESOURCE_CATEGORY_STATIC",
	}
	ResourceCategory_value = map[string]int32{
		"RESOURCE_CATEGORY_UNKNOWN":    0,
		"RESOURCE_CATEGORY_EXECUTABLE": 1,
		"RESOURCE_CATEGORY_STATIC":     2,
	}
)

func (x ResourceCategory) Enum() *ResourceCategory {
	p := new(ResourceCategory)
	*p = x
	return p
}

func (x ResourceCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_blockchain_block_transaction_resource_resource_proto_enumTypes[0].Descriptor()
}

func (ResourceCategory) Type() protoreflect.EnumType {
	return &file_pb_blockchain_block_transaction_resource_resource_proto_enumTypes[0]
}

func (x ResourceCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceCategory.Descriptor instead.
func (ResourceCategory) EnumDescriptor() ([]byte, []int) {
	return file_pb_blockchain_block_transaction_resource_resource_proto_rawDescGZIP(), []int{0}
}

// *
// ExecutableType - 可执行资源子类型（基于执行引擎）
//
// 🎯 设计原则：基于internal/core/engines中实际提供的执行引擎
type ExecutableType int32

const (
	ExecutableType_EXECUTABLE_TYPE_UNKNOWN  ExecutableType = 0
	ExecutableType_EXECUTABLE_TYPE_CONTRACT ExecutableType = 1 // 智能合约（contract engine）
	ExecutableType_EXECUTABLE_TYPE_AIMODEL  ExecutableType = 2 // AI模型（aimodel engine）
)

// Enum value maps for ExecutableType.
var (
	ExecutableType_name = map[int32]string{
		0: "EXECUTABLE_TYPE_UNKNOWN",
		1: "EXECUTABLE_TYPE_CONTRACT",
		2: "EXECUTABLE_TYPE_AIMODEL",
	}
	ExecutableType_value = map[string]int32{
		"EXECUTABLE_TYPE_UNKNOWN":  0,
		"EXECUTABLE_TYPE_CONTRACT": 1,
		"EXECUTABLE_TYPE_AIMODEL":  2,
	}
)

func (x ExecutableType) Enum() *ExecutableType {
	p := new(ExecutableType)
	*p = x
	return p
}

func (x ExecutableType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutableType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_blockchain_block_transaction_resource_resource_proto_enumTypes[1].Descriptor()
}

func (ExecutableType) Type() protoreflect.EnumType {
	return &file_pb_blockchain_block_transaction_resource_resource_proto_enumTypes[1]
}

func (x ExecutableType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutableType.Descriptor instead.
func (ExecutableType) EnumDescriptor() ([]byte, []int) {
	return file_pb_blockchain_block_transaction_resource_resource_proto_rawDescGZIP(), []int{1}
}

// *
// Resource - 纯内容载体定义（权利与内容严格分离）
//
// 🎯 在TX架构中的位置：
// ```
// Transaction (权限验证 + 状态转换)
//
//	↓
//
// TxOutput (创建新UTXO)
//
//	├─ AssetOutput    (💰 价值载体：Token/NFT/SFT)
//	├─ ResourceOutput (⚙️ 能力载体：Contract/Model/File) ← Resource定义在此
//	└─ StateOutput    (📊 证据载体：Execution/Snapshot)
//
// ```
//
// ⚠️ 设计边界（核心原则）：
// ✅ Resource【仅】定义内容（是什么）
// ✅ Transaction【负责】权限（如何使用）
// ✅ ResourceOutput 与 Asset/State **完全平等**
// ❌ Resource【绝不】定义权利属性
//
// 🔒 权限验证要点（必须理解）：
// 1. **资源创建需要TX权限验证**：
//   - 创建ResourceOutput必须通过Transaction
//   - 需要消费输入UTXO支付费用
//   - 需要提供UnlockingProof证明有权支付费用
//
// 2. **资源引用需要TX权限验证**：
//   - TxInput.is_reference_only = true
//   - UnlockingProof 必须匹配 ResourceOutput的LockingCondition
//   - 引用成功后UTXO保持在集合中
//
// 3. **资源消费需要TX权限验证**：
//   - TxInput.is_reference_only = false
//   - UnlockingProof 必须匹配 ResourceOutput的LockingCondition
//   - 消费成功后UTXO从集合中移除
//
// 🏗️ 层级设计（严格符合统一权利载体理论）：
// • 顶层分类：可执行资源 vs 静态资源（基于内容特征，非权利特征）
// • 可执行资源子类型：基于执行引擎（CONTRACT, AIMODEL等）
// • 静态资源：无子类型，由mime_type区分业务语义
// • 【重要】：分类基于内容能力，不基于权利性质！
//
// 📋 完整的资源生命周期（由Transaction层控制）：
// ```
// 创建：N inputs (费用) + ResourceOutput
//
//	→ 需要证明有权支付费用
//
// 引用：TxInput(is_reference_only=true) + 其他outputs
//
//	→ 需要证明有权引用资源
//	→ UTXO保持在集合中
//
// 消费：TxInput(is_reference_only=false) + 新ResourceOutput
//
//	→ 需要证明有权消费资源
//	→ UTXO从集合中移除（转移/升级）
//
// ```
//
// 🛡️ 验证约束（纯内容层面）：
// • content_hash: 必须是32字节SHA-256哈希
// • category与executable_type必须匹配（当且仅当 category=EXECUTABLE 时 executable_type 有效）
// • 不包含权利验证 - 这是Transaction层的职责！
//
// 💡 理论映射：
// - Resource = 统一权利载体理论中的"内容载体"部分
// - 权利属性由Transaction层的EUTXO结构承载（LockingCondition/UnlockingProof）
// - 这种分离实现了完美的"内容"与"权利"解耦
//
// 🎯 TX本质在资源场景的体现：
// **TX = 证明有权使用某些UTXO（输入权限） + 定义如何创建新UTXO（输出定义）**
// - 创建资源：证明有权支付 → 创建ResourceOutput
// - 引用资源：证明有权引用 → 保持ResourceOutput
// - 消费资源：证明有权消费 → 移除旧ResourceOutput + 创建新ResourceOutput
type Resource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ========== 资源核心身份（内容载体部分）==========
	Category       ResourceCategory `protobuf:"varint,1,opt,name=category,proto3,enum=pb.blockchain.resource.ResourceCategory" json:"category,omitempty"`                                 // 顶层分类：可执行 vs 静态
	ExecutableType ExecutableType   `protobuf:"varint,2,opt,name=executable_type,json=executableType,proto3,enum=pb.blockchain.resource.ExecutableType" json:"executable_type,omitempty"` // 可执行资源子类型（仅当category=EXECUTABLE时有效）
	ContentHash    []byte           `protobuf:"bytes,3,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`                                                      // 内容SHA-256哈希（唯一身份标识）
	MimeType       string           `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`                                                               // 内容媒体类型（业务层语义）
	Size           uint64           `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`                                                                                      // 内容大小（字节）
	// ========== 资源元信息 ==========
	Name             string `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`                                                  // 资源显示名称（用户友好，可自定义）
	Version          string `protobuf:"bytes,11,opt,name=version,proto3" json:"version,omitempty"`                                            // 版本标识
	CreatedTimestamp uint64 `protobuf:"varint,12,opt,name=created_timestamp,json=createdTimestamp,proto3" json:"created_timestamp,omitempty"` // 创建时间戳
	CreatorAddress   string `protobuf:"bytes,13,opt,name=creator_address,json=creatorAddress,proto3" json:"creator_address,omitempty"`        // 创建者地址
	Description      string `protobuf:"bytes,14,opt,name=description,proto3" json:"description,omitempty"`                                    // 资源描述
	OriginalFilename string `protobuf:"bytes,15,opt,name=original_filename,json=originalFilename,proto3" json:"original_filename,omitempty"`  // 原始文件名（含扩展名，如 "协会简介中英双语.pdf"）
	FileExtension    string `protobuf:"bytes,16,opt,name=file_extension,json=fileExtension,proto3" json:"file_extension,omitempty"`           // 文件扩展名（如 ".pdf", ".wasm", ".onnx"）
	// ========== 执行引擎配置（仅可执行资源需要）==========
	//
	// Types that are valid to be assigned to ExecutionConfig:
	//
	//	*Resource_Contract
	//	*Resource_Aimodel
	ExecutionConfig isResource_ExecutionConfig `protobuf_oneof:"execution_config"`
	// ========== 用户自定义属性（业务层扩展）==========
	CustomAttributes map[string]string `protobuf:"bytes,30,rep,name=custom_attributes,json=customAttributes,proto3" json:"custom_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 业务层自定义属性
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_pb_blockchain_block_transaction_resource_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blockchain_block_transaction_resource_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_pb_blockchain_block_transaction_resource_resource_proto_rawDescGZIP(), []int{0}
}

func (x *Resource) GetCategory() ResourceCategory {
	if x != nil {
		return x.Category
	}
	return ResourceCategory_RESOURCE_CATEGORY_UNKNOWN
}

func (x *Resource) GetExecutableType() ExecutableType {
	if x != nil {
		return x.ExecutableType
	}
	return ExecutableType_EXECUTABLE_TYPE_UNKNOWN
}

func (x *Resource) GetContentHash() []byte {
	if x != nil {
		return x.ContentHash
	}
	return nil
}

func (x *Resource) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Resource) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Resource) GetCreatedTimestamp() uint64 {
	if x != nil {
		return x.CreatedTimestamp
	}
	return 0
}

func (x *Resource) GetCreatorAddress() string {
	if x != nil {
		return x.CreatorAddress
	}
	return ""
}

func (x *Resource) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Resource) GetOriginalFilename() string {
	if x != nil {
		return x.OriginalFilename
	}
	return ""
}

func (x *Resource) GetFileExtension() string {
	if x != nil {
		return x.FileExtension
	}
	return ""
}

func (x *Resource) GetExecutionConfig() isResource_ExecutionConfig {
	if x != nil {
		return x.ExecutionConfig
	}
	return nil
}

func (x *Resource) GetContract() *ContractExecutionConfig {
	if x != nil {
		if x, ok := x.ExecutionConfig.(*Resource_Contract); ok {
			return x.Contract
		}
	}
	return nil
}

func (x *Resource) GetAimodel() *AIModelExecutionConfig {
	if x != nil {
		if x, ok := x.ExecutionConfig.(*Resource_Aimodel); ok {
			return x.Aimodel
		}
	}
	return nil
}

func (x *Resource) GetCustomAttributes() map[string]string {
	if x != nil {
		return x.CustomAttributes
	}
	return nil
}

type isResource_ExecutionConfig interface {
	isResource_ExecutionConfig()
}

type Resource_Contract struct {
	Contract *ContractExecutionConfig `protobuf:"bytes,100,opt,name=contract,proto3,oneof"` // 智能合约执行配置
}

type Resource_Aimodel struct {
	Aimodel *AIModelExecutionConfig `protobuf:"bytes,101,opt,name=aimodel,proto3,oneof"` // AI模型执行配置
}

func (*Resource_Contract) isResource_ExecutionConfig() {}

func (*Resource_Aimodel) isResource_ExecutionConfig() {}

// *
// ContractExecutionConfig - 智能合约执行配置（对应contract engine）
//
// 🎯 设计原则：只包含执行引擎所需的核心配置
//
// ⚠️ 当前状态：定义已完成，execution层集成进行中
// - 该配置会在 internal/core/engines/wasm 中被使用
// - 目前业务代码还在适配新的ResourceOutput架构
// - 这是预设计的执行引擎配置接口，确保后续集成的一致性
type ContractExecutionConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AbiVersion        string                 `protobuf:"bytes,1,opt,name=abi_version,json=abiVersion,proto3" json:"abi_version,omitempty"`                                                                                           // ABI版本
	ExportedFunctions []string               `protobuf:"bytes,2,rep,name=exported_functions,json=exportedFunctions,proto3" json:"exported_functions,omitempty"`                                                                      // 导出函数列表
	ExecutionParams   map[string]string      `protobuf:"bytes,10,rep,name=execution_params,json=executionParams,proto3" json:"execution_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 执行参数（引擎特定）
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ContractExecutionConfig) Reset() {
	*x = ContractExecutionConfig{}
	mi := &file_pb_blockchain_block_transaction_resource_resource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractExecutionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractExecutionConfig) ProtoMessage() {}

func (x *ContractExecutionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blockchain_block_transaction_resource_resource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractExecutionConfig.ProtoReflect.Descriptor instead.
func (*ContractExecutionConfig) Descriptor() ([]byte, []int) {
	return file_pb_blockchain_block_transaction_resource_resource_proto_rawDescGZIP(), []int{1}
}

func (x *ContractExecutionConfig) GetAbiVersion() string {
	if x != nil {
		return x.AbiVersion
	}
	return ""
}

func (x *ContractExecutionConfig) GetExportedFunctions() []string {
	if x != nil {
		return x.ExportedFunctions
	}
	return nil
}

func (x *ContractExecutionConfig) GetExecutionParams() map[string]string {
	if x != nil {
		return x.ExecutionParams
	}
	return nil
}

// *
// AIModelExecutionConfig - AI模型执行配置（对应aimodel engine）
//
// 🎯 设计原则：只包含执行引擎所需的核心配置
//
// ⚠️ 当前状态：定义已完成，execution层集成进行中
// - 该配置会在 internal/core/engines/aimodel 中被使用
// - 目前业务代码还在适配新的ResourceOutput架构
// - 这是预设计的执行引擎配置接口，确保ONNX等模型的标准化执行
type AIModelExecutionConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ModelFormat     string                 `protobuf:"bytes,1,opt,name=model_format,json=modelFormat,proto3" json:"model_format,omitempty"`                                                                                        // 模型格式（ONNX, TensorFlow等）
	InputNames      []string               `protobuf:"bytes,2,rep,name=input_names,json=inputNames,proto3" json:"input_names,omitempty"`                                                                                           // 输入张量名称
	OutputNames     []string               `protobuf:"bytes,3,rep,name=output_names,json=outputNames,proto3" json:"output_names,omitempty"`                                                                                        // 输出张量名称
	ExecutionParams map[string]string      `protobuf:"bytes,10,rep,name=execution_params,json=executionParams,proto3" json:"execution_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 执行参数（引擎特定）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AIModelExecutionConfig) Reset() {
	*x = AIModelExecutionConfig{}
	mi := &file_pb_blockchain_block_transaction_resource_resource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIModelExecutionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIModelExecutionConfig) ProtoMessage() {}

func (x *AIModelExecutionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blockchain_block_transaction_resource_resource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIModelExecutionConfig.ProtoReflect.Descriptor instead.
func (*AIModelExecutionConfig) Descriptor() ([]byte, []int) {
	return file_pb_blockchain_block_transaction_resource_resource_proto_rawDescGZIP(), []int{2}
}

func (x *AIModelExecutionConfig) GetModelFormat() string {
	if x != nil {
		return x.ModelFormat
	}
	return ""
}

func (x *AIModelExecutionConfig) GetInputNames() []string {
	if x != nil {
		return x.InputNames
	}
	return nil
}

func (x *AIModelExecutionConfig) GetOutputNames() []string {
	if x != nil {
		return x.OutputNames
	}
	return nil
}

func (x *AIModelExecutionConfig) GetExecutionParams() map[string]string {
	if x != nil {
		return x.ExecutionParams
	}
	return nil
}

var File_pb_blockchain_block_transaction_resource_resource_proto protoreflect.FileDescriptor

const file_pb_blockchain_block_transaction_resource_resource_proto_rawDesc = "" +
	"\n" +
	"7pb/blockchain/block/transaction/resource/resource.proto\x12\x16pb.blockchain.resource\"\xc8\x06\n" +
	"\bResource\x12D\n" +
	"\bcategory\x18\x01 \x01(\x0e2(.pb.blockchain.resource.ResourceCategoryR\bcategory\x12O\n" +
	"\x0fexecutable_type\x18\x02 \x01(\x0e2&.pb.blockchain.resource.ExecutableTypeR\x0eexecutableType\x12!\n" +
	"\fcontent_hash\x18\x03 \x01(\fR\vcontentHash\x12\x1b\n" +
	"\tmime_type\x18\x04 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x04R\x04size\x12\x12\n" +
	"\x04name\x18\n" +
	" \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\v \x01(\tR\aversion\x12+\n" +
	"\x11created_timestamp\x18\f \x01(\x04R\x10createdTimestamp\x12'\n" +
	"\x0fcreator_address\x18\r \x01(\tR\x0ecreatorAddress\x12 \n" +
	"\vdescription\x18\x0e \x01(\tR\vdescription\x12+\n" +
	"\x11original_filename\x18\x0f \x01(\tR\x10originalFilename\x12%\n" +
	"\x0efile_extension\x18\x10 \x01(\tR\rfileExtension\x12M\n" +
	"\bcontract\x18d \x01(\v2/.pb.blockchain.resource.ContractExecutionConfigH\x00R\bcontract\x12J\n" +
	"\aaimodel\x18e \x01(\v2..pb.blockchain.resource.AIModelExecutionConfigH\x00R\aaimodel\x12c\n" +
	"\x11custom_attributes\x18\x1e \x03(\v26.pb.blockchain.resource.Resource.CustomAttributesEntryR\x10customAttributes\x1aC\n" +
	"\x15CustomAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x12\n" +
	"\x10execution_config\"\x9e\x02\n" +
	"\x17ContractExecutionConfig\x12\x1f\n" +
	"\vabi_version\x18\x01 \x01(\tR\n" +
	"abiVersion\x12-\n" +
	"\x12exported_functions\x18\x02 \x03(\tR\x11exportedFunctions\x12o\n" +
	"\x10execution_params\x18\n" +
	" \x03(\v2D.pb.blockchain.resource.ContractExecutionConfig.ExecutionParamsEntryR\x0fexecutionParams\x1aB\n" +
	"\x14ExecutionParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb3\x02\n" +
	"\x16AIModelExecutionConfig\x12!\n" +
	"\fmodel_format\x18\x01 \x01(\tR\vmodelFormat\x12\x1f\n" +
	"\vinput_names\x18\x02 \x03(\tR\n" +
	"inputNames\x12!\n" +
	"\foutput_names\x18\x03 \x03(\tR\voutputNames\x12n\n" +
	"\x10execution_params\x18\n" +
	" \x03(\v2C.pb.blockchain.resource.AIModelExecutionConfig.ExecutionParamsEntryR\x0fexecutionParams\x1aB\n" +
	"\x14ExecutionParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*q\n" +
	"\x10ResourceCategory\x12\x1d\n" +
	"\x19RESOURCE_CATEGORY_UNKNOWN\x10\x00\x12 \n" +
	"\x1cRESOURCE_CATEGORY_EXECUTABLE\x10\x01\x12\x1c\n" +
	"\x18RESOURCE_CATEGORY_STATIC\x10\x02*o\n" +
	"\x0eExecutableType\x12\x1b\n" +
	"\x17EXECUTABLE_TYPE_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18EXECUTABLE_TYPE_CONTRACT\x10\x01\x12\x1b\n" +
	"\x17EXECUTABLE_TYPE_AIMODEL\x10\x02\"\x05\b\x03\x10\xe7\aB?Z=github.com/weisyn/v1/pb/blockchain/block/transaction/resourceb\x06proto3"

var (
	file_pb_blockchain_block_transaction_resource_resource_proto_rawDescOnce sync.Once
	file_pb_blockchain_block_transaction_resource_resource_proto_rawDescData []byte
)

func file_pb_blockchain_block_transaction_resource_resource_proto_rawDescGZIP() []byte {
	file_pb_blockchain_block_transaction_resource_resource_proto_rawDescOnce.Do(func() {
		file_pb_blockchain_block_transaction_resource_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_blockchain_block_transaction_resource_resource_proto_rawDesc), len(file_pb_blockchain_block_transaction_resource_resource_proto_rawDesc)))
	})
	return file_pb_blockchain_block_transaction_resource_resource_proto_rawDescData
}

var file_pb_blockchain_block_transaction_resource_resource_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pb_blockchain_block_transaction_resource_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pb_blockchain_block_transaction_resource_resource_proto_goTypes = []any{
	(ResourceCategory)(0),           // 0: pb.blockchain.resource.ResourceCategory
	(ExecutableType)(0),             // 1: pb.blockchain.resource.ExecutableType
	(*Resource)(nil),                // 2: pb.blockchain.resource.Resource
	(*ContractExecutionConfig)(nil), // 3: pb.blockchain.resource.ContractExecutionConfig
	(*AIModelExecutionConfig)(nil),  // 4: pb.blockchain.resource.AIModelExecutionConfig
	nil,                             // 5: pb.blockchain.resource.Resource.CustomAttributesEntry
	nil,                             // 6: pb.blockchain.resource.ContractExecutionConfig.ExecutionParamsEntry
	nil,                             // 7: pb.blockchain.resource.AIModelExecutionConfig.ExecutionParamsEntry
}
var file_pb_blockchain_block_transaction_resource_resource_proto_depIdxs = []int32{
	0, // 0: pb.blockchain.resource.Resource.category:type_name -> pb.blockchain.resource.ResourceCategory
	1, // 1: pb.blockchain.resource.Resource.executable_type:type_name -> pb.blockchain.resource.ExecutableType
	3, // 2: pb.blockchain.resource.Resource.contract:type_name -> pb.blockchain.resource.ContractExecutionConfig
	4, // 3: pb.blockchain.resource.Resource.aimodel:type_name -> pb.blockchain.resource.AIModelExecutionConfig
	5, // 4: pb.blockchain.resource.Resource.custom_attributes:type_name -> pb.blockchain.resource.Resource.CustomAttributesEntry
	6, // 5: pb.blockchain.resource.ContractExecutionConfig.execution_params:type_name -> pb.blockchain.resource.ContractExecutionConfig.ExecutionParamsEntry
	7, // 6: pb.blockchain.resource.AIModelExecutionConfig.execution_params:type_name -> pb.blockchain.resource.AIModelExecutionConfig.ExecutionParamsEntry
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_pb_blockchain_block_transaction_resource_resource_proto_init() }
func file_pb_blockchain_block_transaction_resource_resource_proto_init() {
	if File_pb_blockchain_block_transaction_resource_resource_proto != nil {
		return
	}
	file_pb_blockchain_block_transaction_resource_resource_proto_msgTypes[0].OneofWrappers = []any{
		(*Resource_Contract)(nil),
		(*Resource_Aimodel)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_blockchain_block_transaction_resource_resource_proto_rawDesc), len(file_pb_blockchain_block_transaction_resource_resource_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_blockchain_block_transaction_resource_resource_proto_goTypes,
		DependencyIndexes: file_pb_blockchain_block_transaction_resource_resource_proto_depIdxs,
		EnumInfos:         file_pb_blockchain_block_transaction_resource_resource_proto_enumTypes,
		MessageInfos:      file_pb_blockchain_block_transaction_resource_resource_proto_msgTypes,
	}.Build()
	File_pb_blockchain_block_transaction_resource_resource_proto = out.File
	file_pb_blockchain_block_transaction_resource_resource_proto_goTypes = nil
	file_pb_blockchain_block_transaction_resource_resource_proto_depIdxs = nil
}
