// Package main 实现了一个用于生成键前缀映射的工具
// 基于defs-back/kbucket/generate/main.go的实现
package main

import (
	"crypto/sha256"
	"encoding/binary"
	"fmt"
	"os"
	"strings"
)

// 常量定义
const (
	bits   = 16        // 每个前缀的位数
	target = 1 << bits // 目标值为2^16 = 65536
	idLen  = 32 + 2    // ID长度为32字节加2字节前缀
)

// main 函数生成一个包含键前缀映射的Go源文件
//
// 该函数执行以下步骤:
// 1. 从环境变量获取包名和文件名
// 2. 生成一个包含target个前缀值的映射数组
// 3. 将生成的映射写入到新的源文件中
//
// 生成的映射用于将哈希值快速映射到对应的索引位置
func main() {
	// 从环境变量获取包名和文件名
	pkg := os.Getenv("GOPACKAGE")
	if pkg == "" {
		pkg = "kbucket" // 默认包名
	}

	file := os.Getenv("GOFILE")
	if file == "" {
		file = "generate.go" // 默认文件名
	}

	targetFile := strings.TrimSuffix(file, ".go") + "_prefixmap.go"

	// 初始化数据结构
	ids := new([target]uint32) // 存储生成的前缀值
	found := new([target]bool) // 标记已找到的前缀值
	count := int32(0)          // 已找到的前缀值计数

	// 初始化哈希计算所需的缓冲区
	out := make([]byte, 32)      // 哈希输出缓冲区
	inp := [idLen]byte{0x12, 32} // 哈希输入缓冲区，预设SHA256标识符
	hasher := sha256.New()       // SHA256哈希计算器

	// 生成前缀映射
	for i := uint32(0); count < target; i++ {
		// 将当前计数器值写入输入缓冲区
		binary.BigEndian.PutUint32(inp[2:], i)

		// 计算哈希值
		hasher.Reset()
		hasher.Write(inp[:])
		copy(out, hasher.Sum(nil))

		// 提取前16位作为前缀
		prefix := binary.BigEndian.Uint16(out[:2])

		// 如果该前缀尚未找到，则记录
		if !found[prefix] {
			ids[prefix] = i
			found[prefix] = true
			count++
		}
	}

	// 生成输出文件
	// targetFile 是从环境变量或默认值生成的，路径安全可控
	//nolint:gosec // G304: 文件路径来自环境变量或默认值，安全可控
	f, err := os.Create(targetFile)
	if err != nil {
		panic(err)
	}
	defer func() {
		if err := f.Close(); err != nil {
			fmt.Printf("关闭文件失败: %v\n", err)
		}
	}()

	// 写入文件头
	if _, err := fmt.Fprintf(f, "// Code generated by go generate; DO NOT EDIT.\n"); err != nil {
		_ = f.Close()
		_ = os.Remove(targetFile)
		panic(fmt.Errorf("写入文件头失败: %w", err))
	}
	if _, err := fmt.Fprintf(f, "// This file was generated by robots at\n"); err != nil {
		_ = f.Close()
		_ = os.Remove(targetFile)
		panic(fmt.Errorf("写入文件头失败: %w", err))
	}
	if _, err := fmt.Fprintf(f, "// %s\n\n", "go generate"); err != nil {
		_ = f.Close()
		_ = os.Remove(targetFile)
		panic(fmt.Errorf("写入文件头失败: %w", err))
	}
	if _, err := fmt.Fprintf(f, "package %s\n\n", pkg); err != nil {
		_ = f.Close()
		_ = os.Remove(targetFile)
		panic(fmt.Errorf("写入包声明失败: %w", err))
	}

	// 写入数组声明
	if _, err := fmt.Fprintf(f, "// prefixMap is a lookup table for bucket prefixes.\n"); err != nil {
		_ = f.Close()
		_ = os.Remove(targetFile)
		panic(fmt.Errorf("写入注释失败: %w", err))
	}
	if _, err := fmt.Fprintf(f, "// It maps a 16-bit prefix to a 32-bit value that can be used\n"); err != nil {
		_ = f.Close()
		_ = os.Remove(targetFile)
		panic(fmt.Errorf("写入注释失败: %w", err))
	}
	if _, err := fmt.Fprintf(f, "// to generate peer IDs with that prefix.\n"); err != nil {
		_ = f.Close()
		_ = os.Remove(targetFile)
		panic(fmt.Errorf("写入注释失败: %w", err))
	}
	if _, err := fmt.Fprintf(f, "var prefixMap = [%d]uint32{\n", target); err != nil {
		_ = f.Close()
		_ = os.Remove(targetFile)
		panic(fmt.Errorf("写入数组声明失败: %w", err))
	}

	// 写入映射数据
	for i, id := range ids {
		if i%8 == 0 {
			if _, err := fmt.Fprintf(f, "\t"); err != nil {
				_ = f.Close()
				_ = os.Remove(targetFile)
				panic(fmt.Errorf("写入数据失败: %w", err))
			}
		}
		if _, err := fmt.Fprintf(f, "0x%08x", id); err != nil {
			_ = f.Close()
			_ = os.Remove(targetFile)
			panic(fmt.Errorf("写入数据失败: %w", err))
		}
		if i < target-1 {
			if _, err := fmt.Fprintf(f, ","); err != nil {
				_ = f.Close()
				_ = os.Remove(targetFile)
				panic(fmt.Errorf("写入数据失败: %w", err))
			}
		}
		if i%8 == 7 || i == target-1 {
			if _, err := fmt.Fprintf(f, "\n"); err != nil {
				_ = f.Close()
				_ = os.Remove(targetFile)
				panic(fmt.Errorf("写入数据失败: %w", err))
			}
		} else {
			if _, err := fmt.Fprintf(f, " "); err != nil {
				_ = f.Close()
				_ = os.Remove(targetFile)
				panic(fmt.Errorf("写入数据失败: %w", err))
			}
		}
	}

	if _, err := fmt.Fprintf(f, "}\n"); err != nil {
		_ = f.Close()
		_ = os.Remove(targetFile)
		panic(fmt.Errorf("写入结束标记失败: %w", err))
	}
	if _, err := fmt.Printf("Generated %s with %d prefixes\n", targetFile, target); err != nil {
		// 输出到标准输出失败，记录但不影响主流程
		_, _ = fmt.Fprintf(os.Stderr, "输出信息失败: %v\n", err)
	}
}
