// Package main 实现了一个用于生成键前缀映射的工具
// 基于defs-back/kbucket/generate/main.go的实现
package main

import (
	"crypto/sha256"
	"encoding/binary"
	"fmt"
	"os"
	"strings"
)

// 常量定义
const (
	bits   = 16        // 每个前缀的位数
	target = 1 << bits // 目标值为2^16 = 65536
	idLen  = 32 + 2    // ID长度为32字节加2字节前缀
)

// main 函数生成一个包含键前缀映射的Go源文件
//
// 该函数执行以下步骤:
// 1. 从环境变量获取包名和文件名
// 2. 生成一个包含target个前缀值的映射数组
// 3. 将生成的映射写入到新的源文件中
//
// 生成的映射用于将哈希值快速映射到对应的索引位置
func main() {
	// 从环境变量获取包名和文件名
	pkg := os.Getenv("GOPACKAGE")
	if pkg == "" {
		pkg = "kbucket" // 默认包名
	}

	file := os.Getenv("GOFILE")
	if file == "" {
		file = "generate.go" // 默认文件名
	}

	targetFile := strings.TrimSuffix(file, ".go") + "_prefixmap.go"

	// 初始化数据结构
	ids := new([target]uint32) // 存储生成的前缀值
	found := new([target]bool) // 标记已找到的前缀值
	count := int32(0)          // 已找到的前缀值计数

	// 初始化哈希计算所需的缓冲区
	out := make([]byte, 32)      // 哈希输出缓冲区
	inp := [idLen]byte{0x12, 32} // 哈希输入缓冲区，预设SHA256标识符
	hasher := sha256.New()       // SHA256哈希计算器

	// 生成前缀映射
	for i := uint32(0); count < target; i++ {
		// 将当前计数器值写入输入缓冲区
		binary.BigEndian.PutUint32(inp[2:], i)

		// 计算哈希值
		hasher.Reset()
		hasher.Write(inp[:])
		copy(out, hasher.Sum(nil))

		// 提取前16位作为前缀
		prefix := binary.BigEndian.Uint16(out[:2])

		// 如果该前缀尚未找到，则记录
		if !found[prefix] {
			ids[prefix] = i
			found[prefix] = true
			count++
		}
	}

	// 生成输出文件
	f, err := os.Create(targetFile)
	if err != nil {
		panic(err)
	}
	defer f.Close()

	// 写入文件头
	fmt.Fprintf(f, "// Code generated by go generate; DO NOT EDIT.\n")
	fmt.Fprintf(f, "// This file was generated by robots at\n")
	fmt.Fprintf(f, "// %s\n\n", "go generate")
	fmt.Fprintf(f, "package %s\n\n", pkg)

	// 写入数组声明
	fmt.Fprintf(f, "// prefixMap is a lookup table for bucket prefixes.\n")
	fmt.Fprintf(f, "// It maps a 16-bit prefix to a 32-bit value that can be used\n")
	fmt.Fprintf(f, "// to generate peer IDs with that prefix.\n")
	fmt.Fprintf(f, "var prefixMap = [%d]uint32{\n", target)

	// 写入映射数据
	for i, id := range ids {
		if i%8 == 0 {
			fmt.Fprintf(f, "\t")
		}
		fmt.Fprintf(f, "0x%08x", id)
		if i < target-1 {
			fmt.Fprintf(f, ",")
		}
		if i%8 == 7 || i == target-1 {
			fmt.Fprintf(f, "\n")
		} else {
			fmt.Fprintf(f, " ")
		}
	}

	fmt.Fprintf(f, "}\n")
	fmt.Printf("Generated %s with %d prefixes\n", targetFile, target)
}
