// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: pb/network/protocol/consensus.proto

package protocol

import (
	block "github.com/weisyn/v1/pb/blockchain/block"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AggregatorBlockAcceptance_WaiverReason int32

const (
	AggregatorBlockAcceptance_WAIVER_NONE                    AggregatorBlockAcceptance_WaiverReason = 0 // 未弃权（正常接受/拒绝）
	AggregatorBlockAcceptance_WAIVER_HEIGHT_TOO_FAR_AHEAD    AggregatorBlockAcceptance_WaiverReason = 1 // 高度领先过多（skew > maxFutureSkew）
	AggregatorBlockAcceptance_WAIVER_AGGREGATION_IN_PROGRESS AggregatorBlockAcceptance_WaiverReason = 2 // 本节点当前正忙于处理该高度/其他高度（本轮换人）
	AggregatorBlockAcceptance_WAIVER_READ_ONLY_MODE          AggregatorBlockAcceptance_WaiverReason = 3 // 节点处于只读模式（数据损坏或维护中）
)

// Enum value maps for AggregatorBlockAcceptance_WaiverReason.
var (
	AggregatorBlockAcceptance_WaiverReason_name = map[int32]string{
		0: "WAIVER_NONE",
		1: "WAIVER_HEIGHT_TOO_FAR_AHEAD",
		2: "WAIVER_AGGREGATION_IN_PROGRESS",
		3: "WAIVER_READ_ONLY_MODE",
	}
	AggregatorBlockAcceptance_WaiverReason_value = map[string]int32{
		"WAIVER_NONE":                    0,
		"WAIVER_HEIGHT_TOO_FAR_AHEAD":    1,
		"WAIVER_AGGREGATION_IN_PROGRESS": 2,
		"WAIVER_READ_ONLY_MODE":          3,
	}
)

func (x AggregatorBlockAcceptance_WaiverReason) Enum() *AggregatorBlockAcceptance_WaiverReason {
	p := new(AggregatorBlockAcceptance_WaiverReason)
	*p = x
	return p
}

func (x AggregatorBlockAcceptance_WaiverReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AggregatorBlockAcceptance_WaiverReason) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_network_protocol_consensus_proto_enumTypes[0].Descriptor()
}

func (AggregatorBlockAcceptance_WaiverReason) Type() protoreflect.EnumType {
	return &file_pb_network_protocol_consensus_proto_enumTypes[0]
}

func (x AggregatorBlockAcceptance_WaiverReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AggregatorBlockAcceptance_WaiverReason.Descriptor instead.
func (AggregatorBlockAcceptance_WaiverReason) EnumDescriptor() ([]byte, []int) {
	return file_pb_network_protocol_consensus_proto_rawDescGZIP(), []int{2, 0}
}

type ConsensusHeartbeat_NodeStatus int32

const (
	ConsensusHeartbeat_NODE_STATUS_UNKNOWN     ConsensusHeartbeat_NodeStatus = 0 // 未知状态
	ConsensusHeartbeat_NODE_STATUS_ACTIVE      ConsensusHeartbeat_NodeStatus = 1 // 活跃状态
	ConsensusHeartbeat_NODE_STATUS_SYNCING     ConsensusHeartbeat_NodeStatus = 2 // 同步中
	ConsensusHeartbeat_NODE_STATUS_MINING      ConsensusHeartbeat_NodeStatus = 3 // 挖矿中
	ConsensusHeartbeat_NODE_STATUS_AGGREGATING ConsensusHeartbeat_NodeStatus = 4 // 聚合中
	ConsensusHeartbeat_NODE_STATUS_OFFLINE     ConsensusHeartbeat_NodeStatus = 5 // 离线状态
)

// Enum value maps for ConsensusHeartbeat_NodeStatus.
var (
	ConsensusHeartbeat_NodeStatus_name = map[int32]string{
		0: "NODE_STATUS_UNKNOWN",
		1: "NODE_STATUS_ACTIVE",
		2: "NODE_STATUS_SYNCING",
		3: "NODE_STATUS_MINING",
		4: "NODE_STATUS_AGGREGATING",
		5: "NODE_STATUS_OFFLINE",
	}
	ConsensusHeartbeat_NodeStatus_value = map[string]int32{
		"NODE_STATUS_UNKNOWN":     0,
		"NODE_STATUS_ACTIVE":      1,
		"NODE_STATUS_SYNCING":     2,
		"NODE_STATUS_MINING":      3,
		"NODE_STATUS_AGGREGATING": 4,
		"NODE_STATUS_OFFLINE":     5,
	}
)

func (x ConsensusHeartbeat_NodeStatus) Enum() *ConsensusHeartbeat_NodeStatus {
	p := new(ConsensusHeartbeat_NodeStatus)
	*p = x
	return p
}

func (x ConsensusHeartbeat_NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsensusHeartbeat_NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_network_protocol_consensus_proto_enumTypes[1].Descriptor()
}

func (ConsensusHeartbeat_NodeStatus) Type() protoreflect.EnumType {
	return &file_pb_network_protocol_consensus_proto_enumTypes[1]
}

func (x ConsensusHeartbeat_NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsensusHeartbeat_NodeStatus.Descriptor instead.
func (ConsensusHeartbeat_NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_pb_network_protocol_consensus_proto_rawDescGZIP(), []int{5, 0}
}

type ConsensusError_ErrorCode int32

const (
	ConsensusError_ERROR_UNKNOWN              ConsensusError_ErrorCode = 0 // 未知错误
	ConsensusError_ERROR_INVALID_MESSAGE      ConsensusError_ErrorCode = 1 // 无效消息格式
	ConsensusError_ERROR_INVALID_BLOCK        ConsensusError_ErrorCode = 2 // 无效区块数据
	ConsensusError_ERROR_INVALID_SIGNATURE    ConsensusError_ErrorCode = 3 // 无效签名
	ConsensusError_ERROR_NETWORK_TIMEOUT      ConsensusError_ErrorCode = 4 // 网络超时
	ConsensusError_ERROR_CONSENSUS_FAILURE    ConsensusError_ErrorCode = 5 // 共识失败
	ConsensusError_ERROR_DUPLICATE_SUBMISSION ConsensusError_ErrorCode = 6 // 重复提交
)

// Enum value maps for ConsensusError_ErrorCode.
var (
	ConsensusError_ErrorCode_name = map[int32]string{
		0: "ERROR_UNKNOWN",
		1: "ERROR_INVALID_MESSAGE",
		2: "ERROR_INVALID_BLOCK",
		3: "ERROR_INVALID_SIGNATURE",
		4: "ERROR_NETWORK_TIMEOUT",
		5: "ERROR_CONSENSUS_FAILURE",
		6: "ERROR_DUPLICATE_SUBMISSION",
	}
	ConsensusError_ErrorCode_value = map[string]int32{
		"ERROR_UNKNOWN":              0,
		"ERROR_INVALID_MESSAGE":      1,
		"ERROR_INVALID_BLOCK":        2,
		"ERROR_INVALID_SIGNATURE":    3,
		"ERROR_NETWORK_TIMEOUT":      4,
		"ERROR_CONSENSUS_FAILURE":    5,
		"ERROR_DUPLICATE_SUBMISSION": 6,
	}
)

func (x ConsensusError_ErrorCode) Enum() *ConsensusError_ErrorCode {
	p := new(ConsensusError_ErrorCode)
	*p = x
	return p
}

func (x ConsensusError_ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsensusError_ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_network_protocol_consensus_proto_enumTypes[2].Descriptor()
}

func (ConsensusError_ErrorCode) Type() protoreflect.EnumType {
	return &file_pb_network_protocol_consensus_proto_enumTypes[2]
}

func (x ConsensusError_ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsensusError_ErrorCode.Descriptor instead.
func (ConsensusError_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_pb_network_protocol_consensus_proto_rawDescGZIP(), []int{6, 0}
}

type AggregatorStatusResponse_AggregatorState int32

const (
	AggregatorStatusResponse_AGGREGATOR_STATE_UNKNOWN        AggregatorStatusResponse_AggregatorState = 0
	AggregatorStatusResponse_AGGREGATOR_STATE_COLLECTING     AggregatorStatusResponse_AggregatorState = 1 // 正在收集候选
	AggregatorStatusResponse_AGGREGATOR_STATE_EVALUATING     AggregatorStatusResponse_AggregatorState = 2 // 正在评估/选举
	AggregatorStatusResponse_AGGREGATOR_STATE_DISTRIBUTING   AggregatorStatusResponse_AggregatorState = 3 // 正在分发结果
	AggregatorStatusResponse_AGGREGATOR_STATE_COMPLETED      AggregatorStatusResponse_AggregatorState = 4 // 已完成（final_block不为空）
	AggregatorStatusResponse_AGGREGATOR_STATE_NOT_AGGREGATOR AggregatorStatusResponse_AggregatorState = 5 // 本节点不是该高度的聚合器
)

// Enum value maps for AggregatorStatusResponse_AggregatorState.
var (
	AggregatorStatusResponse_AggregatorState_name = map[int32]string{
		0: "AGGREGATOR_STATE_UNKNOWN",
		1: "AGGREGATOR_STATE_COLLECTING",
		2: "AGGREGATOR_STATE_EVALUATING",
		3: "AGGREGATOR_STATE_DISTRIBUTING",
		4: "AGGREGATOR_STATE_COMPLETED",
		5: "AGGREGATOR_STATE_NOT_AGGREGATOR",
	}
	AggregatorStatusResponse_AggregatorState_value = map[string]int32{
		"AGGREGATOR_STATE_UNKNOWN":        0,
		"AGGREGATOR_STATE_COLLECTING":     1,
		"AGGREGATOR_STATE_EVALUATING":     2,
		"AGGREGATOR_STATE_DISTRIBUTING":   3,
		"AGGREGATOR_STATE_COMPLETED":      4,
		"AGGREGATOR_STATE_NOT_AGGREGATOR": 5,
	}
)

func (x AggregatorStatusResponse_AggregatorState) Enum() *AggregatorStatusResponse_AggregatorState {
	p := new(AggregatorStatusResponse_AggregatorState)
	*p = x
	return p
}

func (x AggregatorStatusResponse_AggregatorState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AggregatorStatusResponse_AggregatorState) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_network_protocol_consensus_proto_enumTypes[3].Descriptor()
}

func (AggregatorStatusResponse_AggregatorState) Type() protoreflect.EnumType {
	return &file_pb_network_protocol_consensus_proto_enumTypes[3]
}

func (x AggregatorStatusResponse_AggregatorState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AggregatorStatusResponse_AggregatorState.Descriptor instead.
func (AggregatorStatusResponse_AggregatorState) EnumDescriptor() ([]byte, []int) {
	return file_pb_network_protocol_consensus_proto_rawDescGZIP(), []int{8, 0}
}

type AggregatorStatusResponse_AggregatorStateReason int32

const (
	AggregatorStatusResponse_REASON_NONE                   AggregatorStatusResponse_AggregatorStateReason = 0
	AggregatorStatusResponse_REASON_WAITING_FOR_CANDIDATES AggregatorStatusResponse_AggregatorStateReason = 1 // 等待更多候选
	AggregatorStatusResponse_REASON_CALCULATING_DISTANCES  AggregatorStatusResponse_AggregatorStateReason = 2 // 正在计算距离
	AggregatorStatusResponse_REASON_BROADCASTING_RESULT    AggregatorStatusResponse_AggregatorStateReason = 3 // 正在广播结果
	AggregatorStatusResponse_REASON_ALREADY_COMPLETED      AggregatorStatusResponse_AggregatorStateReason = 4 // 已完成
	AggregatorStatusResponse_REASON_WRONG_AGGREGATOR       AggregatorStatusResponse_AggregatorStateReason = 5 // 查询了错误的聚合器
)

// Enum value maps for AggregatorStatusResponse_AggregatorStateReason.
var (
	AggregatorStatusResponse_AggregatorStateReason_name = map[int32]string{
		0: "REASON_NONE",
		1: "REASON_WAITING_FOR_CANDIDATES",
		2: "REASON_CALCULATING_DISTANCES",
		3: "REASON_BROADCASTING_RESULT",
		4: "REASON_ALREADY_COMPLETED",
		5: "REASON_WRONG_AGGREGATOR",
	}
	AggregatorStatusResponse_AggregatorStateReason_value = map[string]int32{
		"REASON_NONE":                   0,
		"REASON_WAITING_FOR_CANDIDATES": 1,
		"REASON_CALCULATING_DISTANCES":  2,
		"REASON_BROADCASTING_RESULT":    3,
		"REASON_ALREADY_COMPLETED":      4,
		"REASON_WRONG_AGGREGATOR":       5,
	}
)

func (x AggregatorStatusResponse_AggregatorStateReason) Enum() *AggregatorStatusResponse_AggregatorStateReason {
	p := new(AggregatorStatusResponse_AggregatorStateReason)
	*p = x
	return p
}

func (x AggregatorStatusResponse_AggregatorStateReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AggregatorStatusResponse_AggregatorStateReason) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_network_protocol_consensus_proto_enumTypes[4].Descriptor()
}

func (AggregatorStatusResponse_AggregatorStateReason) Type() protoreflect.EnumType {
	return &file_pb_network_protocol_consensus_proto_enumTypes[4]
}

func (x AggregatorStatusResponse_AggregatorStateReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AggregatorStatusResponse_AggregatorStateReason.Descriptor instead.
func (AggregatorStatusResponse_AggregatorStateReason) EnumDescriptor() ([]byte, []int) {
	return file_pb_network_protocol_consensus_proto_rawDescGZIP(), []int{8, 1}
}

// *
// BaseMessage - 通用消息基础结构
//
// 🎯 设计目的：为所有共识消息提供统一的基础字段
//
// 🔧 核心字段：
// - message_id：全局唯一消息标识符，用于去重和追踪
// - version：协议版本，支持协议演进和兼容性检查
// - sender_id：发送者节点ID，用于身份验证和路由
// - timestamp_unix：Unix时间戳，用于时序验证和TTL控制
// - signature：消息签名，防止篡改和伪造
//
// 💡 使用价值：
// - 统一性：所有共识消息都有一致的基础结构
// - 安全性：通过签名确保消息的完整性和真实性
// - 可追踪性：通过message_id实现端到端的消息追踪
// - 版本控制：支持协议的平滑升级和兼容性管理
type BaseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`              // 全局唯一消息标识符
	SenderId      []byte                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`                 // 发送者节点ID（peer.ID序列化）
	TimestampUnix int64                  `protobuf:"varint,3,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"` // 消息创建时间戳（Unix秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseMessage) Reset() {
	*x = BaseMessage{}
	mi := &file_pb_network_protocol_consensus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseMessage) ProtoMessage() {}

func (x *BaseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_consensus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseMessage.ProtoReflect.Descriptor instead.
func (*BaseMessage) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_consensus_proto_rawDescGZIP(), []int{0}
}

func (x *BaseMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *BaseMessage) GetSenderId() []byte {
	if x != nil {
		return x.SenderId
	}
	return nil
}

func (x *BaseMessage) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

// *
// MinerBlockSubmission - 矿工区块提交消息
//
// 🎯 设计目的：矿工向聚合器提交候选区块的标准消息格式
//
// ⛏️ 矿工工作流：
// 1. 候选创建：从交易池选择交易，创建候选区块模板
// 2. PoW计算：执行工作量证明，搜索有效的Nonce
// 3. 目标选择：基于K-bucket距离选择2个近邻聚合器
// 4. 并发提交：同时向选中的聚合器发送MinerBlockSubmission
// 5. 快速返回：任一聚合器接受即取消其他请求
//
// 🔄 V2 扩展（2025-12-15）：弃权与重选机制
// - waived_aggregators：已知弃权的聚合器节点ID列表（避免回环）
// - retry_attempt：重试次数（从0开始，每次重选+1）
// - original_miner_peer_id：原始矿工节点ID（用于回环检测）
type MinerBlockSubmission struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Base             *BaseMessage           `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`                                                  // 消息基础信息
	CandidateBlock   *block.Block           `protobuf:"bytes,2,opt,name=candidate_block,json=candidateBlock,proto3" json:"candidate_block,omitempty"`        // 候选区块（完整数据）
	MinerPeerId      []byte                 `protobuf:"bytes,3,opt,name=miner_peer_id,json=minerPeerId,proto3" json:"miner_peer_id,omitempty"`               // 矿工节点ID
	MiningDifficulty uint64                 `protobuf:"varint,4,opt,name=mining_difficulty,json=miningDifficulty,proto3" json:"mining_difficulty,omitempty"` // 挖矿难度值
	MiningTimeMs     uint64                 `protobuf:"varint,5,opt,name=mining_time_ms,json=miningTimeMs,proto3" json:"mining_time_ms,omitempty"`           // PoW计算耗时（毫秒）
	ParentHash       []byte                 `protobuf:"bytes,6,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`                    // 父区块哈希（K-bucket路由键）
	RelayHopLimit    uint32                 `protobuf:"varint,7,opt,name=relay_hop_limit,json=relayHopLimit,proto3" json:"relay_hop_limit,omitempty"`        // 中继跳数限制（默认1）
	// V2 新增：弃权与重选机制（仅用于"本高度轮"的弃权避环，不做跨高度/跨轮次累积）
	WaivedAggregators   [][]byte `protobuf:"bytes,8,rep,name=waived_aggregators,json=waivedAggregators,proto3" json:"waived_aggregators,omitempty"`            // 已知弃权的聚合器节点ID列表（避免回环）
	RetryAttempt        uint32   `protobuf:"varint,9,opt,name=retry_attempt,json=retryAttempt,proto3" json:"retry_attempt,omitempty"`                          // 重试次数（从0开始，每次重选+1）
	OriginalMinerPeerId []byte   `protobuf:"bytes,10,opt,name=original_miner_peer_id,json=originalMinerPeerId,proto3" json:"original_miner_peer_id,omitempty"` // 原始矿工节点ID（用于回环检测）
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MinerBlockSubmission) Reset() {
	*x = MinerBlockSubmission{}
	mi := &file_pb_network_protocol_consensus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MinerBlockSubmission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinerBlockSubmission) ProtoMessage() {}

func (x *MinerBlockSubmission) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_consensus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinerBlockSubmission.ProtoReflect.Descriptor instead.
func (*MinerBlockSubmission) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_consensus_proto_rawDescGZIP(), []int{1}
}

func (x *MinerBlockSubmission) GetBase() *BaseMessage {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *MinerBlockSubmission) GetCandidateBlock() *block.Block {
	if x != nil {
		return x.CandidateBlock
	}
	return nil
}

func (x *MinerBlockSubmission) GetMinerPeerId() []byte {
	if x != nil {
		return x.MinerPeerId
	}
	return nil
}

func (x *MinerBlockSubmission) GetMiningDifficulty() uint64 {
	if x != nil {
		return x.MiningDifficulty
	}
	return 0
}

func (x *MinerBlockSubmission) GetMiningTimeMs() uint64 {
	if x != nil {
		return x.MiningTimeMs
	}
	return 0
}

func (x *MinerBlockSubmission) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *MinerBlockSubmission) GetRelayHopLimit() uint32 {
	if x != nil {
		return x.RelayHopLimit
	}
	return 0
}

func (x *MinerBlockSubmission) GetWaivedAggregators() [][]byte {
	if x != nil {
		return x.WaivedAggregators
	}
	return nil
}

func (x *MinerBlockSubmission) GetRetryAttempt() uint32 {
	if x != nil {
		return x.RetryAttempt
	}
	return 0
}

func (x *MinerBlockSubmission) GetOriginalMinerPeerId() []byte {
	if x != nil {
		return x.OriginalMinerPeerId
	}
	return nil
}

// *
// AggregatorBlockAcceptance - 聚合器区块接受响应
//
// 🎯 设计目的：聚合器对矿工提交的候选区块给出接受或拒绝响应
//
// 🔄 V2 扩展（2025-12-15）：弃权响应机制
// - waived：是否弃权（true=本节点弃权，false=接受/拒绝）
// - waiver_reason：弃权原因（HEIGHT_TOO_FAR_AHEAD/AGGREGATION_IN_PROGRESS）
// - local_height：本节点当前高度（可选诊断字段，不参与裁决）
type AggregatorBlockAcceptance struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Base             *BaseMessage           `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`                                                   // 消息基础信息
	RequestId        string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                        // 对应的提交请求ID
	Accepted         bool                   `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`                                          // 是否接受候选区块
	AcceptanceReason string                 `protobuf:"bytes,4,opt,name=acceptance_reason,json=acceptanceReason,proto3" json:"acceptance_reason,omitempty"`   // 接受或拒绝的详细原因
	AggregatorPeerId []byte                 `protobuf:"bytes,5,opt,name=aggregator_peer_id,json=aggregatorPeerId,proto3" json:"aggregator_peer_id,omitempty"` // 聚合器节点ID
	Timestamp        uint64                 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                        // 处理时间戳
	// V2 新增：弃权响应
	Waived        bool                                   `protobuf:"varint,7,opt,name=waived,proto3" json:"waived,omitempty"`                                                                                                 // 是否弃权（true=本节点弃权，false=接受/拒绝）
	WaiverReason  AggregatorBlockAcceptance_WaiverReason `protobuf:"varint,8,opt,name=waiver_reason,json=waiverReason,proto3,enum=pb.network.protocol.AggregatorBlockAcceptance_WaiverReason" json:"waiver_reason,omitempty"` // 弃权原因（枚举）
	LocalHeight   uint64                                 `protobuf:"varint,9,opt,name=local_height,json=localHeight,proto3" json:"local_height,omitempty"`                                                                    // 本节点当前高度（可选诊断字段，不参与裁决）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregatorBlockAcceptance) Reset() {
	*x = AggregatorBlockAcceptance{}
	mi := &file_pb_network_protocol_consensus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatorBlockAcceptance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatorBlockAcceptance) ProtoMessage() {}

func (x *AggregatorBlockAcceptance) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_consensus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatorBlockAcceptance.ProtoReflect.Descriptor instead.
func (*AggregatorBlockAcceptance) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_consensus_proto_rawDescGZIP(), []int{2}
}

func (x *AggregatorBlockAcceptance) GetBase() *BaseMessage {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *AggregatorBlockAcceptance) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AggregatorBlockAcceptance) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *AggregatorBlockAcceptance) GetAcceptanceReason() string {
	if x != nil {
		return x.AcceptanceReason
	}
	return ""
}

func (x *AggregatorBlockAcceptance) GetAggregatorPeerId() []byte {
	if x != nil {
		return x.AggregatorPeerId
	}
	return nil
}

func (x *AggregatorBlockAcceptance) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AggregatorBlockAcceptance) GetWaived() bool {
	if x != nil {
		return x.Waived
	}
	return false
}

func (x *AggregatorBlockAcceptance) GetWaiverReason() AggregatorBlockAcceptance_WaiverReason {
	if x != nil {
		return x.WaiverReason
	}
	return AggregatorBlockAcceptance_WAIVER_NONE
}

func (x *AggregatorBlockAcceptance) GetLocalHeight() uint64 {
	if x != nil {
		return x.LocalHeight
	}
	return 0
}

// *
// ConsensusResultBroadcast - 共识结果广播消息
//
// 🎯 设计目的：聚合器向全网广播最终的共识决策结果
type ConsensusResultBroadcast struct {
	state              protoimpl.MessageState     `protogen:"open.v1"`
	Base               *BaseMessage               `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`                                                        // 消息基础信息
	SelectedBlockHash  []byte                     `protobuf:"bytes,2,opt,name=selected_block_hash,json=selectedBlockHash,proto3" json:"selected_block_hash,omitempty"`   // 选中区块的哈希
	FinalBlock         *block.Block               `protobuf:"bytes,3,opt,name=final_block,json=finalBlock,proto3" json:"final_block,omitempty"`                          // 最终选择的区块
	AggregatorPeerId   []byte                     `protobuf:"bytes,4,opt,name=aggregator_peer_id,json=aggregatorPeerId,proto3" json:"aggregator_peer_id,omitempty"`      // 决策聚合器节点ID
	DecisionResult     *AggregationDecisionResult `protobuf:"bytes,5,opt,name=decision_result,json=decisionResult,proto3" json:"decision_result,omitempty"`              // 详细的决策结果
	BroadcastTimestamp uint64                     `protobuf:"varint,6,opt,name=broadcast_timestamp,json=broadcastTimestamp,proto3" json:"broadcast_timestamp,omitempty"` // 广播时间戳
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConsensusResultBroadcast) Reset() {
	*x = ConsensusResultBroadcast{}
	mi := &file_pb_network_protocol_consensus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusResultBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusResultBroadcast) ProtoMessage() {}

func (x *ConsensusResultBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_consensus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusResultBroadcast.ProtoReflect.Descriptor instead.
func (*ConsensusResultBroadcast) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_consensus_proto_rawDescGZIP(), []int{3}
}

func (x *ConsensusResultBroadcast) GetBase() *BaseMessage {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ConsensusResultBroadcast) GetSelectedBlockHash() []byte {
	if x != nil {
		return x.SelectedBlockHash
	}
	return nil
}

func (x *ConsensusResultBroadcast) GetFinalBlock() *block.Block {
	if x != nil {
		return x.FinalBlock
	}
	return nil
}

func (x *ConsensusResultBroadcast) GetAggregatorPeerId() []byte {
	if x != nil {
		return x.AggregatorPeerId
	}
	return nil
}

func (x *ConsensusResultBroadcast) GetDecisionResult() *AggregationDecisionResult {
	if x != nil {
		return x.DecisionResult
	}
	return nil
}

func (x *ConsensusResultBroadcast) GetBroadcastTimestamp() uint64 {
	if x != nil {
		return x.BroadcastTimestamp
	}
	return 0
}

// *
// AggregationDecisionResult - 聚合决策距离概要（PoW+XOR）
//
// 🎯 设计目的：记录基于XOR距离的区块选择决策结果
type AggregationDecisionResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalCandidates  uint32                 `protobuf:"varint,1,opt,name=total_candidates,json=totalCandidates,proto3" json:"total_candidates,omitempty"`   // 参与决策的候选总数
	SelectedDistance string                 `protobuf:"bytes,2,opt,name=selected_distance,json=selectedDistance,proto3" json:"selected_distance,omitempty"` // 选中区块与父区块的XOR距离（大整数字符串）
	TieBreakApplied  bool                   `protobuf:"varint,3,opt,name=tie_break_applied,json=tieBreakApplied,proto3" json:"tie_break_applied,omitempty"` // 是否应用了距离tie-breaking
	SelectionReason  string                 `protobuf:"bytes,4,opt,name=selection_reason,json=selectionReason,proto3" json:"selection_reason,omitempty"`    // 选择原因简述（如 "xor_min_distance"）
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AggregationDecisionResult) Reset() {
	*x = AggregationDecisionResult{}
	mi := &file_pb_network_protocol_consensus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregationDecisionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregationDecisionResult) ProtoMessage() {}

func (x *AggregationDecisionResult) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_consensus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregationDecisionResult.ProtoReflect.Descriptor instead.
func (*AggregationDecisionResult) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_consensus_proto_rawDescGZIP(), []int{4}
}

func (x *AggregationDecisionResult) GetTotalCandidates() uint32 {
	if x != nil {
		return x.TotalCandidates
	}
	return 0
}

func (x *AggregationDecisionResult) GetSelectedDistance() string {
	if x != nil {
		return x.SelectedDistance
	}
	return ""
}

func (x *AggregationDecisionResult) GetTieBreakApplied() bool {
	if x != nil {
		return x.TieBreakApplied
	}
	return false
}

func (x *AggregationDecisionResult) GetSelectionReason() string {
	if x != nil {
		return x.SelectionReason
	}
	return ""
}

// *
// ConsensusHeartbeat - 共识心跳消息
//
// 🎯 设计目的：节点间的状态同步和网络健康监控
type ConsensusHeartbeat struct {
	state           protoimpl.MessageState        `protogen:"open.v1"`
	Base            *BaseMessage                  `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`                                                                                       // 消息基础信息
	NodeStatus      ConsensusHeartbeat_NodeStatus `protobuf:"varint,2,opt,name=node_status,json=nodeStatus,proto3,enum=pb.network.protocol.ConsensusHeartbeat_NodeStatus" json:"node_status,omitempty"` // 节点当前状态
	LastBlockHeight uint64                        `protobuf:"varint,3,opt,name=last_block_height,json=lastBlockHeight,proto3" json:"last_block_height,omitempty"`                                       // 最新区块高度
	LastBlockHash   []byte                        `protobuf:"bytes,4,opt,name=last_block_hash,json=lastBlockHash,proto3" json:"last_block_hash,omitempty"`                                              // 最新区块哈希
	ConnectedPeers  uint32                        `protobuf:"varint,5,opt,name=connected_peers,json=connectedPeers,proto3" json:"connected_peers,omitempty"`                                            // 已连接对等节点数
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConsensusHeartbeat) Reset() {
	*x = ConsensusHeartbeat{}
	mi := &file_pb_network_protocol_consensus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusHeartbeat) ProtoMessage() {}

func (x *ConsensusHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_consensus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusHeartbeat.ProtoReflect.Descriptor instead.
func (*ConsensusHeartbeat) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_consensus_proto_rawDescGZIP(), []int{5}
}

func (x *ConsensusHeartbeat) GetBase() *BaseMessage {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ConsensusHeartbeat) GetNodeStatus() ConsensusHeartbeat_NodeStatus {
	if x != nil {
		return x.NodeStatus
	}
	return ConsensusHeartbeat_NODE_STATUS_UNKNOWN
}

func (x *ConsensusHeartbeat) GetLastBlockHeight() uint64 {
	if x != nil {
		return x.LastBlockHeight
	}
	return 0
}

func (x *ConsensusHeartbeat) GetLastBlockHash() []byte {
	if x != nil {
		return x.LastBlockHash
	}
	return nil
}

func (x *ConsensusHeartbeat) GetConnectedPeers() uint32 {
	if x != nil {
		return x.ConnectedPeers
	}
	return 0
}

// *
// ConsensusError - 共识错误消息
//
// 🎯 设计目的：标准化共识过程中的错误报告和处理
type ConsensusError struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	Base             *BaseMessage             `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`                                                                               // 消息基础信息
	ErrorCode        ConsensusError_ErrorCode `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3,enum=pb.network.protocol.ConsensusError_ErrorCode" json:"error_code,omitempty"` // 标准化错误代码
	ErrorDescription string                   `protobuf:"bytes,3,opt,name=error_description,json=errorDescription,proto3" json:"error_description,omitempty"`                               // 错误详细描述
	RelatedMessageId *string                  `protobuf:"bytes,4,opt,name=related_message_id,json=relatedMessageId,proto3,oneof" json:"related_message_id,omitempty"`                       // 相关消息ID（引起错误的消息）
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConsensusError) Reset() {
	*x = ConsensusError{}
	mi := &file_pb_network_protocol_consensus_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusError) ProtoMessage() {}

func (x *ConsensusError) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_consensus_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusError.ProtoReflect.Descriptor instead.
func (*ConsensusError) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_consensus_proto_rawDescGZIP(), []int{6}
}

func (x *ConsensusError) GetBase() *BaseMessage {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ConsensusError) GetErrorCode() ConsensusError_ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ConsensusError_ERROR_UNKNOWN
}

func (x *ConsensusError) GetErrorDescription() string {
	if x != nil {
		return x.ErrorDescription
	}
	return ""
}

func (x *ConsensusError) GetRelatedMessageId() string {
	if x != nil && x.RelatedMessageId != nil {
		return *x.RelatedMessageId
	}
	return ""
}

// *
// AggregatorStatusQuery - 聚合器状态查询请求
//
// 🎯 设计目的：提交者主动查询聚合器状态，用于处理广播丢失场景
//
// 📡 协议映射：/weisyn/consensus/aggregator_status/1.0.0 (RPC)
//
// 🔄 使用场景：
// - 提交者等待45秒后未收到Gossip广播，主动查询聚合器状态
// - 查询聚合器是否已完成聚合，如果已完成则获取最终区块
// - 如果聚合器离线，触发重选机制
type AggregatorStatusQuery struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Base               *BaseMessage           `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`                                                               // 消息基础信息
	Height             uint64                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`                                                          // 查询的目标高度
	CandidateBlockHash []byte                 `protobuf:"bytes,3,opt,name=candidate_block_hash,json=candidateBlockHash,proto3,oneof" json:"candidate_block_hash,omitempty"` // 提交者自己的候选区块哈希（可选，用于验证）
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AggregatorStatusQuery) Reset() {
	*x = AggregatorStatusQuery{}
	mi := &file_pb_network_protocol_consensus_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatorStatusQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatorStatusQuery) ProtoMessage() {}

func (x *AggregatorStatusQuery) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_consensus_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatorStatusQuery.ProtoReflect.Descriptor instead.
func (*AggregatorStatusQuery) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_consensus_proto_rawDescGZIP(), []int{7}
}

func (x *AggregatorStatusQuery) GetBase() *BaseMessage {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *AggregatorStatusQuery) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *AggregatorStatusQuery) GetCandidateBlockHash() []byte {
	if x != nil {
		return x.CandidateBlockHash
	}
	return nil
}

// *
// AggregatorStatusResponse - 聚合器状态查询响应
//
// 🎯 设计目的：聚合器返回当前状态，供提交者判断下一步动作
//
// 🔄 状态说明：
// - COLLECTING：正在收集候选区块
// - EVALUATING：正在评估/选举
// - DISTRIBUTING：正在分发结果
// - COMPLETED：已完成（final_block不为空）
// - NOT_AGGREGATOR：本节点不是该高度的聚合器（触发重选）
type AggregatorStatusResponse struct {
	state                   protoimpl.MessageState                         `protogen:"open.v1"`
	Base                    *BaseMessage                                   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`                                                                              // 消息基础信息
	RequestId               string                                         `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                                                   // 对应的查询请求ID
	State                   AggregatorStatusResponse_AggregatorState       `protobuf:"varint,3,opt,name=state,proto3,enum=pb.network.protocol.AggregatorStatusResponse_AggregatorState" json:"state,omitempty"`         // 聚合器当前状态
	Height                  uint64                                         `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`                                                                         // 查询的高度
	FinalBlock              *block.Block                                   `protobuf:"bytes,5,opt,name=final_block,json=finalBlock,proto3,oneof" json:"final_block,omitempty"`                                          // 如果已完成，返回最终区块
	CollectionWindowEndTime uint64                                         `protobuf:"varint,6,opt,name=collection_window_end_time,json=collectionWindowEndTime,proto3" json:"collection_window_end_time,omitempty"`    // 收集窗口结束时间（Unix秒）
	CandidateCount          uint32                                         `protobuf:"varint,7,opt,name=candidate_count,json=candidateCount,proto3" json:"candidate_count,omitempty"`                                   // 已收集的候选数量
	Reason                  AggregatorStatusResponse_AggregatorStateReason `protobuf:"varint,8,opt,name=reason,proto3,enum=pb.network.protocol.AggregatorStatusResponse_AggregatorStateReason" json:"reason,omitempty"` // 状态原因（用于诊断）
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AggregatorStatusResponse) Reset() {
	*x = AggregatorStatusResponse{}
	mi := &file_pb_network_protocol_consensus_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatorStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatorStatusResponse) ProtoMessage() {}

func (x *AggregatorStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_consensus_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatorStatusResponse.ProtoReflect.Descriptor instead.
func (*AggregatorStatusResponse) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_consensus_proto_rawDescGZIP(), []int{8}
}

func (x *AggregatorStatusResponse) GetBase() *BaseMessage {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *AggregatorStatusResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AggregatorStatusResponse) GetState() AggregatorStatusResponse_AggregatorState {
	if x != nil {
		return x.State
	}
	return AggregatorStatusResponse_AGGREGATOR_STATE_UNKNOWN
}

func (x *AggregatorStatusResponse) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *AggregatorStatusResponse) GetFinalBlock() *block.Block {
	if x != nil {
		return x.FinalBlock
	}
	return nil
}

func (x *AggregatorStatusResponse) GetCollectionWindowEndTime() uint64 {
	if x != nil {
		return x.CollectionWindowEndTime
	}
	return 0
}

func (x *AggregatorStatusResponse) GetCandidateCount() uint32 {
	if x != nil {
		return x.CandidateCount
	}
	return 0
}

func (x *AggregatorStatusResponse) GetReason() AggregatorStatusResponse_AggregatorStateReason {
	if x != nil {
		return x.Reason
	}
	return AggregatorStatusResponse_REASON_NONE
}

var File_pb_network_protocol_consensus_proto protoreflect.FileDescriptor

const file_pb_network_protocol_consensus_proto_rawDesc = "" +
	"\n" +
	"#pb/network/protocol/consensus.proto\x12\x13pb.network.protocol\x1a\x1fpb/blockchain/block/block.proto\"p\n" +
	"\vBaseMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\fR\bsenderId\x12%\n" +
	"\x0etimestamp_unix\x18\x03 \x01(\x03R\rtimestampUnix\"\xd9\x03\n" +
	"\x14MinerBlockSubmission\x124\n" +
	"\x04base\x18\x01 \x01(\v2 .pb.network.protocol.BaseMessageR\x04base\x12B\n" +
	"\x0fcandidate_block\x18\x02 \x01(\v2\x19.pb.blockchain.core.BlockR\x0ecandidateBlock\x12\"\n" +
	"\rminer_peer_id\x18\x03 \x01(\fR\vminerPeerId\x12+\n" +
	"\x11mining_difficulty\x18\x04 \x01(\x04R\x10miningDifficulty\x12$\n" +
	"\x0emining_time_ms\x18\x05 \x01(\x04R\fminingTimeMs\x12\x1f\n" +
	"\vparent_hash\x18\x06 \x01(\fR\n" +
	"parentHash\x12&\n" +
	"\x0frelay_hop_limit\x18\a \x01(\rR\rrelayHopLimit\x12-\n" +
	"\x12waived_aggregators\x18\b \x03(\fR\x11waivedAggregators\x12#\n" +
	"\rretry_attempt\x18\t \x01(\rR\fretryAttempt\x123\n" +
	"\x16original_miner_peer_id\x18\n" +
	" \x01(\fR\x13originalMinerPeerId\"\xa3\x04\n" +
	"\x19AggregatorBlockAcceptance\x124\n" +
	"\x04base\x18\x01 \x01(\v2 .pb.network.protocol.BaseMessageR\x04base\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1a\n" +
	"\baccepted\x18\x03 \x01(\bR\baccepted\x12+\n" +
	"\x11acceptance_reason\x18\x04 \x01(\tR\x10acceptanceReason\x12,\n" +
	"\x12aggregator_peer_id\x18\x05 \x01(\fR\x10aggregatorPeerId\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x04R\ttimestamp\x12\x16\n" +
	"\x06waived\x18\a \x01(\bR\x06waived\x12`\n" +
	"\rwaiver_reason\x18\b \x01(\x0e2;.pb.network.protocol.AggregatorBlockAcceptance.WaiverReasonR\fwaiverReason\x12!\n" +
	"\flocal_height\x18\t \x01(\x04R\vlocalHeight\"\x7f\n" +
	"\fWaiverReason\x12\x0f\n" +
	"\vWAIVER_NONE\x10\x00\x12\x1f\n" +
	"\x1bWAIVER_HEIGHT_TOO_FAR_AHEAD\x10\x01\x12\"\n" +
	"\x1eWAIVER_AGGREGATION_IN_PROGRESS\x10\x02\x12\x19\n" +
	"\x15WAIVER_READ_ONLY_MODE\x10\x03\"\xf4\x02\n" +
	"\x18ConsensusResultBroadcast\x124\n" +
	"\x04base\x18\x01 \x01(\v2 .pb.network.protocol.BaseMessageR\x04base\x12.\n" +
	"\x13selected_block_hash\x18\x02 \x01(\fR\x11selectedBlockHash\x12:\n" +
	"\vfinal_block\x18\x03 \x01(\v2\x19.pb.blockchain.core.BlockR\n" +
	"finalBlock\x12,\n" +
	"\x12aggregator_peer_id\x18\x04 \x01(\fR\x10aggregatorPeerId\x12W\n" +
	"\x0fdecision_result\x18\x05 \x01(\v2..pb.network.protocol.AggregationDecisionResultR\x0edecisionResult\x12/\n" +
	"\x13broadcast_timestamp\x18\x06 \x01(\x04R\x12broadcastTimestamp\"\xca\x01\n" +
	"\x19AggregationDecisionResult\x12)\n" +
	"\x10total_candidates\x18\x01 \x01(\rR\x0ftotalCandidates\x12+\n" +
	"\x11selected_distance\x18\x02 \x01(\tR\x10selectedDistance\x12*\n" +
	"\x11tie_break_applied\x18\x03 \x01(\bR\x0ftieBreakApplied\x12)\n" +
	"\x10selection_reason\x18\x04 \x01(\tR\x0fselectionReason\"\xc3\x03\n" +
	"\x12ConsensusHeartbeat\x124\n" +
	"\x04base\x18\x01 \x01(\v2 .pb.network.protocol.BaseMessageR\x04base\x12S\n" +
	"\vnode_status\x18\x02 \x01(\x0e22.pb.network.protocol.ConsensusHeartbeat.NodeStatusR\n" +
	"nodeStatus\x12*\n" +
	"\x11last_block_height\x18\x03 \x01(\x04R\x0flastBlockHeight\x12&\n" +
	"\x0flast_block_hash\x18\x04 \x01(\fR\rlastBlockHash\x12'\n" +
	"\x0fconnected_peers\x18\x05 \x01(\rR\x0econnectedPeers\"\xa4\x01\n" +
	"\n" +
	"NodeStatus\x12\x17\n" +
	"\x13NODE_STATUS_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12NODE_STATUS_ACTIVE\x10\x01\x12\x17\n" +
	"\x13NODE_STATUS_SYNCING\x10\x02\x12\x16\n" +
	"\x12NODE_STATUS_MINING\x10\x03\x12\x1b\n" +
	"\x17NODE_STATUS_AGGREGATING\x10\x04\x12\x17\n" +
	"\x13NODE_STATUS_OFFLINE\x10\x05\"\xd5\x03\n" +
	"\x0eConsensusError\x124\n" +
	"\x04base\x18\x01 \x01(\v2 .pb.network.protocol.BaseMessageR\x04base\x12L\n" +
	"\n" +
	"error_code\x18\x02 \x01(\x0e2-.pb.network.protocol.ConsensusError.ErrorCodeR\terrorCode\x12+\n" +
	"\x11error_description\x18\x03 \x01(\tR\x10errorDescription\x121\n" +
	"\x12related_message_id\x18\x04 \x01(\tH\x00R\x10relatedMessageId\x88\x01\x01\"\xc7\x01\n" +
	"\tErrorCode\x12\x11\n" +
	"\rERROR_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15ERROR_INVALID_MESSAGE\x10\x01\x12\x17\n" +
	"\x13ERROR_INVALID_BLOCK\x10\x02\x12\x1b\n" +
	"\x17ERROR_INVALID_SIGNATURE\x10\x03\x12\x19\n" +
	"\x15ERROR_NETWORK_TIMEOUT\x10\x04\x12\x1b\n" +
	"\x17ERROR_CONSENSUS_FAILURE\x10\x05\x12\x1e\n" +
	"\x1aERROR_DUPLICATE_SUBMISSION\x10\x06B\x15\n" +
	"\x13_related_message_id\"\xb5\x01\n" +
	"\x15AggregatorStatusQuery\x124\n" +
	"\x04base\x18\x01 \x01(\v2 .pb.network.protocol.BaseMessageR\x04base\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\x125\n" +
	"\x14candidate_block_hash\x18\x03 \x01(\fH\x00R\x12candidateBlockHash\x88\x01\x01B\x17\n" +
	"\x15_candidate_block_hash\"\x97\a\n" +
	"\x18AggregatorStatusResponse\x124\n" +
	"\x04base\x18\x01 \x01(\v2 .pb.network.protocol.BaseMessageR\x04base\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12S\n" +
	"\x05state\x18\x03 \x01(\x0e2=.pb.network.protocol.AggregatorStatusResponse.AggregatorStateR\x05state\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x04R\x06height\x12?\n" +
	"\vfinal_block\x18\x05 \x01(\v2\x19.pb.blockchain.core.BlockH\x00R\n" +
	"finalBlock\x88\x01\x01\x12;\n" +
	"\x1acollection_window_end_time\x18\x06 \x01(\x04R\x17collectionWindowEndTime\x12'\n" +
	"\x0fcandidate_count\x18\a \x01(\rR\x0ecandidateCount\x12[\n" +
	"\x06reason\x18\b \x01(\x0e2C.pb.network.protocol.AggregatorStatusResponse.AggregatorStateReasonR\x06reason\"\xd9\x01\n" +
	"\x0fAggregatorState\x12\x1c\n" +
	"\x18AGGREGATOR_STATE_UNKNOWN\x10\x00\x12\x1f\n" +
	"\x1bAGGREGATOR_STATE_COLLECTING\x10\x01\x12\x1f\n" +
	"\x1bAGGREGATOR_STATE_EVALUATING\x10\x02\x12!\n" +
	"\x1dAGGREGATOR_STATE_DISTRIBUTING\x10\x03\x12\x1e\n" +
	"\x1aAGGREGATOR_STATE_COMPLETED\x10\x04\x12#\n" +
	"\x1fAGGREGATOR_STATE_NOT_AGGREGATOR\x10\x05\"\xc8\x01\n" +
	"\x15AggregatorStateReason\x12\x0f\n" +
	"\vREASON_NONE\x10\x00\x12!\n" +
	"\x1dREASON_WAITING_FOR_CANDIDATES\x10\x01\x12 \n" +
	"\x1cREASON_CALCULATING_DISTANCES\x10\x02\x12\x1e\n" +
	"\x1aREASON_BROADCASTING_RESULT\x10\x03\x12\x1c\n" +
	"\x18REASON_ALREADY_COMPLETED\x10\x04\x12\x1b\n" +
	"\x17REASON_WRONG_AGGREGATOR\x10\x05B\x0e\n" +
	"\f_final_blockB*Z(github.com/weisyn/v1/pb/network/protocolb\x06proto3"

var (
	file_pb_network_protocol_consensus_proto_rawDescOnce sync.Once
	file_pb_network_protocol_consensus_proto_rawDescData []byte
)

func file_pb_network_protocol_consensus_proto_rawDescGZIP() []byte {
	file_pb_network_protocol_consensus_proto_rawDescOnce.Do(func() {
		file_pb_network_protocol_consensus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_network_protocol_consensus_proto_rawDesc), len(file_pb_network_protocol_consensus_proto_rawDesc)))
	})
	return file_pb_network_protocol_consensus_proto_rawDescData
}

var file_pb_network_protocol_consensus_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_pb_network_protocol_consensus_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pb_network_protocol_consensus_proto_goTypes = []any{
	(AggregatorBlockAcceptance_WaiverReason)(0),         // 0: pb.network.protocol.AggregatorBlockAcceptance.WaiverReason
	(ConsensusHeartbeat_NodeStatus)(0),                  // 1: pb.network.protocol.ConsensusHeartbeat.NodeStatus
	(ConsensusError_ErrorCode)(0),                       // 2: pb.network.protocol.ConsensusError.ErrorCode
	(AggregatorStatusResponse_AggregatorState)(0),       // 3: pb.network.protocol.AggregatorStatusResponse.AggregatorState
	(AggregatorStatusResponse_AggregatorStateReason)(0), // 4: pb.network.protocol.AggregatorStatusResponse.AggregatorStateReason
	(*BaseMessage)(nil),                                 // 5: pb.network.protocol.BaseMessage
	(*MinerBlockSubmission)(nil),                        // 6: pb.network.protocol.MinerBlockSubmission
	(*AggregatorBlockAcceptance)(nil),                   // 7: pb.network.protocol.AggregatorBlockAcceptance
	(*ConsensusResultBroadcast)(nil),                    // 8: pb.network.protocol.ConsensusResultBroadcast
	(*AggregationDecisionResult)(nil),                   // 9: pb.network.protocol.AggregationDecisionResult
	(*ConsensusHeartbeat)(nil),                          // 10: pb.network.protocol.ConsensusHeartbeat
	(*ConsensusError)(nil),                              // 11: pb.network.protocol.ConsensusError
	(*AggregatorStatusQuery)(nil),                       // 12: pb.network.protocol.AggregatorStatusQuery
	(*AggregatorStatusResponse)(nil),                    // 13: pb.network.protocol.AggregatorStatusResponse
	(*block.Block)(nil),                                 // 14: pb.blockchain.core.Block
}
var file_pb_network_protocol_consensus_proto_depIdxs = []int32{
	5,  // 0: pb.network.protocol.MinerBlockSubmission.base:type_name -> pb.network.protocol.BaseMessage
	14, // 1: pb.network.protocol.MinerBlockSubmission.candidate_block:type_name -> pb.blockchain.core.Block
	5,  // 2: pb.network.protocol.AggregatorBlockAcceptance.base:type_name -> pb.network.protocol.BaseMessage
	0,  // 3: pb.network.protocol.AggregatorBlockAcceptance.waiver_reason:type_name -> pb.network.protocol.AggregatorBlockAcceptance.WaiverReason
	5,  // 4: pb.network.protocol.ConsensusResultBroadcast.base:type_name -> pb.network.protocol.BaseMessage
	14, // 5: pb.network.protocol.ConsensusResultBroadcast.final_block:type_name -> pb.blockchain.core.Block
	9,  // 6: pb.network.protocol.ConsensusResultBroadcast.decision_result:type_name -> pb.network.protocol.AggregationDecisionResult
	5,  // 7: pb.network.protocol.ConsensusHeartbeat.base:type_name -> pb.network.protocol.BaseMessage
	1,  // 8: pb.network.protocol.ConsensusHeartbeat.node_status:type_name -> pb.network.protocol.ConsensusHeartbeat.NodeStatus
	5,  // 9: pb.network.protocol.ConsensusError.base:type_name -> pb.network.protocol.BaseMessage
	2,  // 10: pb.network.protocol.ConsensusError.error_code:type_name -> pb.network.protocol.ConsensusError.ErrorCode
	5,  // 11: pb.network.protocol.AggregatorStatusQuery.base:type_name -> pb.network.protocol.BaseMessage
	5,  // 12: pb.network.protocol.AggregatorStatusResponse.base:type_name -> pb.network.protocol.BaseMessage
	3,  // 13: pb.network.protocol.AggregatorStatusResponse.state:type_name -> pb.network.protocol.AggregatorStatusResponse.AggregatorState
	14, // 14: pb.network.protocol.AggregatorStatusResponse.final_block:type_name -> pb.blockchain.core.Block
	4,  // 15: pb.network.protocol.AggregatorStatusResponse.reason:type_name -> pb.network.protocol.AggregatorStatusResponse.AggregatorStateReason
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_pb_network_protocol_consensus_proto_init() }
func file_pb_network_protocol_consensus_proto_init() {
	if File_pb_network_protocol_consensus_proto != nil {
		return
	}
	file_pb_network_protocol_consensus_proto_msgTypes[6].OneofWrappers = []any{}
	file_pb_network_protocol_consensus_proto_msgTypes[7].OneofWrappers = []any{}
	file_pb_network_protocol_consensus_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_network_protocol_consensus_proto_rawDesc), len(file_pb_network_protocol_consensus_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_network_protocol_consensus_proto_goTypes,
		DependencyIndexes: file_pb_network_protocol_consensus_proto_depIdxs,
		EnumInfos:         file_pb_network_protocol_consensus_proto_enumTypes,
		MessageInfos:      file_pb_network_protocol_consensus_proto_msgTypes,
	}.Build()
	File_pb_network_protocol_consensus_proto = out.File
	file_pb_network_protocol_consensus_proto_goTypes = nil
	file_pb_network_protocol_consensus_proto_depIdxs = nil
}
