// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: pb/network/protocol/sync.proto

package protocol

import (
	block "github.com/weisyn/v1/pb/blockchain/block"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncRelationship 节点间链关系判定结果（用于指导下一步动作）
type SyncRelationship int32

const (
	SyncRelationship_SYNC_RELATIONSHIP_UNSPECIFIED SyncRelationship = 0
	SyncRelationship_UP_TO_DATE                    SyncRelationship = 1 // 高度与 hash 一致，无需同步
	SyncRelationship_REMOTE_BEHIND                 SyncRelationship = 2 // 对端高度落后我方（对端应自同步）
	SyncRelationship_REMOTE_AHEAD_SAME_CHAIN       SyncRelationship = 3 // 对端领先，且在我方 tip_height 处 hash 一致（可安全拉后续）
	SyncRelationship_FORK_DETECTED                 SyncRelationship = 4 // 同高度 hash 不一致（分叉，需要 reorg 或回退找共同祖先）
	SyncRelationship_UNKNOWN                       SyncRelationship = 5 // 无法判断（例如 locator 太短或本地缺块）
)

// Enum value maps for SyncRelationship.
var (
	SyncRelationship_name = map[int32]string{
		0: "SYNC_RELATIONSHIP_UNSPECIFIED",
		1: "UP_TO_DATE",
		2: "REMOTE_BEHIND",
		3: "REMOTE_AHEAD_SAME_CHAIN",
		4: "FORK_DETECTED",
		5: "UNKNOWN",
	}
	SyncRelationship_value = map[string]int32{
		"SYNC_RELATIONSHIP_UNSPECIFIED": 0,
		"UP_TO_DATE":                    1,
		"REMOTE_BEHIND":                 2,
		"REMOTE_AHEAD_SAME_CHAIN":       3,
		"FORK_DETECTED":                 4,
		"UNKNOWN":                       5,
	}
)

func (x SyncRelationship) Enum() *SyncRelationship {
	p := new(SyncRelationship)
	*p = x
	return p
}

func (x SyncRelationship) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncRelationship) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_network_protocol_sync_proto_enumTypes[0].Descriptor()
}

func (SyncRelationship) Type() protoreflect.EnumType {
	return &file_pb_network_protocol_sync_proto_enumTypes[0]
}

func (x SyncRelationship) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncRelationship.Descriptor instead.
func (SyncRelationship) EnumDescriptor() ([]byte, []int) {
	return file_pb_network_protocol_sync_proto_rawDescGZIP(), []int{0}
}

// *
// ChainIdentity - 链身份标识
//
// 🎯 设计目的：在所有跨节点通信中明确标识"这是不是同一条链"
//
// 包含链的核心标识信息，用于防止串链攻击和错误配置。
// 接收方必须验证请求的链身份是否与本地匹配，不匹配则拒绝请求。
type ChainIdentity struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ChainId          string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`                            // 链ID（数字字符串或十六进制）
	NetworkNamespace string                 `protobuf:"bytes,2,opt,name=network_namespace,json=networkNamespace,proto3" json:"network_namespace,omitempty"` // 网络命名空间（如 "mainnet-public", "test-consortium"）
	NetworkId        string                 `protobuf:"bytes,3,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`                      // 网络标识符（如 "WES_mainnet_2025"）
	ChainMode        string                 `protobuf:"bytes,4,opt,name=chain_mode,json=chainMode,proto3" json:"chain_mode,omitempty"`                      // 链模式：public | consortium | private
	GenesisHash      string                 `protobuf:"bytes,5,opt,name=genesis_hash,json=genesisHash,proto3" json:"genesis_hash,omitempty"`                // 创世区块哈希（十六进制字符串，32字节）
	VersionTag       string                 `protobuf:"bytes,6,opt,name=version_tag,json=versionTag,proto3" json:"version_tag,omitempty"`                   // 版本标签（可选，如 "v1", "v1.1-hotfix"）
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChainIdentity) Reset() {
	*x = ChainIdentity{}
	mi := &file_pb_network_protocol_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainIdentity) ProtoMessage() {}

func (x *ChainIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainIdentity.ProtoReflect.Descriptor instead.
func (*ChainIdentity) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_sync_proto_rawDescGZIP(), []int{0}
}

func (x *ChainIdentity) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *ChainIdentity) GetNetworkNamespace() string {
	if x != nil {
		return x.NetworkNamespace
	}
	return ""
}

func (x *ChainIdentity) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *ChainIdentity) GetChainMode() string {
	if x != nil {
		return x.ChainMode
	}
	return ""
}

func (x *ChainIdentity) GetGenesisHash() string {
	if x != nil {
		return x.GenesisHash
	}
	return ""
}

func (x *ChainIdentity) GetVersionTag() string {
	if x != nil {
		return x.VersionTag
	}
	return ""
}

// *
// KBucketSyncRequest - K-bucket智能同步请求
//
// 🎯 设计目的：基于Kademlia距离算法选择最优同步节点
//
// 🔗 节点选择机制：
// - 路由键生成：使用父区块哈希（或默认值）作为路由键
// - 距离计算：routing_key XOR peer_node_id，选择距离最小的节点
// - 近邻优选：从K-bucket中选择最近的8个节点作为候选
// - 并发尝试：同时向多个近邻节点发起同步请求
//
// 🔄 同步流程：
// 1. 请求方计算路由键（通常是本地最新区块的哈希）
// 2. 查询K-bucket，获取距离最近的节点列表
// 3. 发送KBucketSyncRequest到选中的节点
// 4. 接收方检查高度差异，决定是否提供区块数据
// 5. 如请求失败，自动选择下一批近邻节点重试
//
// 🛡️ 链身份验证：
// - 请求必须携带 chain_identity 字段
// - 接收方首先验证 chain_identity 是否与本地匹配
// - 不匹配则拒绝请求，避免串链攻击
//
// 📝 使用示例：
//
//	kbucket_sync_request {
//	  request_id: "sync_001"
//	  local_height: 12345
//	  routing_key: sha256(local_latest_block_hash)  // 基于本地最新区块计算
//	  max_response_size: 5242880  // 5MB限制
//	  requester_peer_id: "QmXXXXX..."
//	  chain_identity: {
//	    chain_id: "12345"
//	    network_namespace: "mainnet-public"
//	    chain_mode: "public"
//	    genesis_hash: "abcd1234..."
//	  }
//	}
type KBucketSyncRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	RequestId   string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`        // 请求唯一标识符
	LocalHeight uint64                 `protobuf:"varint,2,opt,name=local_height,json=localHeight,proto3" json:"local_height,omitempty"` // 本地区块链高度
	RoutingKey  []byte                 `protobuf:"bytes,3,opt,name=routing_key,json=routingKey,proto3" json:"routing_key,omitempty"`     // 路由键（用于K-bucket距离计算）
	// 通常使用父区块哈希，空值时使用默认路由键
	MaxResponseSize uint32 `protobuf:"varint,4,opt,name=max_response_size,json=maxResponseSize,proto3" json:"max_response_size,omitempty"` // 期望的最大响应大小（字节）
	// 接收方根据此值进行智能分页
	RequesterPeerId []byte `protobuf:"bytes,5,opt,name=requester_peer_id,json=requesterPeerId,proto3" json:"requester_peer_id,omitempty"` // 请求者节点ID
	// 同步上下文
	TargetHeight *uint64 `protobuf:"varint,11,opt,name=target_height,json=targetHeight,proto3,oneof" json:"target_height,omitempty"` // 目标同步高度（可选，0表示同步到最新）
	// 链身份验证（新增）
	ChainIdentity *ChainIdentity `protobuf:"bytes,12,opt,name=chain_identity,json=chainIdentity,proto3" json:"chain_identity,omitempty"` // 请求方的链身份标识（用于防止串链）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KBucketSyncRequest) Reset() {
	*x = KBucketSyncRequest{}
	mi := &file_pb_network_protocol_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KBucketSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KBucketSyncRequest) ProtoMessage() {}

func (x *KBucketSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KBucketSyncRequest.ProtoReflect.Descriptor instead.
func (*KBucketSyncRequest) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_sync_proto_rawDescGZIP(), []int{1}
}

func (x *KBucketSyncRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *KBucketSyncRequest) GetLocalHeight() uint64 {
	if x != nil {
		return x.LocalHeight
	}
	return 0
}

func (x *KBucketSyncRequest) GetRoutingKey() []byte {
	if x != nil {
		return x.RoutingKey
	}
	return nil
}

func (x *KBucketSyncRequest) GetMaxResponseSize() uint32 {
	if x != nil {
		return x.MaxResponseSize
	}
	return 0
}

func (x *KBucketSyncRequest) GetRequesterPeerId() []byte {
	if x != nil {
		return x.RequesterPeerId
	}
	return nil
}

func (x *KBucketSyncRequest) GetTargetHeight() uint64 {
	if x != nil && x.TargetHeight != nil {
		return *x.TargetHeight
	}
	return 0
}

func (x *KBucketSyncRequest) GetChainIdentity() *ChainIdentity {
	if x != nil {
		return x.ChainIdentity
	}
	return nil
}

// *
// IntelligentPaginationResponse - 智能分页同步响应
//
// 🎯 设计目的：接收方根据网络状况和区块大小智能分页返回数据
//
// 🔧 智能分页逻辑：
// - 请求解析：接收方分析请求的高度范围和大小限制
// - 区块评估：计算每个区块的序列化大小
// - 分页决策：在网络限制内选择最优的区块数量
// - 最小保障：即使单个区块超过限制，也至少返回1个区块
//
// 📊 分页策略：
// - 网络限制优先：根据max_response_size进行硬限制
// - 区块完整性：不会截断单个区块，保证区块完整传输
// - 批次优化：优先选择能够填满网络限制的区块批次
// - 延迟优化：避免过小批次导致的往返延迟
//
// 🛡️ 链身份验证：
// - 响应可选携带 chain_identity 字段（用于响应端再校验）
// - 请求方可以验证响应的链身份是否与请求匹配
//
// 📝 使用示例：
//
//	intelligent_pagination_response {
//	  request_id: "sync_001"
//	  blocks: [block_12346, block_12347, block_12348]
//	  next_height: 12349
//	  has_more: true
//	  actual_size: 4194304  // 实际返回4MB数据
//	  pagination_reason: "NETWORK_SIZE_LIMIT"
//	  chain_identity: {
//	    chain_id: "12345"
//	    network_namespace: "mainnet-public"
//	    chain_mode: "public"
//	    genesis_hash: "abcd1234..."
//	  }
//	}
//
// 🔄 分页流程：
// 1. 接收方收到KBucketSyncRequest
// 2. 检查本地高度是否高于请求方高度
// 3. 计算需要同步的区块范围：[local_height+1, remote_height]
// 4. 从起始高度开始，逐个累加区块大小
// 5. 当累积大小接近max_response_size时停止
// 6. 返回当前批次，并指示是否还有更多数据
type IntelligentPaginationResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestId        string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                      // 对应请求ID
	Blocks           []*block.Block         `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`                                             // 当前批次的区块列表
	NextHeight       uint64                 `protobuf:"varint,3,opt,name=next_height,json=nextHeight,proto3" json:"next_height,omitempty"`                  // 下次请求应该使用的起始高度
	HasMore          bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`                           // 是否还有更多数据待传输
	ActualSize       uint32                 `protobuf:"varint,5,opt,name=actual_size,json=actualSize,proto3" json:"actual_size,omitempty"`                  // 实际返回的数据大小（字节）
	PaginationReason string                 `protobuf:"bytes,6,opt,name=pagination_reason,json=paginationReason,proto3" json:"pagination_reason,omitempty"` // 分页原因说明
	// 错误处理
	Success      bool    `protobuf:"varint,30,opt,name=success,proto3" json:"success,omitempty"`                                    // 处理是否成功
	ErrorMessage *string `protobuf:"bytes,31,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"` // 错误信息（失败时）
	// 链身份验证（新增，可选）
	ChainIdentity *ChainIdentity `protobuf:"bytes,32,opt,name=chain_identity,json=chainIdentity,proto3,oneof" json:"chain_identity,omitempty"` // 响应方的链身份标识（用于响应端再校验）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntelligentPaginationResponse) Reset() {
	*x = IntelligentPaginationResponse{}
	mi := &file_pb_network_protocol_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntelligentPaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntelligentPaginationResponse) ProtoMessage() {}

func (x *IntelligentPaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntelligentPaginationResponse.ProtoReflect.Descriptor instead.
func (*IntelligentPaginationResponse) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_sync_proto_rawDescGZIP(), []int{2}
}

func (x *IntelligentPaginationResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *IntelligentPaginationResponse) GetBlocks() []*block.Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *IntelligentPaginationResponse) GetNextHeight() uint64 {
	if x != nil {
		return x.NextHeight
	}
	return 0
}

func (x *IntelligentPaginationResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *IntelligentPaginationResponse) GetActualSize() uint32 {
	if x != nil {
		return x.ActualSize
	}
	return 0
}

func (x *IntelligentPaginationResponse) GetPaginationReason() string {
	if x != nil {
		return x.PaginationReason
	}
	return ""
}

func (x *IntelligentPaginationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IntelligentPaginationResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *IntelligentPaginationResponse) GetChainIdentity() *ChainIdentity {
	if x != nil {
		return x.ChainIdentity
	}
	return nil
}

// BlockLocatorEntry 用于快速寻找共同祖先（携带 height + hash，避免依赖 hash->height 索引）。
type BlockLocatorEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`                       // 区块高度
	BlockHash     []byte                 `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"` // 该高度的区块哈希（32 bytes）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockLocatorEntry) Reset() {
	*x = BlockLocatorEntry{}
	mi := &file_pb_network_protocol_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockLocatorEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockLocatorEntry) ProtoMessage() {}

func (x *BlockLocatorEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockLocatorEntry.ProtoReflect.Descriptor instead.
func (*BlockLocatorEntry) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_sync_proto_rawDescGZIP(), []int{3}
}

func (x *BlockLocatorEntry) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlockLocatorEntry) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

// BlockLocator 从 tip 往前抽样的一组 (height, hash)（例如 tip, tip-1, tip-2, tip-4, ...）
type BlockLocator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*BlockLocatorEntry   `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockLocator) Reset() {
	*x = BlockLocator{}
	mi := &file_pb_network_protocol_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockLocator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockLocator) ProtoMessage() {}

func (x *BlockLocator) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockLocator.ProtoReflect.Descriptor instead.
func (*BlockLocator) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_sync_proto_rawDescGZIP(), []int{4}
}

func (x *BlockLocator) GetEntries() []*BlockLocatorEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// SyncHelloV2Request：同步握手（携带高度+哈希+locator），用于判定关系与共同祖先。
type SyncHelloV2Request struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                       // 请求唯一标识符
	ChainIdentity   *ChainIdentity         `protobuf:"bytes,2,opt,name=chain_identity,json=chainIdentity,proto3" json:"chain_identity,omitempty"`           // 链身份（必须校验）
	LocalTipHeight  uint64                 `protobuf:"varint,10,opt,name=local_tip_height,json=localTipHeight,proto3" json:"local_tip_height,omitempty"`    // 请求方链尖高度
	LocalTipHash    []byte                 `protobuf:"bytes,11,opt,name=local_tip_hash,json=localTipHash,proto3" json:"local_tip_hash,omitempty"`           // 请求方链尖哈希（32 bytes）
	Locator         *BlockLocator          `protobuf:"bytes,20,opt,name=locator,proto3" json:"locator,omitempty"`                                           // 用于寻找共同祖先
	MaxResponseSize uint32                 `protobuf:"varint,30,opt,name=max_response_size,json=maxResponseSize,proto3" json:"max_response_size,omitempty"` // 服务端可参考该值决定响应负载上限（字节）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SyncHelloV2Request) Reset() {
	*x = SyncHelloV2Request{}
	mi := &file_pb_network_protocol_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncHelloV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncHelloV2Request) ProtoMessage() {}

func (x *SyncHelloV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncHelloV2Request.ProtoReflect.Descriptor instead.
func (*SyncHelloV2Request) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_sync_proto_rawDescGZIP(), []int{5}
}

func (x *SyncHelloV2Request) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SyncHelloV2Request) GetChainIdentity() *ChainIdentity {
	if x != nil {
		return x.ChainIdentity
	}
	return nil
}

func (x *SyncHelloV2Request) GetLocalTipHeight() uint64 {
	if x != nil {
		return x.LocalTipHeight
	}
	return 0
}

func (x *SyncHelloV2Request) GetLocalTipHash() []byte {
	if x != nil {
		return x.LocalTipHash
	}
	return nil
}

func (x *SyncHelloV2Request) GetLocator() *BlockLocator {
	if x != nil {
		return x.Locator
	}
	return nil
}

func (x *SyncHelloV2Request) GetMaxResponseSize() uint32 {
	if x != nil {
		return x.MaxResponseSize
	}
	return 0
}

// SyncHelloV2Response：返回关系判定、对端链尖、共同祖先（若可确定）。
type SyncHelloV2Response struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success         bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage    *string                `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	ChainIdentity   *ChainIdentity         `protobuf:"bytes,4,opt,name=chain_identity,json=chainIdentity,proto3,oneof" json:"chain_identity,omitempty"` // 响应端链身份（可选，便于请求端 double-check）
	RemoteTipHeight uint64                 `protobuf:"varint,10,opt,name=remote_tip_height,json=remoteTipHeight,proto3" json:"remote_tip_height,omitempty"`
	RemoteTipHash   []byte                 `protobuf:"bytes,11,opt,name=remote_tip_hash,json=remoteTipHash,proto3" json:"remote_tip_hash,omitempty"`
	Relationship    SyncRelationship       `protobuf:"varint,20,opt,name=relationship,proto3,enum=pb.network.protocol.SyncRelationship" json:"relationship,omitempty"`
	// 若确定共同祖先，则填充；否则为 0/空
	CommonAncestorHeight uint64 `protobuf:"varint,30,opt,name=common_ancestor_height,json=commonAncestorHeight,proto3" json:"common_ancestor_height,omitempty"`
	CommonAncestorHash   []byte `protobuf:"bytes,31,opt,name=common_ancestor_hash,json=commonAncestorHash,proto3" json:"common_ancestor_hash,omitempty"`
	// 对请求方的下一步建议（可选，诊断友好）
	Recommendation *string `protobuf:"bytes,40,opt,name=recommendation,proto3,oneof" json:"recommendation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncHelloV2Response) Reset() {
	*x = SyncHelloV2Response{}
	mi := &file_pb_network_protocol_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncHelloV2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncHelloV2Response) ProtoMessage() {}

func (x *SyncHelloV2Response) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncHelloV2Response.ProtoReflect.Descriptor instead.
func (*SyncHelloV2Response) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_sync_proto_rawDescGZIP(), []int{6}
}

func (x *SyncHelloV2Response) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SyncHelloV2Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncHelloV2Response) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *SyncHelloV2Response) GetChainIdentity() *ChainIdentity {
	if x != nil {
		return x.ChainIdentity
	}
	return nil
}

func (x *SyncHelloV2Response) GetRemoteTipHeight() uint64 {
	if x != nil {
		return x.RemoteTipHeight
	}
	return 0
}

func (x *SyncHelloV2Response) GetRemoteTipHash() []byte {
	if x != nil {
		return x.RemoteTipHash
	}
	return nil
}

func (x *SyncHelloV2Response) GetRelationship() SyncRelationship {
	if x != nil {
		return x.Relationship
	}
	return SyncRelationship_SYNC_RELATIONSHIP_UNSPECIFIED
}

func (x *SyncHelloV2Response) GetCommonAncestorHeight() uint64 {
	if x != nil {
		return x.CommonAncestorHeight
	}
	return 0
}

func (x *SyncHelloV2Response) GetCommonAncestorHash() []byte {
	if x != nil {
		return x.CommonAncestorHash
	}
	return nil
}

func (x *SyncHelloV2Response) GetRecommendation() string {
	if x != nil && x.Recommendation != nil {
		return *x.Recommendation
	}
	return ""
}

// SyncBlocksV2Request：在确认同链可线性同步后，按高度范围拉取区块批次。
type SyncBlocksV2Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ChainIdentity *ChainIdentity         `protobuf:"bytes,2,opt,name=chain_identity,json=chainIdentity,proto3" json:"chain_identity,omitempty"`
	FromHeight    uint64                 `protobuf:"varint,10,opt,name=from_height,json=fromHeight,proto3" json:"from_height,omitempty"` // 起始高度（包含）
	ToHeight      uint64                 `protobuf:"varint,11,opt,name=to_height,json=toHeight,proto3" json:"to_height,omitempty"`       // 结束高度（包含）
	// 可选：请求方期望的 parent hash，用于服务端快速 sanity-check “是否连在一起”
	ExpectedParentHash []byte `protobuf:"bytes,20,opt,name=expected_parent_hash,json=expectedParentHash,proto3,oneof" json:"expected_parent_hash,omitempty"`
	MaxResponseSize    uint32 `protobuf:"varint,30,opt,name=max_response_size,json=maxResponseSize,proto3" json:"max_response_size,omitempty"` // 响应大小上限（字节）
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SyncBlocksV2Request) Reset() {
	*x = SyncBlocksV2Request{}
	mi := &file_pb_network_protocol_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncBlocksV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncBlocksV2Request) ProtoMessage() {}

func (x *SyncBlocksV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncBlocksV2Request.ProtoReflect.Descriptor instead.
func (*SyncBlocksV2Request) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_sync_proto_rawDescGZIP(), []int{7}
}

func (x *SyncBlocksV2Request) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SyncBlocksV2Request) GetChainIdentity() *ChainIdentity {
	if x != nil {
		return x.ChainIdentity
	}
	return nil
}

func (x *SyncBlocksV2Request) GetFromHeight() uint64 {
	if x != nil {
		return x.FromHeight
	}
	return 0
}

func (x *SyncBlocksV2Request) GetToHeight() uint64 {
	if x != nil {
		return x.ToHeight
	}
	return 0
}

func (x *SyncBlocksV2Request) GetExpectedParentHash() []byte {
	if x != nil {
		return x.ExpectedParentHash
	}
	return nil
}

func (x *SyncBlocksV2Request) GetMaxResponseSize() uint32 {
	if x != nil {
		return x.MaxResponseSize
	}
	return 0
}

// SyncBlocksV2Response：返回 blocks + next_height，并可携带关系/祖先信息用于错误归因。
type SyncBlocksV2Response struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	RequestId    string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success      bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage *string                `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	Blocks       []*block.Block         `protobuf:"bytes,10,rep,name=blocks,proto3" json:"blocks,omitempty"`
	NextHeight   uint64                 `protobuf:"varint,11,opt,name=next_height,json=nextHeight,proto3" json:"next_height,omitempty"`
	HasMore      bool                   `protobuf:"varint,12,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	ActualSize   uint32                 `protobuf:"varint,13,opt,name=actual_size,json=actualSize,proto3" json:"actual_size,omitempty"`
	// 若服务端发现分叉或无法线性返回，可回传关系与祖先信息
	Relationship         SyncRelationship `protobuf:"varint,20,opt,name=relationship,proto3,enum=pb.network.protocol.SyncRelationship" json:"relationship,omitempty"`
	RemoteTipHeight      uint64           `protobuf:"varint,21,opt,name=remote_tip_height,json=remoteTipHeight,proto3" json:"remote_tip_height,omitempty"`
	RemoteTipHash        []byte           `protobuf:"bytes,22,opt,name=remote_tip_hash,json=remoteTipHash,proto3" json:"remote_tip_hash,omitempty"`
	CommonAncestorHeight uint64           `protobuf:"varint,23,opt,name=common_ancestor_height,json=commonAncestorHeight,proto3" json:"common_ancestor_height,omitempty"`
	CommonAncestorHash   []byte           `protobuf:"bytes,24,opt,name=common_ancestor_hash,json=commonAncestorHash,proto3" json:"common_ancestor_hash,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SyncBlocksV2Response) Reset() {
	*x = SyncBlocksV2Response{}
	mi := &file_pb_network_protocol_sync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncBlocksV2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncBlocksV2Response) ProtoMessage() {}

func (x *SyncBlocksV2Response) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_sync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncBlocksV2Response.ProtoReflect.Descriptor instead.
func (*SyncBlocksV2Response) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_sync_proto_rawDescGZIP(), []int{8}
}

func (x *SyncBlocksV2Response) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SyncBlocksV2Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncBlocksV2Response) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *SyncBlocksV2Response) GetBlocks() []*block.Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *SyncBlocksV2Response) GetNextHeight() uint64 {
	if x != nil {
		return x.NextHeight
	}
	return 0
}

func (x *SyncBlocksV2Response) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *SyncBlocksV2Response) GetActualSize() uint32 {
	if x != nil {
		return x.ActualSize
	}
	return 0
}

func (x *SyncBlocksV2Response) GetRelationship() SyncRelationship {
	if x != nil {
		return x.Relationship
	}
	return SyncRelationship_SYNC_RELATIONSHIP_UNSPECIFIED
}

func (x *SyncBlocksV2Response) GetRemoteTipHeight() uint64 {
	if x != nil {
		return x.RemoteTipHeight
	}
	return 0
}

func (x *SyncBlocksV2Response) GetRemoteTipHash() []byte {
	if x != nil {
		return x.RemoteTipHash
	}
	return nil
}

func (x *SyncBlocksV2Response) GetCommonAncestorHeight() uint64 {
	if x != nil {
		return x.CommonAncestorHeight
	}
	return 0
}

func (x *SyncBlocksV2Response) GetCommonAncestorHash() []byte {
	if x != nil {
		return x.CommonAncestorHash
	}
	return nil
}

var File_pb_network_protocol_sync_proto protoreflect.FileDescriptor

const file_pb_network_protocol_sync_proto_rawDesc = "" +
	"\n" +
	"\x1epb/network/protocol/sync.proto\x12\x13pb.network.protocol\x1a\x1fpb/blockchain/block/block.proto\"\xd9\x01\n" +
	"\rChainIdentity\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x12+\n" +
	"\x11network_namespace\x18\x02 \x01(\tR\x10networkNamespace\x12\x1d\n" +
	"\n" +
	"network_id\x18\x03 \x01(\tR\tnetworkId\x12\x1d\n" +
	"\n" +
	"chain_mode\x18\x04 \x01(\tR\tchainMode\x12!\n" +
	"\fgenesis_hash\x18\x05 \x01(\tR\vgenesisHash\x12\x1f\n" +
	"\vversion_tag\x18\x06 \x01(\tR\n" +
	"versionTag\"\xd6\x02\n" +
	"\x12KBucketSyncRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12!\n" +
	"\flocal_height\x18\x02 \x01(\x04R\vlocalHeight\x12\x1f\n" +
	"\vrouting_key\x18\x03 \x01(\fR\n" +
	"routingKey\x12*\n" +
	"\x11max_response_size\x18\x04 \x01(\rR\x0fmaxResponseSize\x12*\n" +
	"\x11requester_peer_id\x18\x05 \x01(\fR\x0frequesterPeerId\x12(\n" +
	"\rtarget_height\x18\v \x01(\x04H\x00R\ftargetHeight\x88\x01\x01\x12I\n" +
	"\x0echain_identity\x18\f \x01(\v2\".pb.network.protocol.ChainIdentityR\rchainIdentityB\x10\n" +
	"\x0e_target_height\"\xb4\x03\n" +
	"\x1dIntelligentPaginationResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x121\n" +
	"\x06blocks\x18\x02 \x03(\v2\x19.pb.blockchain.core.BlockR\x06blocks\x12\x1f\n" +
	"\vnext_height\x18\x03 \x01(\x04R\n" +
	"nextHeight\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\x12\x1f\n" +
	"\vactual_size\x18\x05 \x01(\rR\n" +
	"actualSize\x12+\n" +
	"\x11pagination_reason\x18\x06 \x01(\tR\x10paginationReason\x12\x18\n" +
	"\asuccess\x18\x1e \x01(\bR\asuccess\x12(\n" +
	"\rerror_message\x18\x1f \x01(\tH\x00R\ferrorMessage\x88\x01\x01\x12N\n" +
	"\x0echain_identity\x18  \x01(\v2\".pb.network.protocol.ChainIdentityH\x01R\rchainIdentity\x88\x01\x01B\x10\n" +
	"\x0e_error_messageB\x11\n" +
	"\x0f_chain_identity\"J\n" +
	"\x11BlockLocatorEntry\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x02 \x01(\fR\tblockHash\"P\n" +
	"\fBlockLocator\x12@\n" +
	"\aentries\x18\x01 \x03(\v2&.pb.network.protocol.BlockLocatorEntryR\aentries\"\xb7\x02\n" +
	"\x12SyncHelloV2Request\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12I\n" +
	"\x0echain_identity\x18\x02 \x01(\v2\".pb.network.protocol.ChainIdentityR\rchainIdentity\x12(\n" +
	"\x10local_tip_height\x18\n" +
	" \x01(\x04R\x0elocalTipHeight\x12$\n" +
	"\x0elocal_tip_hash\x18\v \x01(\fR\flocalTipHash\x12;\n" +
	"\alocator\x18\x14 \x01(\v2!.pb.network.protocol.BlockLocatorR\alocator\x12*\n" +
	"\x11max_response_size\x18\x1e \x01(\rR\x0fmaxResponseSize\"\xb4\x04\n" +
	"\x13SyncHelloV2Response\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12(\n" +
	"\rerror_message\x18\x03 \x01(\tH\x00R\ferrorMessage\x88\x01\x01\x12N\n" +
	"\x0echain_identity\x18\x04 \x01(\v2\".pb.network.protocol.ChainIdentityH\x01R\rchainIdentity\x88\x01\x01\x12*\n" +
	"\x11remote_tip_height\x18\n" +
	" \x01(\x04R\x0fremoteTipHeight\x12&\n" +
	"\x0fremote_tip_hash\x18\v \x01(\fR\rremoteTipHash\x12I\n" +
	"\frelationship\x18\x14 \x01(\x0e2%.pb.network.protocol.SyncRelationshipR\frelationship\x124\n" +
	"\x16common_ancestor_height\x18\x1e \x01(\x04R\x14commonAncestorHeight\x120\n" +
	"\x14common_ancestor_hash\x18\x1f \x01(\fR\x12commonAncestorHash\x12+\n" +
	"\x0erecommendation\x18( \x01(\tH\x02R\x0erecommendation\x88\x01\x01B\x10\n" +
	"\x0e_error_messageB\x11\n" +
	"\x0f_chain_identityB\x11\n" +
	"\x0f_recommendation\"\xb9\x02\n" +
	"\x13SyncBlocksV2Request\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12I\n" +
	"\x0echain_identity\x18\x02 \x01(\v2\".pb.network.protocol.ChainIdentityR\rchainIdentity\x12\x1f\n" +
	"\vfrom_height\x18\n" +
	" \x01(\x04R\n" +
	"fromHeight\x12\x1b\n" +
	"\tto_height\x18\v \x01(\x04R\btoHeight\x125\n" +
	"\x14expected_parent_hash\x18\x14 \x01(\fH\x00R\x12expectedParentHash\x88\x01\x01\x12*\n" +
	"\x11max_response_size\x18\x1e \x01(\rR\x0fmaxResponseSizeB\x17\n" +
	"\x15_expected_parent_hash\"\xa2\x04\n" +
	"\x14SyncBlocksV2Response\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12(\n" +
	"\rerror_message\x18\x03 \x01(\tH\x00R\ferrorMessage\x88\x01\x01\x121\n" +
	"\x06blocks\x18\n" +
	" \x03(\v2\x19.pb.blockchain.core.BlockR\x06blocks\x12\x1f\n" +
	"\vnext_height\x18\v \x01(\x04R\n" +
	"nextHeight\x12\x19\n" +
	"\bhas_more\x18\f \x01(\bR\ahasMore\x12\x1f\n" +
	"\vactual_size\x18\r \x01(\rR\n" +
	"actualSize\x12I\n" +
	"\frelationship\x18\x14 \x01(\x0e2%.pb.network.protocol.SyncRelationshipR\frelationship\x12*\n" +
	"\x11remote_tip_height\x18\x15 \x01(\x04R\x0fremoteTipHeight\x12&\n" +
	"\x0fremote_tip_hash\x18\x16 \x01(\fR\rremoteTipHash\x124\n" +
	"\x16common_ancestor_height\x18\x17 \x01(\x04R\x14commonAncestorHeight\x120\n" +
	"\x14common_ancestor_hash\x18\x18 \x01(\fR\x12commonAncestorHashB\x10\n" +
	"\x0e_error_message*\x95\x01\n" +
	"\x10SyncRelationship\x12!\n" +
	"\x1dSYNC_RELATIONSHIP_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"UP_TO_DATE\x10\x01\x12\x11\n" +
	"\rREMOTE_BEHIND\x10\x02\x12\x1b\n" +
	"\x17REMOTE_AHEAD_SAME_CHAIN\x10\x03\x12\x11\n" +
	"\rFORK_DETECTED\x10\x04\x12\v\n" +
	"\aUNKNOWN\x10\x05B*Z(github.com/weisyn/v1/pb/network/protocolb\x06proto3"

var (
	file_pb_network_protocol_sync_proto_rawDescOnce sync.Once
	file_pb_network_protocol_sync_proto_rawDescData []byte
)

func file_pb_network_protocol_sync_proto_rawDescGZIP() []byte {
	file_pb_network_protocol_sync_proto_rawDescOnce.Do(func() {
		file_pb_network_protocol_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_network_protocol_sync_proto_rawDesc), len(file_pb_network_protocol_sync_proto_rawDesc)))
	})
	return file_pb_network_protocol_sync_proto_rawDescData
}

var file_pb_network_protocol_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_network_protocol_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pb_network_protocol_sync_proto_goTypes = []any{
	(SyncRelationship)(0),                 // 0: pb.network.protocol.SyncRelationship
	(*ChainIdentity)(nil),                 // 1: pb.network.protocol.ChainIdentity
	(*KBucketSyncRequest)(nil),            // 2: pb.network.protocol.KBucketSyncRequest
	(*IntelligentPaginationResponse)(nil), // 3: pb.network.protocol.IntelligentPaginationResponse
	(*BlockLocatorEntry)(nil),             // 4: pb.network.protocol.BlockLocatorEntry
	(*BlockLocator)(nil),                  // 5: pb.network.protocol.BlockLocator
	(*SyncHelloV2Request)(nil),            // 6: pb.network.protocol.SyncHelloV2Request
	(*SyncHelloV2Response)(nil),           // 7: pb.network.protocol.SyncHelloV2Response
	(*SyncBlocksV2Request)(nil),           // 8: pb.network.protocol.SyncBlocksV2Request
	(*SyncBlocksV2Response)(nil),          // 9: pb.network.protocol.SyncBlocksV2Response
	(*block.Block)(nil),                   // 10: pb.blockchain.core.Block
}
var file_pb_network_protocol_sync_proto_depIdxs = []int32{
	1,  // 0: pb.network.protocol.KBucketSyncRequest.chain_identity:type_name -> pb.network.protocol.ChainIdentity
	10, // 1: pb.network.protocol.IntelligentPaginationResponse.blocks:type_name -> pb.blockchain.core.Block
	1,  // 2: pb.network.protocol.IntelligentPaginationResponse.chain_identity:type_name -> pb.network.protocol.ChainIdentity
	4,  // 3: pb.network.protocol.BlockLocator.entries:type_name -> pb.network.protocol.BlockLocatorEntry
	1,  // 4: pb.network.protocol.SyncHelloV2Request.chain_identity:type_name -> pb.network.protocol.ChainIdentity
	5,  // 5: pb.network.protocol.SyncHelloV2Request.locator:type_name -> pb.network.protocol.BlockLocator
	1,  // 6: pb.network.protocol.SyncHelloV2Response.chain_identity:type_name -> pb.network.protocol.ChainIdentity
	0,  // 7: pb.network.protocol.SyncHelloV2Response.relationship:type_name -> pb.network.protocol.SyncRelationship
	1,  // 8: pb.network.protocol.SyncBlocksV2Request.chain_identity:type_name -> pb.network.protocol.ChainIdentity
	10, // 9: pb.network.protocol.SyncBlocksV2Response.blocks:type_name -> pb.blockchain.core.Block
	0,  // 10: pb.network.protocol.SyncBlocksV2Response.relationship:type_name -> pb.network.protocol.SyncRelationship
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pb_network_protocol_sync_proto_init() }
func file_pb_network_protocol_sync_proto_init() {
	if File_pb_network_protocol_sync_proto != nil {
		return
	}
	file_pb_network_protocol_sync_proto_msgTypes[1].OneofWrappers = []any{}
	file_pb_network_protocol_sync_proto_msgTypes[2].OneofWrappers = []any{}
	file_pb_network_protocol_sync_proto_msgTypes[6].OneofWrappers = []any{}
	file_pb_network_protocol_sync_proto_msgTypes[7].OneofWrappers = []any{}
	file_pb_network_protocol_sync_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_network_protocol_sync_proto_rawDesc), len(file_pb_network_protocol_sync_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_network_protocol_sync_proto_goTypes,
		DependencyIndexes: file_pb_network_protocol_sync_proto_depIdxs,
		EnumInfos:         file_pb_network_protocol_sync_proto_enumTypes,
		MessageInfos:      file_pb_network_protocol_sync_proto_msgTypes,
	}.Build()
	File_pb_network_protocol_sync_proto = out.File
	file_pb_network_protocol_sync_proto_goTypes = nil
	file_pb_network_protocol_sync_proto_depIdxs = nil
}
