// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: pb/network/protocol/test_network_management.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ResetStatus 重置状态枚举
type ResetStatus int32

const (
	ResetStatus_RESET_STATUS_UNKNOWN     ResetStatus = 0 // 未知状态
	ResetStatus_RESET_STATUS_ACCEPTED    ResetStatus = 1 // 已接受重置请求
	ResetStatus_RESET_STATUS_IN_PROGRESS ResetStatus = 2 // 重置进行中
	ResetStatus_RESET_STATUS_COMPLETED   ResetStatus = 3 // 重置完成
	ResetStatus_RESET_STATUS_FAILED      ResetStatus = 4 // 重置失败
	ResetStatus_RESET_STATUS_REJECTED    ResetStatus = 5 // 重置被拒绝
	ResetStatus_RESET_STATUS_TIMEOUT     ResetStatus = 6 // 重置超时
)

// Enum value maps for ResetStatus.
var (
	ResetStatus_name = map[int32]string{
		0: "RESET_STATUS_UNKNOWN",
		1: "RESET_STATUS_ACCEPTED",
		2: "RESET_STATUS_IN_PROGRESS",
		3: "RESET_STATUS_COMPLETED",
		4: "RESET_STATUS_FAILED",
		5: "RESET_STATUS_REJECTED",
		6: "RESET_STATUS_TIMEOUT",
	}
	ResetStatus_value = map[string]int32{
		"RESET_STATUS_UNKNOWN":     0,
		"RESET_STATUS_ACCEPTED":    1,
		"RESET_STATUS_IN_PROGRESS": 2,
		"RESET_STATUS_COMPLETED":   3,
		"RESET_STATUS_FAILED":      4,
		"RESET_STATUS_REJECTED":    5,
		"RESET_STATUS_TIMEOUT":     6,
	}
)

func (x ResetStatus) Enum() *ResetStatus {
	p := new(ResetStatus)
	*p = x
	return p
}

func (x ResetStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResetStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_network_protocol_test_network_management_proto_enumTypes[0].Descriptor()
}

func (ResetStatus) Type() protoreflect.EnumType {
	return &file_pb_network_protocol_test_network_management_proto_enumTypes[0]
}

func (x ResetStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResetStatus.Descriptor instead.
func (ResetStatus) EnumDescriptor() ([]byte, []int) {
	return file_pb_network_protocol_test_network_management_proto_rawDescGZIP(), []int{0}
}

// NodeHealthStatus 节点健康状态枚举
type NodeHealthStatus int32

const (
	NodeHealthStatus_HEALTH_STATUS_UNKNOWN  NodeHealthStatus = 0 // 未知状态
	NodeHealthStatus_HEALTH_STATUS_HEALTHY  NodeHealthStatus = 1 // 健康
	NodeHealthStatus_HEALTH_STATUS_WARNING  NodeHealthStatus = 2 // 有警告
	NodeHealthStatus_HEALTH_STATUS_ERROR    NodeHealthStatus = 3 // 有错误
	NodeHealthStatus_HEALTH_STATUS_CRITICAL NodeHealthStatus = 4 // 严重问题
	NodeHealthStatus_HEALTH_STATUS_OFFLINE  NodeHealthStatus = 5 // 离线
)

// Enum value maps for NodeHealthStatus.
var (
	NodeHealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNKNOWN",
		1: "HEALTH_STATUS_HEALTHY",
		2: "HEALTH_STATUS_WARNING",
		3: "HEALTH_STATUS_ERROR",
		4: "HEALTH_STATUS_CRITICAL",
		5: "HEALTH_STATUS_OFFLINE",
	}
	NodeHealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNKNOWN":  0,
		"HEALTH_STATUS_HEALTHY":  1,
		"HEALTH_STATUS_WARNING":  2,
		"HEALTH_STATUS_ERROR":    3,
		"HEALTH_STATUS_CRITICAL": 4,
		"HEALTH_STATUS_OFFLINE":  5,
	}
)

func (x NodeHealthStatus) Enum() *NodeHealthStatus {
	p := new(NodeHealthStatus)
	*p = x
	return p
}

func (x NodeHealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeHealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_network_protocol_test_network_management_proto_enumTypes[1].Descriptor()
}

func (NodeHealthStatus) Type() protoreflect.EnumType {
	return &file_pb_network_protocol_test_network_management_proto_enumTypes[1]
}

func (x NodeHealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeHealthStatus.Descriptor instead.
func (NodeHealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_pb_network_protocol_test_network_management_proto_rawDescGZIP(), []int{1}
}

// SessionMessageType 会话消息类型
type SessionMessageType int32

const (
	SessionMessageType_SESSION_MESSAGE_UNKNOWN SessionMessageType = 0 // 未知消息
	SessionMessageType_SESSION_MESSAGE_START   SessionMessageType = 1 // 启动会话
	SessionMessageType_SESSION_MESSAGE_JOIN    SessionMessageType = 2 // 加入会话
	SessionMessageType_SESSION_MESSAGE_STATUS  SessionMessageType = 3 // 状态更新
	SessionMessageType_SESSION_MESSAGE_END     SessionMessageType = 4 // 结束会话
	SessionMessageType_SESSION_MESSAGE_SYNC    SessionMessageType = 5 // 同步请求
)

// Enum value maps for SessionMessageType.
var (
	SessionMessageType_name = map[int32]string{
		0: "SESSION_MESSAGE_UNKNOWN",
		1: "SESSION_MESSAGE_START",
		2: "SESSION_MESSAGE_JOIN",
		3: "SESSION_MESSAGE_STATUS",
		4: "SESSION_MESSAGE_END",
		5: "SESSION_MESSAGE_SYNC",
	}
	SessionMessageType_value = map[string]int32{
		"SESSION_MESSAGE_UNKNOWN": 0,
		"SESSION_MESSAGE_START":   1,
		"SESSION_MESSAGE_JOIN":    2,
		"SESSION_MESSAGE_STATUS":  3,
		"SESSION_MESSAGE_END":     4,
		"SESSION_MESSAGE_SYNC":    5,
	}
)

func (x SessionMessageType) Enum() *SessionMessageType {
	p := new(SessionMessageType)
	*p = x
	return p
}

func (x SessionMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_network_protocol_test_network_management_proto_enumTypes[2].Descriptor()
}

func (SessionMessageType) Type() protoreflect.EnumType {
	return &file_pb_network_protocol_test_network_management_proto_enumTypes[2]
}

func (x SessionMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionMessageType.Descriptor instead.
func (SessionMessageType) EnumDescriptor() ([]byte, []int) {
	return file_pb_network_protocol_test_network_management_proto_rawDescGZIP(), []int{2}
}

// SessionStatus 会话状态枚举
type SessionStatus int32

const (
	SessionStatus_SESSION_STATUS_UNKNOWN   SessionStatus = 0 // 未知状态
	SessionStatus_SESSION_STATUS_STARTING  SessionStatus = 1 // 启动中
	SessionStatus_SESSION_STATUS_ACTIVE    SessionStatus = 2 // 活跃中
	SessionStatus_SESSION_STATUS_PAUSED    SessionStatus = 3 // 已暂停
	SessionStatus_SESSION_STATUS_ENDING    SessionStatus = 4 // 结束中
	SessionStatus_SESSION_STATUS_COMPLETED SessionStatus = 5 // 已完成
	SessionStatus_SESSION_STATUS_FAILED    SessionStatus = 6 // 失败
)

// Enum value maps for SessionStatus.
var (
	SessionStatus_name = map[int32]string{
		0: "SESSION_STATUS_UNKNOWN",
		1: "SESSION_STATUS_STARTING",
		2: "SESSION_STATUS_ACTIVE",
		3: "SESSION_STATUS_PAUSED",
		4: "SESSION_STATUS_ENDING",
		5: "SESSION_STATUS_COMPLETED",
		6: "SESSION_STATUS_FAILED",
	}
	SessionStatus_value = map[string]int32{
		"SESSION_STATUS_UNKNOWN":   0,
		"SESSION_STATUS_STARTING":  1,
		"SESSION_STATUS_ACTIVE":    2,
		"SESSION_STATUS_PAUSED":    3,
		"SESSION_STATUS_ENDING":    4,
		"SESSION_STATUS_COMPLETED": 5,
		"SESSION_STATUS_FAILED":    6,
	}
)

func (x SessionStatus) Enum() *SessionStatus {
	p := new(SessionStatus)
	*p = x
	return p
}

func (x SessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_network_protocol_test_network_management_proto_enumTypes[3].Descriptor()
}

func (SessionStatus) Type() protoreflect.EnumType {
	return &file_pb_network_protocol_test_network_management_proto_enumTypes[3]
}

func (x SessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionStatus.Descriptor instead.
func (SessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_pb_network_protocol_test_network_management_proto_rawDescGZIP(), []int{3}
}

// HealthCheckType 健康检查类型
type HealthCheckType int32

const (
	HealthCheckType_HEALTH_CHECK_UNKNOWN     HealthCheckType = 0 // 未知检查
	HealthCheckType_HEALTH_CHECK_NETWORK     HealthCheckType = 1 // 网络连接检查
	HealthCheckType_HEALTH_CHECK_BLOCKCHAIN  HealthCheckType = 2 // 区块链状态检查
	HealthCheckType_HEALTH_CHECK_STORAGE     HealthCheckType = 3 // 存储状态检查
	HealthCheckType_HEALTH_CHECK_PERFORMANCE HealthCheckType = 4 // 性能指标检查
	HealthCheckType_HEALTH_CHECK_CONSENSUS   HealthCheckType = 5 // 共识状态检查
)

// Enum value maps for HealthCheckType.
var (
	HealthCheckType_name = map[int32]string{
		0: "HEALTH_CHECK_UNKNOWN",
		1: "HEALTH_CHECK_NETWORK",
		2: "HEALTH_CHECK_BLOCKCHAIN",
		3: "HEALTH_CHECK_STORAGE",
		4: "HEALTH_CHECK_PERFORMANCE",
		5: "HEALTH_CHECK_CONSENSUS",
	}
	HealthCheckType_value = map[string]int32{
		"HEALTH_CHECK_UNKNOWN":     0,
		"HEALTH_CHECK_NETWORK":     1,
		"HEALTH_CHECK_BLOCKCHAIN":  2,
		"HEALTH_CHECK_STORAGE":     3,
		"HEALTH_CHECK_PERFORMANCE": 4,
		"HEALTH_CHECK_CONSENSUS":   5,
	}
)

func (x HealthCheckType) Enum() *HealthCheckType {
	p := new(HealthCheckType)
	*p = x
	return p
}

func (x HealthCheckType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_network_protocol_test_network_management_proto_enumTypes[4].Descriptor()
}

func (HealthCheckType) Type() protoreflect.EnumType {
	return &file_pb_network_protocol_test_network_management_proto_enumTypes[4]
}

func (x HealthCheckType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckType.Descriptor instead.
func (HealthCheckType) EnumDescriptor() ([]byte, []int) {
	return file_pb_network_protocol_test_network_management_proto_rawDescGZIP(), []int{4}
}

// TestNetworkResetMessage 测试网络重置消息
// 用于协调全网节点执行数据清理和重置操作
type TestNetworkResetMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 重置标识和基本信息
	ResetId     string `protobuf:"bytes,1,opt,name=reset_id,json=resetId,proto3" json:"reset_id,omitempty"`              // 唯一重置标识符（如：reset-20241201-001）
	ResetHeight uint64 `protobuf:"varint,2,opt,name=reset_height,json=resetHeight,proto3" json:"reset_height,omitempty"` // 重置到的区块高度（0=完全重置）
	ResetReason string `protobuf:"bytes,3,opt,name=reset_reason,json=resetReason,proto3" json:"reset_reason,omitempty"`  // 重置原因描述
	Timestamp   uint64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                        // 重置时间戳（Unix时间）
	// 重置选项和控制
	ForceReset        bool     `protobuf:"varint,5,opt,name=force_reset,json=forceReset,proto3" json:"force_reset,omitempty"`                        // 强制重置标志
	KeepConfig        bool     `protobuf:"varint,6,opt,name=keep_config,json=keepConfig,proto3" json:"keep_config,omitempty"`                        // 保留配置文件标志
	BackupBeforeReset bool     `protobuf:"varint,7,opt,name=backup_before_reset,json=backupBeforeReset,proto3" json:"backup_before_reset,omitempty"` // 重置前备份标志
	ExcludePatterns   []string `protobuf:"bytes,8,rep,name=exclude_patterns,json=excludePatterns,proto3" json:"exclude_patterns,omitempty"`          // 排除的数据模式
	// 权限和验证
	SourcePeerId   string `protobuf:"bytes,9,opt,name=source_peer_id,json=sourcePeerId,proto3" json:"source_peer_id,omitempty"`      // 发起重置的节点ID
	AdminSignature []byte `protobuf:"bytes,10,opt,name=admin_signature,json=adminSignature,proto3" json:"admin_signature,omitempty"` // 管理员数字签名
	SessionToken   string `protobuf:"bytes,11,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`       // 会话令牌
	// 协调和同步
	ResetSequence       uint32 `protobuf:"varint,12,opt,name=reset_sequence,json=resetSequence,proto3" json:"reset_sequence,omitempty"`                   // 重置序号（防重放）
	CoordinationTimeout uint64 `protobuf:"varint,13,opt,name=coordination_timeout,json=coordinationTimeout,proto3" json:"coordination_timeout,omitempty"` // 协调超时时间（秒）
	RequireConfirmation bool   `protobuf:"varint,14,opt,name=require_confirmation,json=requireConfirmation,proto3" json:"require_confirmation,omitempty"` // 是否需要确认响应
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TestNetworkResetMessage) Reset() {
	*x = TestNetworkResetMessage{}
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestNetworkResetMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestNetworkResetMessage) ProtoMessage() {}

func (x *TestNetworkResetMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestNetworkResetMessage.ProtoReflect.Descriptor instead.
func (*TestNetworkResetMessage) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_test_network_management_proto_rawDescGZIP(), []int{0}
}

func (x *TestNetworkResetMessage) GetResetId() string {
	if x != nil {
		return x.ResetId
	}
	return ""
}

func (x *TestNetworkResetMessage) GetResetHeight() uint64 {
	if x != nil {
		return x.ResetHeight
	}
	return 0
}

func (x *TestNetworkResetMessage) GetResetReason() string {
	if x != nil {
		return x.ResetReason
	}
	return ""
}

func (x *TestNetworkResetMessage) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TestNetworkResetMessage) GetForceReset() bool {
	if x != nil {
		return x.ForceReset
	}
	return false
}

func (x *TestNetworkResetMessage) GetKeepConfig() bool {
	if x != nil {
		return x.KeepConfig
	}
	return false
}

func (x *TestNetworkResetMessage) GetBackupBeforeReset() bool {
	if x != nil {
		return x.BackupBeforeReset
	}
	return false
}

func (x *TestNetworkResetMessage) GetExcludePatterns() []string {
	if x != nil {
		return x.ExcludePatterns
	}
	return nil
}

func (x *TestNetworkResetMessage) GetSourcePeerId() string {
	if x != nil {
		return x.SourcePeerId
	}
	return ""
}

func (x *TestNetworkResetMessage) GetAdminSignature() []byte {
	if x != nil {
		return x.AdminSignature
	}
	return nil
}

func (x *TestNetworkResetMessage) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *TestNetworkResetMessage) GetResetSequence() uint32 {
	if x != nil {
		return x.ResetSequence
	}
	return 0
}

func (x *TestNetworkResetMessage) GetCoordinationTimeout() uint64 {
	if x != nil {
		return x.CoordinationTimeout
	}
	return 0
}

func (x *TestNetworkResetMessage) GetRequireConfirmation() bool {
	if x != nil {
		return x.RequireConfirmation
	}
	return false
}

// TestNetworkResetResponse 测试网络重置响应
// 节点对重置消息的响应确认
type TestNetworkResetResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ResetId           string                 `protobuf:"bytes,1,opt,name=reset_id,json=resetId,proto3" json:"reset_id,omitempty"`                                // 对应的重置ID
	RespondingPeerId  string                 `protobuf:"bytes,2,opt,name=responding_peer_id,json=respondingPeerId,proto3" json:"responding_peer_id,omitempty"`   // 响应节点ID
	Status            ResetStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=pb.network.protocol.ResetStatus" json:"status,omitempty"`           // 重置状态
	Message           string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                                               // 状态消息
	ResponseTimestamp uint64                 `protobuf:"varint,5,opt,name=response_timestamp,json=responseTimestamp,proto3" json:"response_timestamp,omitempty"` // 响应时间戳
	// 重置结果详情
	ExecutionResult   *ResetExecutionResult `protobuf:"bytes,6,opt,name=execution_result,json=executionResult,proto3" json:"execution_result,omitempty"`          // 执行结果
	CleanupDurationMs uint64                `protobuf:"varint,7,opt,name=cleanup_duration_ms,json=cleanupDurationMs,proto3" json:"cleanup_duration_ms,omitempty"` // 清理耗时（毫秒）
	CleanedPaths      []string              `protobuf:"bytes,8,rep,name=cleaned_paths,json=cleanedPaths,proto3" json:"cleaned_paths,omitempty"`                   // 已清理的路径
	ErrorMessages     []string              `protobuf:"bytes,9,rep,name=error_messages,json=errorMessages,proto3" json:"error_messages,omitempty"`                // 错误信息列表
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TestNetworkResetResponse) Reset() {
	*x = TestNetworkResetResponse{}
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestNetworkResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestNetworkResetResponse) ProtoMessage() {}

func (x *TestNetworkResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestNetworkResetResponse.ProtoReflect.Descriptor instead.
func (*TestNetworkResetResponse) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_test_network_management_proto_rawDescGZIP(), []int{1}
}

func (x *TestNetworkResetResponse) GetResetId() string {
	if x != nil {
		return x.ResetId
	}
	return ""
}

func (x *TestNetworkResetResponse) GetRespondingPeerId() string {
	if x != nil {
		return x.RespondingPeerId
	}
	return ""
}

func (x *TestNetworkResetResponse) GetStatus() ResetStatus {
	if x != nil {
		return x.Status
	}
	return ResetStatus_RESET_STATUS_UNKNOWN
}

func (x *TestNetworkResetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TestNetworkResetResponse) GetResponseTimestamp() uint64 {
	if x != nil {
		return x.ResponseTimestamp
	}
	return 0
}

func (x *TestNetworkResetResponse) GetExecutionResult() *ResetExecutionResult {
	if x != nil {
		return x.ExecutionResult
	}
	return nil
}

func (x *TestNetworkResetResponse) GetCleanupDurationMs() uint64 {
	if x != nil {
		return x.CleanupDurationMs
	}
	return 0
}

func (x *TestNetworkResetResponse) GetCleanedPaths() []string {
	if x != nil {
		return x.CleanedPaths
	}
	return nil
}

func (x *TestNetworkResetResponse) GetErrorMessages() []string {
	if x != nil {
		return x.ErrorMessages
	}
	return nil
}

// ResetExecutionResult 重置执行结果
type ResetExecutionResult struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Success            bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                                 // 是否成功
	BlocksRemoved      uint64                 `protobuf:"varint,2,opt,name=blocks_removed,json=blocksRemoved,proto3" json:"blocks_removed,omitempty"`                // 删除的区块数
	DataSizeFreed      uint64                 `protobuf:"varint,3,opt,name=data_size_freed,json=dataSizeFreed,proto3" json:"data_size_freed,omitempty"`              // 释放的数据大小（字节）
	BackupPath         string                 `protobuf:"bytes,4,opt,name=backup_path,json=backupPath,proto3" json:"backup_path,omitempty"`                          // 备份路径（如果创建了备份）
	NetworkReconnected bool                   `protobuf:"varint,5,opt,name=network_reconnected,json=networkReconnected,proto3" json:"network_reconnected,omitempty"` // 是否重新连接网络
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ResetExecutionResult) Reset() {
	*x = ResetExecutionResult{}
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetExecutionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetExecutionResult) ProtoMessage() {}

func (x *ResetExecutionResult) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetExecutionResult.ProtoReflect.Descriptor instead.
func (*ResetExecutionResult) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_test_network_management_proto_rawDescGZIP(), []int{2}
}

func (x *ResetExecutionResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResetExecutionResult) GetBlocksRemoved() uint64 {
	if x != nil {
		return x.BlocksRemoved
	}
	return 0
}

func (x *ResetExecutionResult) GetDataSizeFreed() uint64 {
	if x != nil {
		return x.DataSizeFreed
	}
	return 0
}

func (x *ResetExecutionResult) GetBackupPath() string {
	if x != nil {
		return x.BackupPath
	}
	return ""
}

func (x *ResetExecutionResult) GetNetworkReconnected() bool {
	if x != nil {
		return x.NetworkReconnected
	}
	return false
}

// NetworkConsistencyCheckRequest 网络一致性检查请求
type NetworkConsistencyCheckRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CheckId            string                 `protobuf:"bytes,1,opt,name=check_id,json=checkId,proto3" json:"check_id,omitempty"`                                     // 检查ID
	RequesterPeerId    string                 `protobuf:"bytes,2,opt,name=requester_peer_id,json=requesterPeerId,proto3" json:"requester_peer_id,omitempty"`           // 请求者节点ID
	CheckDepth         uint32                 `protobuf:"varint,3,opt,name=check_depth,json=checkDepth,proto3" json:"check_depth,omitempty"`                           // 检查深度（区块数）
	BaseHeight         uint64                 `protobuf:"varint,4,opt,name=base_height,json=baseHeight,proto3" json:"base_height,omitempty"`                           // 基准高度
	TargetPeerIds      []string               `protobuf:"bytes,5,rep,name=target_peer_ids,json=targetPeerIds,proto3" json:"target_peer_ids,omitempty"`                 // 目标检查节点（空=所有节点）
	CheckTimeout       uint64                 `protobuf:"varint,6,opt,name=check_timeout,json=checkTimeout,proto3" json:"check_timeout,omitempty"`                     // 检查超时时间
	IncludeBlockHashes bool                   `protobuf:"varint,7,opt,name=include_block_hashes,json=includeBlockHashes,proto3" json:"include_block_hashes,omitempty"` // 是否包含区块哈希
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NetworkConsistencyCheckRequest) Reset() {
	*x = NetworkConsistencyCheckRequest{}
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConsistencyCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConsistencyCheckRequest) ProtoMessage() {}

func (x *NetworkConsistencyCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConsistencyCheckRequest.ProtoReflect.Descriptor instead.
func (*NetworkConsistencyCheckRequest) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_test_network_management_proto_rawDescGZIP(), []int{3}
}

func (x *NetworkConsistencyCheckRequest) GetCheckId() string {
	if x != nil {
		return x.CheckId
	}
	return ""
}

func (x *NetworkConsistencyCheckRequest) GetRequesterPeerId() string {
	if x != nil {
		return x.RequesterPeerId
	}
	return ""
}

func (x *NetworkConsistencyCheckRequest) GetCheckDepth() uint32 {
	if x != nil {
		return x.CheckDepth
	}
	return 0
}

func (x *NetworkConsistencyCheckRequest) GetBaseHeight() uint64 {
	if x != nil {
		return x.BaseHeight
	}
	return 0
}

func (x *NetworkConsistencyCheckRequest) GetTargetPeerIds() []string {
	if x != nil {
		return x.TargetPeerIds
	}
	return nil
}

func (x *NetworkConsistencyCheckRequest) GetCheckTimeout() uint64 {
	if x != nil {
		return x.CheckTimeout
	}
	return 0
}

func (x *NetworkConsistencyCheckRequest) GetIncludeBlockHashes() bool {
	if x != nil {
		return x.IncludeBlockHashes
	}
	return false
}

// NetworkConsistencyCheckResponse 网络一致性检查响应
type NetworkConsistencyCheckResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CheckId           string                 `protobuf:"bytes,1,opt,name=check_id,json=checkId,proto3" json:"check_id,omitempty"`                                // 对应的检查ID
	RespondingPeerId  string                 `protobuf:"bytes,2,opt,name=responding_peer_id,json=respondingPeerId,proto3" json:"responding_peer_id,omitempty"`   // 响应节点ID
	NodeState         *NodeConsistencyState  `protobuf:"bytes,3,opt,name=node_state,json=nodeState,proto3" json:"node_state,omitempty"`                          // 节点状态
	ResponseTimestamp uint64                 `protobuf:"varint,4,opt,name=response_timestamp,json=responseTimestamp,proto3" json:"response_timestamp,omitempty"` // 响应时间戳
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NetworkConsistencyCheckResponse) Reset() {
	*x = NetworkConsistencyCheckResponse{}
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConsistencyCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConsistencyCheckResponse) ProtoMessage() {}

func (x *NetworkConsistencyCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConsistencyCheckResponse.ProtoReflect.Descriptor instead.
func (*NetworkConsistencyCheckResponse) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_test_network_management_proto_rawDescGZIP(), []int{4}
}

func (x *NetworkConsistencyCheckResponse) GetCheckId() string {
	if x != nil {
		return x.CheckId
	}
	return ""
}

func (x *NetworkConsistencyCheckResponse) GetRespondingPeerId() string {
	if x != nil {
		return x.RespondingPeerId
	}
	return ""
}

func (x *NetworkConsistencyCheckResponse) GetNodeState() *NodeConsistencyState {
	if x != nil {
		return x.NodeState
	}
	return nil
}

func (x *NetworkConsistencyCheckResponse) GetResponseTimestamp() uint64 {
	if x != nil {
		return x.ResponseTimestamp
	}
	return 0
}

// NodeConsistencyState 节点一致性状态
type NodeConsistencyState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PeerId          string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`                                                              // 节点ID
	CurrentHeight   uint64                 `protobuf:"varint,2,opt,name=current_height,json=currentHeight,proto3" json:"current_height,omitempty"`                                        // 当前区块高度
	LatestBlockHash string                 `protobuf:"bytes,3,opt,name=latest_block_hash,json=latestBlockHash,proto3" json:"latest_block_hash,omitempty"`                                 // 最新区块哈希
	BlockHashes     []*BlockHashInfo       `protobuf:"bytes,4,rep,name=block_hashes,json=blockHashes,proto3" json:"block_hashes,omitempty"`                                               // 区块哈希列表
	HealthStatus    NodeHealthStatus       `protobuf:"varint,5,opt,name=health_status,json=healthStatus,proto3,enum=pb.network.protocol.NodeHealthStatus" json:"health_status,omitempty"` // 健康状态
	LastUpdateTime  uint64                 `protobuf:"varint,6,opt,name=last_update_time,json=lastUpdateTime,proto3" json:"last_update_time,omitempty"`                                   // 最后更新时间
	Issues          []string               `protobuf:"bytes,7,rep,name=issues,proto3" json:"issues,omitempty"`                                                                            // 发现的问题
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeConsistencyState) Reset() {
	*x = NodeConsistencyState{}
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeConsistencyState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeConsistencyState) ProtoMessage() {}

func (x *NodeConsistencyState) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeConsistencyState.ProtoReflect.Descriptor instead.
func (*NodeConsistencyState) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_test_network_management_proto_rawDescGZIP(), []int{5}
}

func (x *NodeConsistencyState) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *NodeConsistencyState) GetCurrentHeight() uint64 {
	if x != nil {
		return x.CurrentHeight
	}
	return 0
}

func (x *NodeConsistencyState) GetLatestBlockHash() string {
	if x != nil {
		return x.LatestBlockHash
	}
	return ""
}

func (x *NodeConsistencyState) GetBlockHashes() []*BlockHashInfo {
	if x != nil {
		return x.BlockHashes
	}
	return nil
}

func (x *NodeConsistencyState) GetHealthStatus() NodeHealthStatus {
	if x != nil {
		return x.HealthStatus
	}
	return NodeHealthStatus_HEALTH_STATUS_UNKNOWN
}

func (x *NodeConsistencyState) GetLastUpdateTime() uint64 {
	if x != nil {
		return x.LastUpdateTime
	}
	return 0
}

func (x *NodeConsistencyState) GetIssues() []string {
	if x != nil {
		return x.Issues
	}
	return nil
}

// BlockHashInfo 区块哈希信息
type BlockHashInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Height           uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`                                             // 区块高度
	BlockHash        string                 `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`                       // 区块哈希
	Timestamp        uint64                 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                       // 区块时间戳
	TransactionCount uint32                 `protobuf:"varint,4,opt,name=transaction_count,json=transactionCount,proto3" json:"transaction_count,omitempty"` // 交易数量
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BlockHashInfo) Reset() {
	*x = BlockHashInfo{}
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockHashInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHashInfo) ProtoMessage() {}

func (x *BlockHashInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHashInfo.ProtoReflect.Descriptor instead.
func (*BlockHashInfo) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_test_network_management_proto_rawDescGZIP(), []int{6}
}

func (x *BlockHashInfo) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlockHashInfo) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *BlockHashInfo) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BlockHashInfo) GetTransactionCount() uint32 {
	if x != nil {
		return x.TransactionCount
	}
	return 0
}

// TestSessionMessage 测试会话消息
// 用于管理独立的测试会话和状态同步
type TestSessionMessage struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	MessageType  SessionMessageType     `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=pb.network.protocol.SessionMessageType" json:"message_type,omitempty"` // 消息类型
	SessionId    string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                                                    // 会话ID
	SourcePeerId string                 `protobuf:"bytes,3,opt,name=source_peer_id,json=sourcePeerId,proto3" json:"source_peer_id,omitempty"`                                         // 源节点ID
	Timestamp    uint64                 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                    // 时间戳
	// Types that are valid to be assigned to Content:
	//
	//	*TestSessionMessage_SessionStart
	//	*TestSessionMessage_SessionJoin
	//	*TestSessionMessage_SessionStatus
	//	*TestSessionMessage_SessionEnd
	Content       isTestSessionMessage_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestSessionMessage) Reset() {
	*x = TestSessionMessage{}
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestSessionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestSessionMessage) ProtoMessage() {}

func (x *TestSessionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestSessionMessage.ProtoReflect.Descriptor instead.
func (*TestSessionMessage) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_test_network_management_proto_rawDescGZIP(), []int{7}
}

func (x *TestSessionMessage) GetMessageType() SessionMessageType {
	if x != nil {
		return x.MessageType
	}
	return SessionMessageType_SESSION_MESSAGE_UNKNOWN
}

func (x *TestSessionMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TestSessionMessage) GetSourcePeerId() string {
	if x != nil {
		return x.SourcePeerId
	}
	return ""
}

func (x *TestSessionMessage) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TestSessionMessage) GetContent() isTestSessionMessage_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *TestSessionMessage) GetSessionStart() *SessionStartRequest {
	if x != nil {
		if x, ok := x.Content.(*TestSessionMessage_SessionStart); ok {
			return x.SessionStart
		}
	}
	return nil
}

func (x *TestSessionMessage) GetSessionJoin() *SessionJoinRequest {
	if x != nil {
		if x, ok := x.Content.(*TestSessionMessage_SessionJoin); ok {
			return x.SessionJoin
		}
	}
	return nil
}

func (x *TestSessionMessage) GetSessionStatus() *SessionStatusUpdate {
	if x != nil {
		if x, ok := x.Content.(*TestSessionMessage_SessionStatus); ok {
			return x.SessionStatus
		}
	}
	return nil
}

func (x *TestSessionMessage) GetSessionEnd() *SessionEndNotification {
	if x != nil {
		if x, ok := x.Content.(*TestSessionMessage_SessionEnd); ok {
			return x.SessionEnd
		}
	}
	return nil
}

type isTestSessionMessage_Content interface {
	isTestSessionMessage_Content()
}

type TestSessionMessage_SessionStart struct {
	SessionStart *SessionStartRequest `protobuf:"bytes,5,opt,name=session_start,json=sessionStart,proto3,oneof"` // 会话启动请求
}

type TestSessionMessage_SessionJoin struct {
	SessionJoin *SessionJoinRequest `protobuf:"bytes,6,opt,name=session_join,json=sessionJoin,proto3,oneof"` // 加入会话请求
}

type TestSessionMessage_SessionStatus struct {
	SessionStatus *SessionStatusUpdate `protobuf:"bytes,7,opt,name=session_status,json=sessionStatus,proto3,oneof"` // 会话状态更新
}

type TestSessionMessage_SessionEnd struct {
	SessionEnd *SessionEndNotification `protobuf:"bytes,8,opt,name=session_end,json=sessionEnd,proto3,oneof"` // 会话结束通知
}

func (*TestSessionMessage_SessionStart) isTestSessionMessage_Content() {}

func (*TestSessionMessage_SessionJoin) isTestSessionMessage_Content() {}

func (*TestSessionMessage_SessionStatus) isTestSessionMessage_Content() {}

func (*TestSessionMessage_SessionEnd) isTestSessionMessage_Content() {}

// SessionStartRequest 会话启动请求
type SessionStartRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SessionName        string                 `protobuf:"bytes,1,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`                                                                                 // 会话名称
	Description        string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`                                                                                                    // 会话描述
	CleanBeforeStart   bool                   `protobuf:"varint,3,opt,name=clean_before_start,json=cleanBeforeStart,proto3" json:"clean_before_start,omitempty"`                                                               // 启动前清理
	ParticipantPeerIds []string               `protobuf:"bytes,4,rep,name=participant_peer_ids,json=participantPeerIds,proto3" json:"participant_peer_ids,omitempty"`                                                          // 参与者节点ID
	SessionConfig      map[string]string      `protobuf:"bytes,5,rep,name=session_config,json=sessionConfig,proto3" json:"session_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 会话配置
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SessionStartRequest) Reset() {
	*x = SessionStartRequest{}
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStartRequest) ProtoMessage() {}

func (x *SessionStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStartRequest.ProtoReflect.Descriptor instead.
func (*SessionStartRequest) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_test_network_management_proto_rawDescGZIP(), []int{8}
}

func (x *SessionStartRequest) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

func (x *SessionStartRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SessionStartRequest) GetCleanBeforeStart() bool {
	if x != nil {
		return x.CleanBeforeStart
	}
	return false
}

func (x *SessionStartRequest) GetParticipantPeerIds() []string {
	if x != nil {
		return x.ParticipantPeerIds
	}
	return nil
}

func (x *SessionStartRequest) GetSessionConfig() map[string]string {
	if x != nil {
		return x.SessionConfig
	}
	return nil
}

// SessionJoinRequest 加入会话请求
type SessionJoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`    // 要加入的会话ID
	PeerId        string                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`             // 请求加入的节点ID
	JoinReason    string                 `protobuf:"bytes,3,opt,name=join_reason,json=joinReason,proto3" json:"join_reason,omitempty"` // 加入原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionJoinRequest) Reset() {
	*x = SessionJoinRequest{}
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionJoinRequest) ProtoMessage() {}

func (x *SessionJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionJoinRequest.ProtoReflect.Descriptor instead.
func (*SessionJoinRequest) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_test_network_management_proto_rawDescGZIP(), []int{9}
}

func (x *SessionJoinRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionJoinRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *SessionJoinRequest) GetJoinReason() string {
	if x != nil {
		return x.JoinReason
	}
	return ""
}

// SessionStatusUpdate 会话状态更新
type SessionStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                                                                              // 会话ID
	Status        SessionStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=pb.network.protocol.SessionStatus" json:"status,omitempty"`                                                             // 会话状态
	StatusData    map[string]string      `protobuf:"bytes,3,rep,name=status_data,json=statusData,proto3" json:"status_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 状态数据
	ActivePeers   []string               `protobuf:"bytes,4,rep,name=active_peers,json=activePeers,proto3" json:"active_peers,omitempty"`                                                                        // 活跃节点列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStatusUpdate) Reset() {
	*x = SessionStatusUpdate{}
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStatusUpdate) ProtoMessage() {}

func (x *SessionStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStatusUpdate.ProtoReflect.Descriptor instead.
func (*SessionStatusUpdate) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_test_network_management_proto_rawDescGZIP(), []int{10}
}

func (x *SessionStatusUpdate) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionStatusUpdate) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNKNOWN
}

func (x *SessionStatusUpdate) GetStatusData() map[string]string {
	if x != nil {
		return x.StatusData
	}
	return nil
}

func (x *SessionStatusUpdate) GetActivePeers() []string {
	if x != nil {
		return x.ActivePeers
	}
	return nil
}

// SessionEndNotification 会话结束通知
type SessionEndNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`             // 会话ID
	EndReason     string                 `protobuf:"bytes,2,opt,name=end_reason,json=endReason,proto3" json:"end_reason,omitempty"`             // 结束原因
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`                                 // 是否成功
	SessionReport *SessionReport         `protobuf:"bytes,4,opt,name=session_report,json=sessionReport,proto3" json:"session_report,omitempty"` // 会话报告
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEndNotification) Reset() {
	*x = SessionEndNotification{}
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEndNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEndNotification) ProtoMessage() {}

func (x *SessionEndNotification) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEndNotification.ProtoReflect.Descriptor instead.
func (*SessionEndNotification) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_test_network_management_proto_rawDescGZIP(), []int{11}
}

func (x *SessionEndNotification) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionEndNotification) GetEndReason() string {
	if x != nil {
		return x.EndReason
	}
	return ""
}

func (x *SessionEndNotification) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SessionEndNotification) GetSessionReport() *SessionReport {
	if x != nil {
		return x.SessionReport
	}
	return nil
}

// SessionReport 会话报告
type SessionReport struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                                                      // 会话ID
	StartTime        uint64                 `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`                                                     // 开始时间
	EndTime          uint64                 `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`                                                           // 结束时间
	DurationSeconds  uint64                 `protobuf:"varint,4,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`                                   // 持续时间（秒）
	ParticipantCount uint32                 `protobuf:"varint,5,opt,name=participant_count,json=participantCount,proto3" json:"participant_count,omitempty"`                                // 参与者数量
	Achievements     []string               `protobuf:"bytes,6,rep,name=achievements,proto3" json:"achievements,omitempty"`                                                                 // 完成的任务
	Issues           []string               `protobuf:"bytes,7,rep,name=issues,proto3" json:"issues,omitempty"`                                                                             // 遇到的问题
	Metrics          map[string]string      `protobuf:"bytes,8,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 指标数据
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SessionReport) Reset() {
	*x = SessionReport{}
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionReport) ProtoMessage() {}

func (x *SessionReport) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionReport.ProtoReflect.Descriptor instead.
func (*SessionReport) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_test_network_management_proto_rawDescGZIP(), []int{12}
}

func (x *SessionReport) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionReport) GetStartTime() uint64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *SessionReport) GetEndTime() uint64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *SessionReport) GetDurationSeconds() uint64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *SessionReport) GetParticipantCount() uint32 {
	if x != nil {
		return x.ParticipantCount
	}
	return 0
}

func (x *SessionReport) GetAchievements() []string {
	if x != nil {
		return x.Achievements
	}
	return nil
}

func (x *SessionReport) GetIssues() []string {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *SessionReport) GetMetrics() map[string]string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// NetworkHealthCheckRequest 网络健康检查请求
type NetworkHealthCheckRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CheckId         string                 `protobuf:"bytes,1,opt,name=check_id,json=checkId,proto3" json:"check_id,omitempty"`                                                           // 检查ID
	RequesterPeerId string                 `protobuf:"bytes,2,opt,name=requester_peer_id,json=requesterPeerId,proto3" json:"requester_peer_id,omitempty"`                                 // 请求者节点ID
	CheckTypes      []HealthCheckType      `protobuf:"varint,3,rep,packed,name=check_types,json=checkTypes,proto3,enum=pb.network.protocol.HealthCheckType" json:"check_types,omitempty"` // 检查类型
	CheckTimeout    uint64                 `protobuf:"varint,4,opt,name=check_timeout,json=checkTimeout,proto3" json:"check_timeout,omitempty"`                                           // 检查超时
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NetworkHealthCheckRequest) Reset() {
	*x = NetworkHealthCheckRequest{}
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkHealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkHealthCheckRequest) ProtoMessage() {}

func (x *NetworkHealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkHealthCheckRequest.ProtoReflect.Descriptor instead.
func (*NetworkHealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_test_network_management_proto_rawDescGZIP(), []int{13}
}

func (x *NetworkHealthCheckRequest) GetCheckId() string {
	if x != nil {
		return x.CheckId
	}
	return ""
}

func (x *NetworkHealthCheckRequest) GetRequesterPeerId() string {
	if x != nil {
		return x.RequesterPeerId
	}
	return ""
}

func (x *NetworkHealthCheckRequest) GetCheckTypes() []HealthCheckType {
	if x != nil {
		return x.CheckTypes
	}
	return nil
}

func (x *NetworkHealthCheckRequest) GetCheckTimeout() uint64 {
	if x != nil {
		return x.CheckTimeout
	}
	return 0
}

// NetworkHealthCheckResponse 网络健康检查响应
type NetworkHealthCheckResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CheckId           string                 `protobuf:"bytes,1,opt,name=check_id,json=checkId,proto3" json:"check_id,omitempty"`                                // 对应的检查ID
	RespondingPeerId  string                 `protobuf:"bytes,2,opt,name=responding_peer_id,json=respondingPeerId,proto3" json:"responding_peer_id,omitempty"`   // 响应节点ID
	HealthReport      *NetworkHealthReport   `protobuf:"bytes,3,opt,name=health_report,json=healthReport,proto3" json:"health_report,omitempty"`                 // 健康报告
	ResponseTimestamp uint64                 `protobuf:"varint,4,opt,name=response_timestamp,json=responseTimestamp,proto3" json:"response_timestamp,omitempty"` // 响应时间戳
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NetworkHealthCheckResponse) Reset() {
	*x = NetworkHealthCheckResponse{}
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkHealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkHealthCheckResponse) ProtoMessage() {}

func (x *NetworkHealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkHealthCheckResponse.ProtoReflect.Descriptor instead.
func (*NetworkHealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_test_network_management_proto_rawDescGZIP(), []int{14}
}

func (x *NetworkHealthCheckResponse) GetCheckId() string {
	if x != nil {
		return x.CheckId
	}
	return ""
}

func (x *NetworkHealthCheckResponse) GetRespondingPeerId() string {
	if x != nil {
		return x.RespondingPeerId
	}
	return ""
}

func (x *NetworkHealthCheckResponse) GetHealthReport() *NetworkHealthReport {
	if x != nil {
		return x.HealthReport
	}
	return nil
}

func (x *NetworkHealthCheckResponse) GetResponseTimestamp() uint64 {
	if x != nil {
		return x.ResponseTimestamp
	}
	return 0
}

// NetworkHealthReport 网络健康报告
type NetworkHealthReport struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PeerId             string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`                                                                 // 节点ID
	OverallStatus      NodeHealthStatus       `protobuf:"varint,2,opt,name=overall_status,json=overallStatus,proto3,enum=pb.network.protocol.NodeHealthStatus" json:"overall_status,omitempty"` // 总体状态
	CheckResults       []*HealthCheckResult   `protobuf:"bytes,3,rep,name=check_results,json=checkResults,proto3" json:"check_results,omitempty"`                                               // 检查结果
	NetworkMetrics     *NetworkMetrics        `protobuf:"bytes,4,opt,name=network_metrics,json=networkMetrics,proto3" json:"network_metrics,omitempty"`                                         // 网络指标
	BlockchainMetrics  *BlockchainMetrics     `protobuf:"bytes,5,opt,name=blockchain_metrics,json=blockchainMetrics,proto3" json:"blockchain_metrics,omitempty"`                                // 区块链指标
	PerformanceMetrics *PerformanceMetrics    `protobuf:"bytes,6,opt,name=performance_metrics,json=performanceMetrics,proto3" json:"performance_metrics,omitempty"`                             // 性能指标
	ReportTimestamp    uint64                 `protobuf:"varint,7,opt,name=report_timestamp,json=reportTimestamp,proto3" json:"report_timestamp,omitempty"`                                     // 报告时间戳
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NetworkHealthReport) Reset() {
	*x = NetworkHealthReport{}
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkHealthReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkHealthReport) ProtoMessage() {}

func (x *NetworkHealthReport) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkHealthReport.ProtoReflect.Descriptor instead.
func (*NetworkHealthReport) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_test_network_management_proto_rawDescGZIP(), []int{15}
}

func (x *NetworkHealthReport) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *NetworkHealthReport) GetOverallStatus() NodeHealthStatus {
	if x != nil {
		return x.OverallStatus
	}
	return NodeHealthStatus_HEALTH_STATUS_UNKNOWN
}

func (x *NetworkHealthReport) GetCheckResults() []*HealthCheckResult {
	if x != nil {
		return x.CheckResults
	}
	return nil
}

func (x *NetworkHealthReport) GetNetworkMetrics() *NetworkMetrics {
	if x != nil {
		return x.NetworkMetrics
	}
	return nil
}

func (x *NetworkHealthReport) GetBlockchainMetrics() *BlockchainMetrics {
	if x != nil {
		return x.BlockchainMetrics
	}
	return nil
}

func (x *NetworkHealthReport) GetPerformanceMetrics() *PerformanceMetrics {
	if x != nil {
		return x.PerformanceMetrics
	}
	return nil
}

func (x *NetworkHealthReport) GetReportTimestamp() uint64 {
	if x != nil {
		return x.ReportTimestamp
	}
	return 0
}

// HealthCheckResult 健康检查结果
type HealthCheckResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckType     HealthCheckType        `protobuf:"varint,1,opt,name=check_type,json=checkType,proto3,enum=pb.network.protocol.HealthCheckType" json:"check_type,omitempty"`            // 检查类型
	Passed        bool                   `protobuf:"varint,2,opt,name=passed,proto3" json:"passed,omitempty"`                                                                            // 是否通过
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                                                           // 检查消息
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`                                                                             // 评分（0-100）
	Details       map[string]string      `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 详细信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResult) Reset() {
	*x = HealthCheckResult{}
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResult) ProtoMessage() {}

func (x *HealthCheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResult.ProtoReflect.Descriptor instead.
func (*HealthCheckResult) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_test_network_management_proto_rawDescGZIP(), []int{16}
}

func (x *HealthCheckResult) GetCheckType() HealthCheckType {
	if x != nil {
		return x.CheckType
	}
	return HealthCheckType_HEALTH_CHECK_UNKNOWN
}

func (x *HealthCheckResult) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *HealthCheckResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *HealthCheckResult) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

// NetworkMetrics 网络指标
type NetworkMetrics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConnectedPeers    uint32                 `protobuf:"varint,1,opt,name=connected_peers,json=connectedPeers,proto3" json:"connected_peers,omitempty"`           // 连接的节点数
	ActiveConnections uint32                 `protobuf:"varint,2,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`  // 活跃连接数
	AverageLatencyMs  float64                `protobuf:"fixed64,3,opt,name=average_latency_ms,json=averageLatencyMs,proto3" json:"average_latency_ms,omitempty"`  // 平均延迟（毫秒）
	BytesSent         uint64                 `protobuf:"varint,4,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`                          // 发送字节数
	BytesReceived     uint64                 `protobuf:"varint,5,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`              // 接收字节数
	MessageThroughput float64                `protobuf:"fixed64,6,opt,name=message_throughput,json=messageThroughput,proto3" json:"message_throughput,omitempty"` // 消息吞吐量（msg/s）
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NetworkMetrics) Reset() {
	*x = NetworkMetrics{}
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMetrics) ProtoMessage() {}

func (x *NetworkMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMetrics.ProtoReflect.Descriptor instead.
func (*NetworkMetrics) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_test_network_management_proto_rawDescGZIP(), []int{17}
}

func (x *NetworkMetrics) GetConnectedPeers() uint32 {
	if x != nil {
		return x.ConnectedPeers
	}
	return 0
}

func (x *NetworkMetrics) GetActiveConnections() uint32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *NetworkMetrics) GetAverageLatencyMs() float64 {
	if x != nil {
		return x.AverageLatencyMs
	}
	return 0
}

func (x *NetworkMetrics) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *NetworkMetrics) GetBytesReceived() uint64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *NetworkMetrics) GetMessageThroughput() float64 {
	if x != nil {
		return x.MessageThroughput
	}
	return 0
}

// BlockchainMetrics 区块链指标
type BlockchainMetrics struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CurrentHeight       uint64                 `protobuf:"varint,1,opt,name=current_height,json=currentHeight,proto3" json:"current_height,omitempty"`                   // 当前高度
	LastBlockTime       uint64                 `protobuf:"varint,2,opt,name=last_block_time,json=lastBlockTime,proto3" json:"last_block_time,omitempty"`                 // 最后区块时间
	AverageBlockTime    float64                `protobuf:"fixed64,3,opt,name=average_block_time,json=averageBlockTime,proto3" json:"average_block_time,omitempty"`       // 平均出块时间
	PendingTransactions uint32                 `protobuf:"varint,4,opt,name=pending_transactions,json=pendingTransactions,proto3" json:"pending_transactions,omitempty"` // 待处理交易数
	SyncStatus          bool                   `protobuf:"varint,5,opt,name=sync_status,json=syncStatus,proto3" json:"sync_status,omitempty"`                            // 同步状态
	ChainProgress       float64                `protobuf:"fixed64,6,opt,name=chain_progress,json=chainProgress,proto3" json:"chain_progress,omitempty"`                  // 链同步进度（0-100%）
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BlockchainMetrics) Reset() {
	*x = BlockchainMetrics{}
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockchainMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockchainMetrics) ProtoMessage() {}

func (x *BlockchainMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockchainMetrics.ProtoReflect.Descriptor instead.
func (*BlockchainMetrics) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_test_network_management_proto_rawDescGZIP(), []int{18}
}

func (x *BlockchainMetrics) GetCurrentHeight() uint64 {
	if x != nil {
		return x.CurrentHeight
	}
	return 0
}

func (x *BlockchainMetrics) GetLastBlockTime() uint64 {
	if x != nil {
		return x.LastBlockTime
	}
	return 0
}

func (x *BlockchainMetrics) GetAverageBlockTime() float64 {
	if x != nil {
		return x.AverageBlockTime
	}
	return 0
}

func (x *BlockchainMetrics) GetPendingTransactions() uint32 {
	if x != nil {
		return x.PendingTransactions
	}
	return 0
}

func (x *BlockchainMetrics) GetSyncStatus() bool {
	if x != nil {
		return x.SyncStatus
	}
	return false
}

func (x *BlockchainMetrics) GetChainProgress() float64 {
	if x != nil {
		return x.ChainProgress
	}
	return 0
}

// PerformanceMetrics 性能指标
type PerformanceMetrics struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CpuUsagePercent    float64                `protobuf:"fixed64,1,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`          // CPU使用率
	MemoryUsagePercent float64                `protobuf:"fixed64,2,opt,name=memory_usage_percent,json=memoryUsagePercent,proto3" json:"memory_usage_percent,omitempty"` // 内存使用率
	DiskUsageBytes     uint64                 `protobuf:"varint,3,opt,name=disk_usage_bytes,json=diskUsageBytes,proto3" json:"disk_usage_bytes,omitempty"`              // 磁盘使用量
	NetworkIoMbps      float64                `protobuf:"fixed64,4,opt,name=network_io_mbps,json=networkIoMbps,proto3" json:"network_io_mbps,omitempty"`                // 网络IO速率
	GoroutineCount     uint32                 `protobuf:"varint,5,opt,name=goroutine_count,json=goroutineCount,proto3" json:"goroutine_count,omitempty"`                // 协程数量
	GcPauseMs          float64                `protobuf:"fixed64,6,opt,name=gc_pause_ms,json=gcPauseMs,proto3" json:"gc_pause_ms,omitempty"`                            // GC暂停时间
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PerformanceMetrics) Reset() {
	*x = PerformanceMetrics{}
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformanceMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformanceMetrics) ProtoMessage() {}

func (x *PerformanceMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_test_network_management_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformanceMetrics.ProtoReflect.Descriptor instead.
func (*PerformanceMetrics) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_test_network_management_proto_rawDescGZIP(), []int{19}
}

func (x *PerformanceMetrics) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *PerformanceMetrics) GetMemoryUsagePercent() float64 {
	if x != nil {
		return x.MemoryUsagePercent
	}
	return 0
}

func (x *PerformanceMetrics) GetDiskUsageBytes() uint64 {
	if x != nil {
		return x.DiskUsageBytes
	}
	return 0
}

func (x *PerformanceMetrics) GetNetworkIoMbps() float64 {
	if x != nil {
		return x.NetworkIoMbps
	}
	return 0
}

func (x *PerformanceMetrics) GetGoroutineCount() uint32 {
	if x != nil {
		return x.GoroutineCount
	}
	return 0
}

func (x *PerformanceMetrics) GetGcPauseMs() float64 {
	if x != nil {
		return x.GcPauseMs
	}
	return 0
}

var File_pb_network_protocol_test_network_management_proto protoreflect.FileDescriptor

const file_pb_network_protocol_test_network_management_proto_rawDesc = "" +
	"\n" +
	"1pb/network/protocol/test_network_management.proto\x12\x13pb.network.protocol\"\xb6\x04\n" +
	"\x17TestNetworkResetMessage\x12\x19\n" +
	"\breset_id\x18\x01 \x01(\tR\aresetId\x12!\n" +
	"\freset_height\x18\x02 \x01(\x04R\vresetHeight\x12!\n" +
	"\freset_reason\x18\x03 \x01(\tR\vresetReason\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\x12\x1f\n" +
	"\vforce_reset\x18\x05 \x01(\bR\n" +
	"forceReset\x12\x1f\n" +
	"\vkeep_config\x18\x06 \x01(\bR\n" +
	"keepConfig\x12.\n" +
	"\x13backup_before_reset\x18\a \x01(\bR\x11backupBeforeReset\x12)\n" +
	"\x10exclude_patterns\x18\b \x03(\tR\x0fexcludePatterns\x12$\n" +
	"\x0esource_peer_id\x18\t \x01(\tR\fsourcePeerId\x12'\n" +
	"\x0fadmin_signature\x18\n" +
	" \x01(\fR\x0eadminSignature\x12#\n" +
	"\rsession_token\x18\v \x01(\tR\fsessionToken\x12%\n" +
	"\x0ereset_sequence\x18\f \x01(\rR\rresetSequence\x121\n" +
	"\x14coordination_timeout\x18\r \x01(\x04R\x13coordinationTimeout\x121\n" +
	"\x14require_confirmation\x18\x0e \x01(\bR\x13requireConfirmation\"\xb8\x03\n" +
	"\x18TestNetworkResetResponse\x12\x19\n" +
	"\breset_id\x18\x01 \x01(\tR\aresetId\x12,\n" +
	"\x12responding_peer_id\x18\x02 \x01(\tR\x10respondingPeerId\x128\n" +
	"\x06status\x18\x03 \x01(\x0e2 .pb.network.protocol.ResetStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12-\n" +
	"\x12response_timestamp\x18\x05 \x01(\x04R\x11responseTimestamp\x12T\n" +
	"\x10execution_result\x18\x06 \x01(\v2).pb.network.protocol.ResetExecutionResultR\x0fexecutionResult\x12.\n" +
	"\x13cleanup_duration_ms\x18\a \x01(\x04R\x11cleanupDurationMs\x12#\n" +
	"\rcleaned_paths\x18\b \x03(\tR\fcleanedPaths\x12%\n" +
	"\x0eerror_messages\x18\t \x03(\tR\rerrorMessages\"\xd1\x01\n" +
	"\x14ResetExecutionResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0eblocks_removed\x18\x02 \x01(\x04R\rblocksRemoved\x12&\n" +
	"\x0fdata_size_freed\x18\x03 \x01(\x04R\rdataSizeFreed\x12\x1f\n" +
	"\vbackup_path\x18\x04 \x01(\tR\n" +
	"backupPath\x12/\n" +
	"\x13network_reconnected\x18\x05 \x01(\bR\x12networkReconnected\"\xa8\x02\n" +
	"\x1eNetworkConsistencyCheckRequest\x12\x19\n" +
	"\bcheck_id\x18\x01 \x01(\tR\acheckId\x12*\n" +
	"\x11requester_peer_id\x18\x02 \x01(\tR\x0frequesterPeerId\x12\x1f\n" +
	"\vcheck_depth\x18\x03 \x01(\rR\n" +
	"checkDepth\x12\x1f\n" +
	"\vbase_height\x18\x04 \x01(\x04R\n" +
	"baseHeight\x12&\n" +
	"\x0ftarget_peer_ids\x18\x05 \x03(\tR\rtargetPeerIds\x12#\n" +
	"\rcheck_timeout\x18\x06 \x01(\x04R\fcheckTimeout\x120\n" +
	"\x14include_block_hashes\x18\a \x01(\bR\x12includeBlockHashes\"\xe3\x01\n" +
	"\x1fNetworkConsistencyCheckResponse\x12\x19\n" +
	"\bcheck_id\x18\x01 \x01(\tR\acheckId\x12,\n" +
	"\x12responding_peer_id\x18\x02 \x01(\tR\x10respondingPeerId\x12H\n" +
	"\n" +
	"node_state\x18\x03 \x01(\v2).pb.network.protocol.NodeConsistencyStateR\tnodeState\x12-\n" +
	"\x12response_timestamp\x18\x04 \x01(\x04R\x11responseTimestamp\"\xd7\x02\n" +
	"\x14NodeConsistencyState\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12%\n" +
	"\x0ecurrent_height\x18\x02 \x01(\x04R\rcurrentHeight\x12*\n" +
	"\x11latest_block_hash\x18\x03 \x01(\tR\x0flatestBlockHash\x12E\n" +
	"\fblock_hashes\x18\x04 \x03(\v2\".pb.network.protocol.BlockHashInfoR\vblockHashes\x12J\n" +
	"\rhealth_status\x18\x05 \x01(\x0e2%.pb.network.protocol.NodeHealthStatusR\fhealthStatus\x12(\n" +
	"\x10last_update_time\x18\x06 \x01(\x04R\x0elastUpdateTime\x12\x16\n" +
	"\x06issues\x18\a \x03(\tR\x06issues\"\x91\x01\n" +
	"\rBlockHashInfo\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x02 \x01(\tR\tblockHash\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\x12+\n" +
	"\x11transaction_count\x18\x04 \x01(\rR\x10transactionCount\"\x90\x04\n" +
	"\x12TestSessionMessage\x12J\n" +
	"\fmessage_type\x18\x01 \x01(\x0e2'.pb.network.protocol.SessionMessageTypeR\vmessageType\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12$\n" +
	"\x0esource_peer_id\x18\x03 \x01(\tR\fsourcePeerId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\x12O\n" +
	"\rsession_start\x18\x05 \x01(\v2(.pb.network.protocol.SessionStartRequestH\x00R\fsessionStart\x12L\n" +
	"\fsession_join\x18\x06 \x01(\v2'.pb.network.protocol.SessionJoinRequestH\x00R\vsessionJoin\x12Q\n" +
	"\x0esession_status\x18\a \x01(\v2(.pb.network.protocol.SessionStatusUpdateH\x00R\rsessionStatus\x12N\n" +
	"\vsession_end\x18\b \x01(\v2+.pb.network.protocol.SessionEndNotificationH\x00R\n" +
	"sessionEndB\t\n" +
	"\acontent\"\xe0\x02\n" +
	"\x13SessionStartRequest\x12!\n" +
	"\fsession_name\x18\x01 \x01(\tR\vsessionName\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12,\n" +
	"\x12clean_before_start\x18\x03 \x01(\bR\x10cleanBeforeStart\x120\n" +
	"\x14participant_peer_ids\x18\x04 \x03(\tR\x12participantPeerIds\x12b\n" +
	"\x0esession_config\x18\x05 \x03(\v2;.pb.network.protocol.SessionStartRequest.SessionConfigEntryR\rsessionConfig\x1a@\n" +
	"\x12SessionConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"m\n" +
	"\x12SessionJoinRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\x12\x1f\n" +
	"\vjoin_reason\x18\x03 \x01(\tR\n" +
	"joinReason\"\xad\x02\n" +
	"\x13SessionStatusUpdate\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12:\n" +
	"\x06status\x18\x02 \x01(\x0e2\".pb.network.protocol.SessionStatusR\x06status\x12Y\n" +
	"\vstatus_data\x18\x03 \x03(\v28.pb.network.protocol.SessionStatusUpdate.StatusDataEntryR\n" +
	"statusData\x12!\n" +
	"\factive_peers\x18\x04 \x03(\tR\vactivePeers\x1a=\n" +
	"\x0fStatusDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbb\x01\n" +
	"\x16SessionEndNotification\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"end_reason\x18\x02 \x01(\tR\tendReason\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12I\n" +
	"\x0esession_report\x18\x04 \x01(\v2\".pb.network.protocol.SessionReportR\rsessionReport\"\x83\x03\n" +
	"\rSessionReport\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x04R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x04R\aendTime\x12)\n" +
	"\x10duration_seconds\x18\x04 \x01(\x04R\x0fdurationSeconds\x12+\n" +
	"\x11participant_count\x18\x05 \x01(\rR\x10participantCount\x12\"\n" +
	"\fachievements\x18\x06 \x03(\tR\fachievements\x12\x16\n" +
	"\x06issues\x18\a \x03(\tR\x06issues\x12I\n" +
	"\ametrics\x18\b \x03(\v2/.pb.network.protocol.SessionReport.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xce\x01\n" +
	"\x19NetworkHealthCheckRequest\x12\x19\n" +
	"\bcheck_id\x18\x01 \x01(\tR\acheckId\x12*\n" +
	"\x11requester_peer_id\x18\x02 \x01(\tR\x0frequesterPeerId\x12E\n" +
	"\vcheck_types\x18\x03 \x03(\x0e2$.pb.network.protocol.HealthCheckTypeR\n" +
	"checkTypes\x12#\n" +
	"\rcheck_timeout\x18\x04 \x01(\x04R\fcheckTimeout\"\xe3\x01\n" +
	"\x1aNetworkHealthCheckResponse\x12\x19\n" +
	"\bcheck_id\x18\x01 \x01(\tR\acheckId\x12,\n" +
	"\x12responding_peer_id\x18\x02 \x01(\tR\x10respondingPeerId\x12M\n" +
	"\rhealth_report\x18\x03 \x01(\v2(.pb.network.protocol.NetworkHealthReportR\fhealthReport\x12-\n" +
	"\x12response_timestamp\x18\x04 \x01(\x04R\x11responseTimestamp\"\xf3\x03\n" +
	"\x13NetworkHealthReport\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12L\n" +
	"\x0eoverall_status\x18\x02 \x01(\x0e2%.pb.network.protocol.NodeHealthStatusR\roverallStatus\x12K\n" +
	"\rcheck_results\x18\x03 \x03(\v2&.pb.network.protocol.HealthCheckResultR\fcheckResults\x12L\n" +
	"\x0fnetwork_metrics\x18\x04 \x01(\v2#.pb.network.protocol.NetworkMetricsR\x0enetworkMetrics\x12U\n" +
	"\x12blockchain_metrics\x18\x05 \x01(\v2&.pb.network.protocol.BlockchainMetricsR\x11blockchainMetrics\x12X\n" +
	"\x13performance_metrics\x18\x06 \x01(\v2'.pb.network.protocol.PerformanceMetricsR\x12performanceMetrics\x12)\n" +
	"\x10report_timestamp\x18\a \x01(\x04R\x0freportTimestamp\"\xab\x02\n" +
	"\x11HealthCheckResult\x12C\n" +
	"\n" +
	"check_type\x18\x01 \x01(\x0e2$.pb.network.protocol.HealthCheckTypeR\tcheckType\x12\x16\n" +
	"\x06passed\x18\x02 \x01(\bR\x06passed\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12M\n" +
	"\adetails\x18\x05 \x03(\v23.pb.network.protocol.HealthCheckResult.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8b\x02\n" +
	"\x0eNetworkMetrics\x12'\n" +
	"\x0fconnected_peers\x18\x01 \x01(\rR\x0econnectedPeers\x12-\n" +
	"\x12active_connections\x18\x02 \x01(\rR\x11activeConnections\x12,\n" +
	"\x12average_latency_ms\x18\x03 \x01(\x01R\x10averageLatencyMs\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x04 \x01(\x04R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\x05 \x01(\x04R\rbytesReceived\x12-\n" +
	"\x12message_throughput\x18\x06 \x01(\x01R\x11messageThroughput\"\x8b\x02\n" +
	"\x11BlockchainMetrics\x12%\n" +
	"\x0ecurrent_height\x18\x01 \x01(\x04R\rcurrentHeight\x12&\n" +
	"\x0flast_block_time\x18\x02 \x01(\x04R\rlastBlockTime\x12,\n" +
	"\x12average_block_time\x18\x03 \x01(\x01R\x10averageBlockTime\x121\n" +
	"\x14pending_transactions\x18\x04 \x01(\rR\x13pendingTransactions\x12\x1f\n" +
	"\vsync_status\x18\x05 \x01(\bR\n" +
	"syncStatus\x12%\n" +
	"\x0echain_progress\x18\x06 \x01(\x01R\rchainProgress\"\x8d\x02\n" +
	"\x12PerformanceMetrics\x12*\n" +
	"\x11cpu_usage_percent\x18\x01 \x01(\x01R\x0fcpuUsagePercent\x120\n" +
	"\x14memory_usage_percent\x18\x02 \x01(\x01R\x12memoryUsagePercent\x12(\n" +
	"\x10disk_usage_bytes\x18\x03 \x01(\x04R\x0ediskUsageBytes\x12&\n" +
	"\x0fnetwork_io_mbps\x18\x04 \x01(\x01R\rnetworkIoMbps\x12'\n" +
	"\x0fgoroutine_count\x18\x05 \x01(\rR\x0egoroutineCount\x12\x1e\n" +
	"\vgc_pause_ms\x18\x06 \x01(\x01R\tgcPauseMs*\xca\x01\n" +
	"\vResetStatus\x12\x18\n" +
	"\x14RESET_STATUS_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15RESET_STATUS_ACCEPTED\x10\x01\x12\x1c\n" +
	"\x18RESET_STATUS_IN_PROGRESS\x10\x02\x12\x1a\n" +
	"\x16RESET_STATUS_COMPLETED\x10\x03\x12\x17\n" +
	"\x13RESET_STATUS_FAILED\x10\x04\x12\x19\n" +
	"\x15RESET_STATUS_REJECTED\x10\x05\x12\x18\n" +
	"\x14RESET_STATUS_TIMEOUT\x10\x06*\xb3\x01\n" +
	"\x10NodeHealthStatus\x12\x19\n" +
	"\x15HEALTH_STATUS_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_HEALTHY\x10\x01\x12\x19\n" +
	"\x15HEALTH_STATUS_WARNING\x10\x02\x12\x17\n" +
	"\x13HEALTH_STATUS_ERROR\x10\x03\x12\x1a\n" +
	"\x16HEALTH_STATUS_CRITICAL\x10\x04\x12\x19\n" +
	"\x15HEALTH_STATUS_OFFLINE\x10\x05*\xb5\x01\n" +
	"\x12SessionMessageType\x12\x1b\n" +
	"\x17SESSION_MESSAGE_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15SESSION_MESSAGE_START\x10\x01\x12\x18\n" +
	"\x14SESSION_MESSAGE_JOIN\x10\x02\x12\x1a\n" +
	"\x16SESSION_MESSAGE_STATUS\x10\x03\x12\x17\n" +
	"\x13SESSION_MESSAGE_END\x10\x04\x12\x18\n" +
	"\x14SESSION_MESSAGE_SYNC\x10\x05*\xd2\x01\n" +
	"\rSessionStatus\x12\x1a\n" +
	"\x16SESSION_STATUS_UNKNOWN\x10\x00\x12\x1b\n" +
	"\x17SESSION_STATUS_STARTING\x10\x01\x12\x19\n" +
	"\x15SESSION_STATUS_ACTIVE\x10\x02\x12\x19\n" +
	"\x15SESSION_STATUS_PAUSED\x10\x03\x12\x19\n" +
	"\x15SESSION_STATUS_ENDING\x10\x04\x12\x1c\n" +
	"\x18SESSION_STATUS_COMPLETED\x10\x05\x12\x19\n" +
	"\x15SESSION_STATUS_FAILED\x10\x06*\xb6\x01\n" +
	"\x0fHealthCheckType\x12\x18\n" +
	"\x14HEALTH_CHECK_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14HEALTH_CHECK_NETWORK\x10\x01\x12\x1b\n" +
	"\x17HEALTH_CHECK_BLOCKCHAIN\x10\x02\x12\x18\n" +
	"\x14HEALTH_CHECK_STORAGE\x10\x03\x12\x1c\n" +
	"\x18HEALTH_CHECK_PERFORMANCE\x10\x04\x12\x1a\n" +
	"\x16HEALTH_CHECK_CONSENSUS\x10\x05B*Z(github.com/weisyn/v1/pb/network/protocolb\x06proto3"

var (
	file_pb_network_protocol_test_network_management_proto_rawDescOnce sync.Once
	file_pb_network_protocol_test_network_management_proto_rawDescData []byte
)

func file_pb_network_protocol_test_network_management_proto_rawDescGZIP() []byte {
	file_pb_network_protocol_test_network_management_proto_rawDescOnce.Do(func() {
		file_pb_network_protocol_test_network_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_network_protocol_test_network_management_proto_rawDesc), len(file_pb_network_protocol_test_network_management_proto_rawDesc)))
	})
	return file_pb_network_protocol_test_network_management_proto_rawDescData
}

var file_pb_network_protocol_test_network_management_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_pb_network_protocol_test_network_management_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_pb_network_protocol_test_network_management_proto_goTypes = []any{
	(ResetStatus)(0),                        // 0: pb.network.protocol.ResetStatus
	(NodeHealthStatus)(0),                   // 1: pb.network.protocol.NodeHealthStatus
	(SessionMessageType)(0),                 // 2: pb.network.protocol.SessionMessageType
	(SessionStatus)(0),                      // 3: pb.network.protocol.SessionStatus
	(HealthCheckType)(0),                    // 4: pb.network.protocol.HealthCheckType
	(*TestNetworkResetMessage)(nil),         // 5: pb.network.protocol.TestNetworkResetMessage
	(*TestNetworkResetResponse)(nil),        // 6: pb.network.protocol.TestNetworkResetResponse
	(*ResetExecutionResult)(nil),            // 7: pb.network.protocol.ResetExecutionResult
	(*NetworkConsistencyCheckRequest)(nil),  // 8: pb.network.protocol.NetworkConsistencyCheckRequest
	(*NetworkConsistencyCheckResponse)(nil), // 9: pb.network.protocol.NetworkConsistencyCheckResponse
	(*NodeConsistencyState)(nil),            // 10: pb.network.protocol.NodeConsistencyState
	(*BlockHashInfo)(nil),                   // 11: pb.network.protocol.BlockHashInfo
	(*TestSessionMessage)(nil),              // 12: pb.network.protocol.TestSessionMessage
	(*SessionStartRequest)(nil),             // 13: pb.network.protocol.SessionStartRequest
	(*SessionJoinRequest)(nil),              // 14: pb.network.protocol.SessionJoinRequest
	(*SessionStatusUpdate)(nil),             // 15: pb.network.protocol.SessionStatusUpdate
	(*SessionEndNotification)(nil),          // 16: pb.network.protocol.SessionEndNotification
	(*SessionReport)(nil),                   // 17: pb.network.protocol.SessionReport
	(*NetworkHealthCheckRequest)(nil),       // 18: pb.network.protocol.NetworkHealthCheckRequest
	(*NetworkHealthCheckResponse)(nil),      // 19: pb.network.protocol.NetworkHealthCheckResponse
	(*NetworkHealthReport)(nil),             // 20: pb.network.protocol.NetworkHealthReport
	(*HealthCheckResult)(nil),               // 21: pb.network.protocol.HealthCheckResult
	(*NetworkMetrics)(nil),                  // 22: pb.network.protocol.NetworkMetrics
	(*BlockchainMetrics)(nil),               // 23: pb.network.protocol.BlockchainMetrics
	(*PerformanceMetrics)(nil),              // 24: pb.network.protocol.PerformanceMetrics
	nil,                                     // 25: pb.network.protocol.SessionStartRequest.SessionConfigEntry
	nil,                                     // 26: pb.network.protocol.SessionStatusUpdate.StatusDataEntry
	nil,                                     // 27: pb.network.protocol.SessionReport.MetricsEntry
	nil,                                     // 28: pb.network.protocol.HealthCheckResult.DetailsEntry
}
var file_pb_network_protocol_test_network_management_proto_depIdxs = []int32{
	0,  // 0: pb.network.protocol.TestNetworkResetResponse.status:type_name -> pb.network.protocol.ResetStatus
	7,  // 1: pb.network.protocol.TestNetworkResetResponse.execution_result:type_name -> pb.network.protocol.ResetExecutionResult
	10, // 2: pb.network.protocol.NetworkConsistencyCheckResponse.node_state:type_name -> pb.network.protocol.NodeConsistencyState
	11, // 3: pb.network.protocol.NodeConsistencyState.block_hashes:type_name -> pb.network.protocol.BlockHashInfo
	1,  // 4: pb.network.protocol.NodeConsistencyState.health_status:type_name -> pb.network.protocol.NodeHealthStatus
	2,  // 5: pb.network.protocol.TestSessionMessage.message_type:type_name -> pb.network.protocol.SessionMessageType
	13, // 6: pb.network.protocol.TestSessionMessage.session_start:type_name -> pb.network.protocol.SessionStartRequest
	14, // 7: pb.network.protocol.TestSessionMessage.session_join:type_name -> pb.network.protocol.SessionJoinRequest
	15, // 8: pb.network.protocol.TestSessionMessage.session_status:type_name -> pb.network.protocol.SessionStatusUpdate
	16, // 9: pb.network.protocol.TestSessionMessage.session_end:type_name -> pb.network.protocol.SessionEndNotification
	25, // 10: pb.network.protocol.SessionStartRequest.session_config:type_name -> pb.network.protocol.SessionStartRequest.SessionConfigEntry
	3,  // 11: pb.network.protocol.SessionStatusUpdate.status:type_name -> pb.network.protocol.SessionStatus
	26, // 12: pb.network.protocol.SessionStatusUpdate.status_data:type_name -> pb.network.protocol.SessionStatusUpdate.StatusDataEntry
	17, // 13: pb.network.protocol.SessionEndNotification.session_report:type_name -> pb.network.protocol.SessionReport
	27, // 14: pb.network.protocol.SessionReport.metrics:type_name -> pb.network.protocol.SessionReport.MetricsEntry
	4,  // 15: pb.network.protocol.NetworkHealthCheckRequest.check_types:type_name -> pb.network.protocol.HealthCheckType
	20, // 16: pb.network.protocol.NetworkHealthCheckResponse.health_report:type_name -> pb.network.protocol.NetworkHealthReport
	1,  // 17: pb.network.protocol.NetworkHealthReport.overall_status:type_name -> pb.network.protocol.NodeHealthStatus
	21, // 18: pb.network.protocol.NetworkHealthReport.check_results:type_name -> pb.network.protocol.HealthCheckResult
	22, // 19: pb.network.protocol.NetworkHealthReport.network_metrics:type_name -> pb.network.protocol.NetworkMetrics
	23, // 20: pb.network.protocol.NetworkHealthReport.blockchain_metrics:type_name -> pb.network.protocol.BlockchainMetrics
	24, // 21: pb.network.protocol.NetworkHealthReport.performance_metrics:type_name -> pb.network.protocol.PerformanceMetrics
	4,  // 22: pb.network.protocol.HealthCheckResult.check_type:type_name -> pb.network.protocol.HealthCheckType
	28, // 23: pb.network.protocol.HealthCheckResult.details:type_name -> pb.network.protocol.HealthCheckResult.DetailsEntry
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_pb_network_protocol_test_network_management_proto_init() }
func file_pb_network_protocol_test_network_management_proto_init() {
	if File_pb_network_protocol_test_network_management_proto != nil {
		return
	}
	file_pb_network_protocol_test_network_management_proto_msgTypes[7].OneofWrappers = []any{
		(*TestSessionMessage_SessionStart)(nil),
		(*TestSessionMessage_SessionJoin)(nil),
		(*TestSessionMessage_SessionStatus)(nil),
		(*TestSessionMessage_SessionEnd)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_network_protocol_test_network_management_proto_rawDesc), len(file_pb_network_protocol_test_network_management_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_network_protocol_test_network_management_proto_goTypes,
		DependencyIndexes: file_pb_network_protocol_test_network_management_proto_depIdxs,
		EnumInfos:         file_pb_network_protocol_test_network_management_proto_enumTypes,
		MessageInfos:      file_pb_network_protocol_test_network_management_proto_msgTypes,
	}.Build()
	File_pb_network_protocol_test_network_management_proto = out.File
	file_pb_network_protocol_test_network_management_proto_goTypes = nil
	file_pb_network_protocol_test_network_management_proto_depIdxs = nil
}
