// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: pb/network/protocol/transaction.proto

package protocol

import (
	transaction "github.com/weisyn/v1/pb/blockchain/block/transaction"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionPropagationResponse_TransactionStatus_TransactionProcessingStatus int32

const (
	TransactionPropagationResponse_TransactionStatus_STATUS_UNKNOWN   TransactionPropagationResponse_TransactionStatus_TransactionProcessingStatus = 0 // 未知状态
	TransactionPropagationResponse_TransactionStatus_STATUS_ACCEPTED  TransactionPropagationResponse_TransactionStatus_TransactionProcessingStatus = 1 // 已接受
	TransactionPropagationResponse_TransactionStatus_STATUS_DUPLICATE TransactionPropagationResponse_TransactionStatus_TransactionProcessingStatus = 2 // 重复交易
	TransactionPropagationResponse_TransactionStatus_STATUS_REJECTED  TransactionPropagationResponse_TransactionStatus_TransactionProcessingStatus = 3 // 已拒绝
)

// Enum value maps for TransactionPropagationResponse_TransactionStatus_TransactionProcessingStatus.
var (
	TransactionPropagationResponse_TransactionStatus_TransactionProcessingStatus_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_ACCEPTED",
		2: "STATUS_DUPLICATE",
		3: "STATUS_REJECTED",
	}
	TransactionPropagationResponse_TransactionStatus_TransactionProcessingStatus_value = map[string]int32{
		"STATUS_UNKNOWN":   0,
		"STATUS_ACCEPTED":  1,
		"STATUS_DUPLICATE": 2,
		"STATUS_REJECTED":  3,
	}
)

func (x TransactionPropagationResponse_TransactionStatus_TransactionProcessingStatus) Enum() *TransactionPropagationResponse_TransactionStatus_TransactionProcessingStatus {
	p := new(TransactionPropagationResponse_TransactionStatus_TransactionProcessingStatus)
	*p = x
	return p
}

func (x TransactionPropagationResponse_TransactionStatus_TransactionProcessingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionPropagationResponse_TransactionStatus_TransactionProcessingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_network_protocol_transaction_proto_enumTypes[0].Descriptor()
}

func (TransactionPropagationResponse_TransactionStatus_TransactionProcessingStatus) Type() protoreflect.EnumType {
	return &file_pb_network_protocol_transaction_proto_enumTypes[0]
}

func (x TransactionPropagationResponse_TransactionStatus_TransactionProcessingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionPropagationResponse_TransactionStatus_TransactionProcessingStatus.Descriptor instead.
func (TransactionPropagationResponse_TransactionStatus_TransactionProcessingStatus) EnumDescriptor() ([]byte, []int) {
	return file_pb_network_protocol_transaction_proto_rawDescGZIP(), []int{2, 0, 0}
}

// *
// TransactionAnnouncement - 交易广播通告
//
// 🎯 设计目的：通过GossipSub进行高效的全网交易广播
//
// 📡 传播机制：
// - 传播方式：GossipSub订阅模式，fire-and-forget
// - 主题名称：weisyn.transaction.announce.v1
// - 覆盖范围：订阅该主题的所有节点
// - 传播效率：O(log N)复杂度，快速全网覆盖
//
// 🔧 消息结构：
// - 交易摘要：包含完整的交易数据
// - 传播元信息：发送者、时间戳、跳数等
// - 签名验证：防止消息在传播过程中被篡改
// - 去重标识：接收端快速去重的关键信息
//
// 📝 使用示例：
//
//	transaction_announcement {
//	  message_id: "announce_001"
//	  transaction_hash: sha256(transaction)
//	  transaction: {完整的交易数据}
//	  timestamp: 1640995200000
//	  sender_peer_id: "QmXXXXX..."
//	  propagation_hop: 1
//	  signature: 发送者签名
//	}
//
// 🚦 处理逻辑：
// 1. 接收端检查transaction_hash是否已存在于本地mempool
// 2. 如不存在，验证交易有效性并加入本地mempool
// 3. 继续向临近节点传播（hop递增，直到达到限制）
// 4. 如已存在，直接丢弃（去重处理）
type TransactionAnnouncement struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	MessageId       string                   `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`                   // 消息唯一标识符
	TransactionHash []byte                   `protobuf:"bytes,2,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"` // 交易哈希（32字节SHA-256）
	Transaction     *transaction.Transaction `protobuf:"bytes,3,opt,name=transaction,proto3" json:"transaction,omitempty"`                                // 完整的交易数据
	Timestamp       uint64                   `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                   // 消息创建时间戳（Unix毫秒）
	SenderPeerId    []byte                   `protobuf:"bytes,5,opt,name=sender_peer_id,json=senderPeerId,proto3" json:"sender_peer_id,omitempty"`        // 发送者节点ID
	PropagationHop  uint32                   `protobuf:"varint,6,opt,name=propagation_hop,json=propagationHop,proto3" json:"propagation_hop,omitempty"`   // 传播跳数（防循环，最大值如16）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransactionAnnouncement) Reset() {
	*x = TransactionAnnouncement{}
	mi := &file_pb_network_protocol_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionAnnouncement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionAnnouncement) ProtoMessage() {}

func (x *TransactionAnnouncement) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionAnnouncement.ProtoReflect.Descriptor instead.
func (*TransactionAnnouncement) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionAnnouncement) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *TransactionAnnouncement) GetTransactionHash() []byte {
	if x != nil {
		return x.TransactionHash
	}
	return nil
}

func (x *TransactionAnnouncement) GetTransaction() *transaction.Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *TransactionAnnouncement) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TransactionAnnouncement) GetSenderPeerId() []byte {
	if x != nil {
		return x.SenderPeerId
	}
	return nil
}

func (x *TransactionAnnouncement) GetPropagationHop() uint32 {
	if x != nil {
		return x.PropagationHop
	}
	return 0
}

// *
// TransactionPropagationRequest - 交易直连传播请求
//
// 🎯 设计目的：通过Direct Stream确保交易可靠送达
//
// 🔗 传播机制：
// - 传播方式：Stream RPC，点对点可靠传输
// - 协议ID：/weisyn/transaction/direct/1.0.0
// - 目标选择：基于K-bucket的近邻节点选择（2-3个节点）
// - 确认机制：要求接收端明确确认接收结果
//
// 🎯 使用场景：
// - GossipSub传播失败时的备用方案
// - 高价值交易的额外传播保障
// - 网络分区时的跨分区传播
// - 新节点快速同步最新交易
//
// 📝 使用示例：
//
//	transaction_propagation_request {
//	  request_id: "direct_req_001"
//	  tx_hashes: [hash1, hash2, hash3]
//	  requester_peer_id: "QmYYYYY..."
//	  timestamp: 1640995200000
//	  propagation_reason: "gossip_backup"
//	}
//
// 🔄 请求-响应流程：
// 1. 请求方选择K-bucket中的2-3个近邻节点
// 2. 发送TransactionPropagationRequest，包含交易哈希列表
// 3. 接收方检查哪些交易尚未处理，返回需要的交易哈希
// 4. 请求方发送完整的交易数据
// 5. 接收方验证并确认接收结果
type TransactionPropagationRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                     // 请求唯一标识符
	TxHashes        [][]byte               `protobuf:"bytes,2,rep,name=tx_hashes,json=txHashes,proto3" json:"tx_hashes,omitempty"`                        // 请求的交易哈希列表
	RequesterPeerId []byte                 `protobuf:"bytes,3,opt,name=requester_peer_id,json=requesterPeerId,proto3" json:"requester_peer_id,omitempty"` // 请求者节点ID
	Timestamp       uint64                 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                     // 请求时间戳（Unix毫秒）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransactionPropagationRequest) Reset() {
	*x = TransactionPropagationRequest{}
	mi := &file_pb_network_protocol_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionPropagationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionPropagationRequest) ProtoMessage() {}

func (x *TransactionPropagationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionPropagationRequest.ProtoReflect.Descriptor instead.
func (*TransactionPropagationRequest) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionPropagationRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TransactionPropagationRequest) GetTxHashes() [][]byte {
	if x != nil {
		return x.TxHashes
	}
	return nil
}

func (x *TransactionPropagationRequest) GetRequesterPeerId() []byte {
	if x != nil {
		return x.RequesterPeerId
	}
	return nil
}

func (x *TransactionPropagationRequest) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// *
// TransactionPropagationResponse - 交易直连传播响应
//
// 🎯 设计目的：确认交易传播的处理结果
//
// 📊 响应信息：
// - 处理结果：成功、失败、部分成功
// - 详细状态：每笔交易的处理状态
// - 错误信息：失败原因和建议处理方式
// - 性能指标：处理时间、网络状况等
//
// 🔄 状态分类：
// - ACCEPTED：交易已接受并加入内存池
// - DUPLICATE：交易重复，已在内存池中
// - REJECTED：交易被拒绝（验证失败、费用不足等）
// - PENDING：交易待处理（资源不足、队列满等）
// - UNKNOWN：未知状态（系统错误等）
//
// 📝 使用示例：
//
//	transaction_propagation_response {
//	  request_id: "direct_req_001"
//	  transactions: [
//	    {hash: hash1, status: ACCEPTED},
//	    {hash: hash2, status: DUPLICATE},
//	    {hash: hash3, status: REJECTED, error: "insufficient_fee"}
//	  ]
//	  success: false  // 部分成功
//	  error_message: "2 of 3 transactions processed successfully"
//	}
type TransactionPropagationResponse struct {
	state         protoimpl.MessageState                              `protogen:"open.v1"`
	RequestId     string                                              `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                // 对应请求ID
	Transactions  []*TransactionPropagationResponse_TransactionStatus `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`                           // 逐笔交易处理状态
	Success       bool                                                `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`                                    // 整体处理结果
	ErrorMessage  *string                                             `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"` // 错误信息（失败时）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionPropagationResponse) Reset() {
	*x = TransactionPropagationResponse{}
	mi := &file_pb_network_protocol_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionPropagationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionPropagationResponse) ProtoMessage() {}

func (x *TransactionPropagationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionPropagationResponse.ProtoReflect.Descriptor instead.
func (*TransactionPropagationResponse) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionPropagationResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TransactionPropagationResponse) GetTransactions() []*TransactionPropagationResponse_TransactionStatus {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *TransactionPropagationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransactionPropagationResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

type TransactionPropagationResponse_TransactionStatus struct {
	state         protoimpl.MessageState                                                       `protogen:"open.v1"`
	TxHash        []byte                                                                       `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`                                                                                          // 交易哈希
	Status        TransactionPropagationResponse_TransactionStatus_TransactionProcessingStatus `protobuf:"varint,2,opt,name=status,proto3,enum=pb.network.protocol.TransactionPropagationResponse_TransactionStatus_TransactionProcessingStatus" json:"status,omitempty"` // 处理状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionPropagationResponse_TransactionStatus) Reset() {
	*x = TransactionPropagationResponse_TransactionStatus{}
	mi := &file_pb_network_protocol_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionPropagationResponse_TransactionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionPropagationResponse_TransactionStatus) ProtoMessage() {}

func (x *TransactionPropagationResponse_TransactionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_protocol_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionPropagationResponse_TransactionStatus.ProtoReflect.Descriptor instead.
func (*TransactionPropagationResponse_TransactionStatus) Descriptor() ([]byte, []int) {
	return file_pb_network_protocol_transaction_proto_rawDescGZIP(), []int{2, 0}
}

func (x *TransactionPropagationResponse_TransactionStatus) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *TransactionPropagationResponse_TransactionStatus) GetStatus() TransactionPropagationResponse_TransactionStatus_TransactionProcessingStatus {
	if x != nil {
		return x.Status
	}
	return TransactionPropagationResponse_TransactionStatus_STATUS_UNKNOWN
}

var File_pb_network_protocol_transaction_proto protoreflect.FileDescriptor

const file_pb_network_protocol_transaction_proto_rawDesc = "" +
	"\n" +
	"%pb/network/protocol/transaction.proto\x12\x13pb.network.protocol\x1a1pb/blockchain/block/transaction/transaction.proto\"\x93\x02\n" +
	"\x17TransactionAnnouncement\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12)\n" +
	"\x10transaction_hash\x18\x02 \x01(\fR\x0ftransactionHash\x12A\n" +
	"\vtransaction\x18\x03 \x01(\v2\x1f.pb.blockchain.core.TransactionR\vtransaction\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\x12$\n" +
	"\x0esender_peer_id\x18\x05 \x01(\fR\fsenderPeerId\x12'\n" +
	"\x0fpropagation_hop\x18\x06 \x01(\rR\x0epropagationHop\"\xa5\x01\n" +
	"\x1dTransactionPropagationRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\ttx_hashes\x18\x02 \x03(\fR\btxHashes\x12*\n" +
	"\x11requester_peer_id\x18\x03 \x01(\fR\x0frequesterPeerId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\"\x9d\x04\n" +
	"\x1eTransactionPropagationResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12i\n" +
	"\ftransactions\x18\x02 \x03(\v2E.pb.network.protocol.TransactionPropagationResponse.TransactionStatusR\ftransactions\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12(\n" +
	"\rerror_message\x18\x04 \x01(\tH\x00R\ferrorMessage\x88\x01\x01\x1a\x9a\x02\n" +
	"\x11TransactionStatus\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\fR\x06txHash\x12y\n" +
	"\x06status\x18\x02 \x01(\x0e2a.pb.network.protocol.TransactionPropagationResponse.TransactionStatus.TransactionProcessingStatusR\x06status\"q\n" +
	"\x1bTransactionProcessingStatus\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fSTATUS_ACCEPTED\x10\x01\x12\x14\n" +
	"\x10STATUS_DUPLICATE\x10\x02\x12\x13\n" +
	"\x0fSTATUS_REJECTED\x10\x03B\x10\n" +
	"\x0e_error_messageB*Z(github.com/weisyn/v1/pb/network/protocolb\x06proto3"

var (
	file_pb_network_protocol_transaction_proto_rawDescOnce sync.Once
	file_pb_network_protocol_transaction_proto_rawDescData []byte
)

func file_pb_network_protocol_transaction_proto_rawDescGZIP() []byte {
	file_pb_network_protocol_transaction_proto_rawDescOnce.Do(func() {
		file_pb_network_protocol_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_network_protocol_transaction_proto_rawDesc), len(file_pb_network_protocol_transaction_proto_rawDesc)))
	})
	return file_pb_network_protocol_transaction_proto_rawDescData
}

var file_pb_network_protocol_transaction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_network_protocol_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_network_protocol_transaction_proto_goTypes = []any{
	(TransactionPropagationResponse_TransactionStatus_TransactionProcessingStatus)(0), // 0: pb.network.protocol.TransactionPropagationResponse.TransactionStatus.TransactionProcessingStatus
	(*TransactionAnnouncement)(nil),                          // 1: pb.network.protocol.TransactionAnnouncement
	(*TransactionPropagationRequest)(nil),                    // 2: pb.network.protocol.TransactionPropagationRequest
	(*TransactionPropagationResponse)(nil),                   // 3: pb.network.protocol.TransactionPropagationResponse
	(*TransactionPropagationResponse_TransactionStatus)(nil), // 4: pb.network.protocol.TransactionPropagationResponse.TransactionStatus
	(*transaction.Transaction)(nil),                          // 5: pb.blockchain.core.Transaction
}
var file_pb_network_protocol_transaction_proto_depIdxs = []int32{
	5, // 0: pb.network.protocol.TransactionAnnouncement.transaction:type_name -> pb.blockchain.core.Transaction
	4, // 1: pb.network.protocol.TransactionPropagationResponse.transactions:type_name -> pb.network.protocol.TransactionPropagationResponse.TransactionStatus
	0, // 2: pb.network.protocol.TransactionPropagationResponse.TransactionStatus.status:type_name -> pb.network.protocol.TransactionPropagationResponse.TransactionStatus.TransactionProcessingStatus
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pb_network_protocol_transaction_proto_init() }
func file_pb_network_protocol_transaction_proto_init() {
	if File_pb_network_protocol_transaction_proto != nil {
		return
	}
	file_pb_network_protocol_transaction_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_network_protocol_transaction_proto_rawDesc), len(file_pb_network_protocol_transaction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_network_protocol_transaction_proto_goTypes,
		DependencyIndexes: file_pb_network_protocol_transaction_proto_depIdxs,
		EnumInfos:         file_pb_network_protocol_transaction_proto_enumTypes,
		MessageInfos:      file_pb_network_protocol_transaction_proto_msgTypes,
	}.Build()
	File_pb_network_protocol_transaction_proto = out.File
	file_pb_network_protocol_transaction_proto_goTypes = nil
	file_pb_network_protocol_transaction_proto_depIdxs = nil
}
