// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: pb/blockchain/block/block.proto

package block

import (
	transaction "github.com/weisyn/v1/pb/blockchain/block/transaction"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// 区块在链中的位置与关系:
//
// +----------------+      +----------------+      +----------------+
// |   区块 N-1     |----->|     区块 N     |----->|   区块 N+1     |
// +----------------+      +----------------+      +----------------+
//
//	       |
//	       v
//	+----------------+
//	|    区块头      |
//	|    区块体      |
//	+----------------+
//
// 区块生命周期与状态:
//
// +----------------+      +----------------+      +----------------+      +----------------+
// |   提议/创建     |----->|    验证/共识    |----->|   提交/确认     |----->|   最终性/归档   |
// +----------------+      +----------------+      +----------------+      +----------------+
//
//	|                       |                       |                       |
//	v                       v                       v                       v
//
// +----------------+      +----------------+      +----------------+      +----------------+
// | • 打包交易      |      | • 验证区块头    |      | • 写入存储      |      | • 确认最终性    |
// | • 执行交易      |      | • 验证交易      |      | • 应用状态变更  |      | • 存档处理      |
// | • 计算状态根    |      | • 共识投票      |      | • 更新全局状态   |      | • 修剪旧数据    |
// +----------------+      +----------------+      +----------------+      +----------------+
//
// 区块结构与状态根关系:
//
// +-------------------------------+
// |           区块 N              |
// |-------------------------------|
// | 区块头:                       |
// | • merkle_root ────────┐      |
// | • state_root ──────┐  |      |
// |                    |  |      |
// | 区块体:            |  |      |
// | • 交易列表         |  |      |
// +-------------------─┼─────────+
//
//	|
//
// +-------------------─┼─────────+
// | 状态数据:          |         |
// | • 交易执行后的      |         |
// |   全局状态变更     |         |
// |                    |         |
// | 计算得到: ─────────┘         |
// | state_root                   |
// +-------------------------------+
type Block struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 区块头
	Header *BlockHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"` // 区块头，由共识引擎生成，包含元数据和各种哈希根
	// 区块体
	Body          *BlockBody `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"` // 区块体，由交易池收集交易并组织生成，包含实际交易数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_pb_blockchain_block_block_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blockchain_block_block_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_pb_blockchain_block_block_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetHeader() *BlockHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Block) GetBody() *BlockBody {
	if x != nil {
		return x.Body
	}
	return nil
}

// *
// 区块头字段分组:
//
// +--------------------------------------+
// |              区块头                  |
// +--------------------------------------+
// | 网络标识        | Merkle验证          |
// |----------------|-------------------|
// | chain_id       | merkle_root       |
// |                | state_root        |
// +--------------------------------------+
// | 基础链接        | 共识机制            |
// |----------------|-------------------|
// | version        | nonce             |
// | previous_hash  | difficulty        |
// | timestamp      |                   |
// | height         |                   |
// +--------------------------------------+
//
// 区块头字段用途与组合场景:
//
// 1. 网络安全与身份验证（最重要）:
//   - chain_id: 防止跨链重放攻击，确保区块只在指定链上有效
//
// 2. 区块链接与定位:
//   - version + previous_hash + height: 确定区块在链中的位置
//   - timestamp: 提供区块时间戳，用于排序和共识
//
// 3. Merkle根验证:
//   - merkle_root: 验证区块中交易数据的完整性
//   - state_root: 验证区块执行后的状态一致性，支持轻客户端
//
// 4. 共识机制支持:
//   - nonce + difficulty: 用于工作量证明(PoW)共识算法
type BlockHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 网络标识（最重要，防止跨网重放）
	ChainId uint64 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"` // 链ID，防止跨链重放攻击
	// 基础链接字段
	Version      uint64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`                              // 区块版本号，用于协议版本控制
	PreviousHash []byte `protobuf:"bytes,3,opt,name=previous_hash,json=previousHash,proto3" json:"previous_hash,omitempty"` // 前一个区块的哈希值，确保区块链接性
	Timestamp    uint64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                          // 区块生成时间戳，用于时间顺序和共识
	Height       uint64 `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`                                // 区块高度，用于标识区块位置
	// Merkle根验证字段
	MerkleRoot []byte `protobuf:"bytes,6,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`    // 交易Merkle树根，用于快速验证交易
	StateRoot  []byte `protobuf:"bytes,7,opt,name=state_root,json=stateRoot,proto3,oneof" json:"state_root,omitempty"` // 状态Merkle根，用于状态验证和轻客户端
	// 共识机制字段
	Nonce         []byte `protobuf:"bytes,8,opt,name=nonce,proto3" json:"nonce,omitempty"`            // 随机数，用于PoW共识机制
	Difficulty    uint64 `protobuf:"varint,9,opt,name=difficulty,proto3" json:"difficulty,omitempty"` // 挖矿难度，用于控制出块速度
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockHeader) Reset() {
	*x = BlockHeader{}
	mi := &file_pb_blockchain_block_block_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHeader) ProtoMessage() {}

func (x *BlockHeader) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blockchain_block_block_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHeader.ProtoReflect.Descriptor instead.
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return file_pb_blockchain_block_block_proto_rawDescGZIP(), []int{1}
}

func (x *BlockHeader) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *BlockHeader) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BlockHeader) GetPreviousHash() []byte {
	if x != nil {
		return x.PreviousHash
	}
	return nil
}

func (x *BlockHeader) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BlockHeader) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlockHeader) GetMerkleRoot() []byte {
	if x != nil {
		return x.MerkleRoot
	}
	return nil
}

func (x *BlockHeader) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *BlockHeader) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *BlockHeader) GetDifficulty() uint64 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

// *
// 区块体结构:
//
// +--------------------------------------+
// |              区块体                  |
// +--------------------------------------+
// | 交易列表                             |
// |--------------------------------------|
// | Transaction 1                        |
// | Transaction 2                        |
// | ...                                  |
// | Transaction N                        |
// +--------------------------------------+
//
// 交易排序和依赖关系:
//
// +-------------+      +-------------+
// | 交易1(独立) |      | 交易2(独立) |
// +-------------+      +-------------+
//
//	|                    |
//	v                    v
//
// +-------------+      +-------------+
// | 交易3(依赖1)|      | 交易4(依赖2)|
// +-------------+      +-------------+
//
//	|                    |
//	|                    v
//	|             +-------------+
//	+------------>| 交易5(依赖  |
//	              | 交易3和交易4)|
//	              +-------------+
//
// 在区块体中，交易按照特定规则排序:
// 1. 首先是Coinbase交易(矿工奖励)
// 2. 然后是独立交易(不依赖区块中其他交易)
// 3. 最后是依赖交易(依赖区块中之前的交易)
//
// 这种排序确保了交易的顺序执行是有效的，避免依赖冲突。
type BlockBody struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Transactions  []*transaction.Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"` // 交易列表，包含区块中的所有交易
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockBody) Reset() {
	*x = BlockBody{}
	mi := &file_pb_blockchain_block_block_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockBody) ProtoMessage() {}

func (x *BlockBody) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blockchain_block_block_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockBody.ProtoReflect.Descriptor instead.
func (*BlockBody) Descriptor() ([]byte, []int) {
	return file_pb_blockchain_block_block_proto_rawDescGZIP(), []int{2}
}

func (x *BlockBody) GetTransactions() []*transaction.Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

// 计算区块哈希请求（确定性设计）
type ComputeBlockHashRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Block            *Block                 `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`                                                  // 待计算哈希的区块
	IncludeDebugInfo bool                   `protobuf:"varint,2,opt,name=include_debug_info,json=includeDebugInfo,proto3" json:"include_debug_info,omitempty"` // 是否返回调试信息（不影响哈希）
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ComputeBlockHashRequest) Reset() {
	*x = ComputeBlockHashRequest{}
	mi := &file_pb_blockchain_block_block_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeBlockHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeBlockHashRequest) ProtoMessage() {}

func (x *ComputeBlockHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blockchain_block_block_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeBlockHashRequest.ProtoReflect.Descriptor instead.
func (*ComputeBlockHashRequest) Descriptor() ([]byte, []int) {
	return file_pb_blockchain_block_block_proto_rawDescGZIP(), []int{3}
}

func (x *ComputeBlockHashRequest) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *ComputeBlockHashRequest) GetIncludeDebugInfo() bool {
	if x != nil {
		return x.IncludeDebugInfo
	}
	return false
}

// 计算区块哈希响应
type ComputeBlockHashResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Hash    []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`                       // 计算得到的区块哈希（SHA-256）
	IsValid bool                   `protobuf:"varint,2,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"` // 区块结构是否有效
	// 调试信息（不影响哈希）
	DebugInfo     *BlockHashDebugInfo `protobuf:"bytes,3,opt,name=debug_info,json=debugInfo,proto3,oneof" json:"debug_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeBlockHashResponse) Reset() {
	*x = ComputeBlockHashResponse{}
	mi := &file_pb_blockchain_block_block_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeBlockHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeBlockHashResponse) ProtoMessage() {}

func (x *ComputeBlockHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blockchain_block_block_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeBlockHashResponse.ProtoReflect.Descriptor instead.
func (*ComputeBlockHashResponse) Descriptor() ([]byte, []int) {
	return file_pb_blockchain_block_block_proto_rawDescGZIP(), []int{4}
}

func (x *ComputeBlockHashResponse) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *ComputeBlockHashResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ComputeBlockHashResponse) GetDebugInfo() *BlockHashDebugInfo {
	if x != nil {
		return x.DebugInfo
	}
	return nil
}

// 验证区块哈希请求
type ValidateBlockHashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *Block                 `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`                                   // 待验证的区块
	ExpectedHash  []byte                 `protobuf:"bytes,2,opt,name=expected_hash,json=expectedHash,proto3" json:"expected_hash,omitempty"` // 期望的区块哈希
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateBlockHashRequest) Reset() {
	*x = ValidateBlockHashRequest{}
	mi := &file_pb_blockchain_block_block_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateBlockHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateBlockHashRequest) ProtoMessage() {}

func (x *ValidateBlockHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blockchain_block_block_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateBlockHashRequest.ProtoReflect.Descriptor instead.
func (*ValidateBlockHashRequest) Descriptor() ([]byte, []int) {
	return file_pb_blockchain_block_block_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateBlockHashRequest) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *ValidateBlockHashRequest) GetExpectedHash() []byte {
	if x != nil {
		return x.ExpectedHash
	}
	return nil
}

// 验证区块哈希响应
type ValidateBlockHashResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	IsValid      bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`               // 验证结果
	ComputedHash []byte                 `protobuf:"bytes,2,opt,name=computed_hash,json=computedHash,proto3" json:"computed_hash,omitempty"` // 实际计算的哈希
	ExpectedHash []byte                 `protobuf:"bytes,3,opt,name=expected_hash,json=expectedHash,proto3" json:"expected_hash,omitempty"` // 期望的哈希值
	// 验证详情（不影响哈希）
	ErrorMessage  *string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"` // 错误信息（验证失败时）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateBlockHashResponse) Reset() {
	*x = ValidateBlockHashResponse{}
	mi := &file_pb_blockchain_block_block_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateBlockHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateBlockHashResponse) ProtoMessage() {}

func (x *ValidateBlockHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blockchain_block_block_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateBlockHashResponse.ProtoReflect.Descriptor instead.
func (*ValidateBlockHashResponse) Descriptor() ([]byte, []int) {
	return file_pb_blockchain_block_block_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateBlockHashResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidateBlockHashResponse) GetComputedHash() []byte {
	if x != nil {
		return x.ComputedHash
	}
	return nil
}

func (x *ValidateBlockHashResponse) GetExpectedHash() []byte {
	if x != nil {
		return x.ExpectedHash
	}
	return nil
}

func (x *ValidateBlockHashResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

// 区块哈希调试信息（不影响哈希）
type BlockHashDebugInfo struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CanonicalBytes       []byte                 `protobuf:"bytes,1,opt,name=canonical_bytes,json=canonicalBytes,proto3" json:"canonical_bytes,omitempty"`                      // 标准化后的字节数据
	CanonicalLength      uint64                 `protobuf:"varint,2,opt,name=canonical_length,json=canonicalLength,proto3" json:"canonical_length,omitempty"`                  // 标准化数据长度
	IncludedFields       []string               `protobuf:"bytes,3,rep,name=included_fields,json=includedFields,proto3" json:"included_fields,omitempty"`                      // 参与哈希计算的字段列表
	ExcludedFields       []string               `protobuf:"bytes,4,rep,name=excluded_fields,json=excludedFields,proto3" json:"excluded_fields,omitempty"`                      // 排除的字段列表（如签名）
	SerializationMethod  string                 `protobuf:"bytes,5,opt,name=serialization_method,json=serializationMethod,proto3" json:"serialization_method,omitempty"`       // 序列化方法（固定为"protobuf"）
	ComputationTimeNanos uint64                 `protobuf:"varint,6,opt,name=computation_time_nanos,json=computationTimeNanos,proto3" json:"computation_time_nanos,omitempty"` // 计算耗时（纳秒，仅调试）
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *BlockHashDebugInfo) Reset() {
	*x = BlockHashDebugInfo{}
	mi := &file_pb_blockchain_block_block_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockHashDebugInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHashDebugInfo) ProtoMessage() {}

func (x *BlockHashDebugInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blockchain_block_block_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHashDebugInfo.ProtoReflect.Descriptor instead.
func (*BlockHashDebugInfo) Descriptor() ([]byte, []int) {
	return file_pb_blockchain_block_block_proto_rawDescGZIP(), []int{7}
}

func (x *BlockHashDebugInfo) GetCanonicalBytes() []byte {
	if x != nil {
		return x.CanonicalBytes
	}
	return nil
}

func (x *BlockHashDebugInfo) GetCanonicalLength() uint64 {
	if x != nil {
		return x.CanonicalLength
	}
	return 0
}

func (x *BlockHashDebugInfo) GetIncludedFields() []string {
	if x != nil {
		return x.IncludedFields
	}
	return nil
}

func (x *BlockHashDebugInfo) GetExcludedFields() []string {
	if x != nil {
		return x.ExcludedFields
	}
	return nil
}

func (x *BlockHashDebugInfo) GetSerializationMethod() string {
	if x != nil {
		return x.SerializationMethod
	}
	return ""
}

func (x *BlockHashDebugInfo) GetComputationTimeNanos() uint64 {
	if x != nil {
		return x.ComputationTimeNanos
	}
	return 0
}

var File_pb_blockchain_block_block_proto protoreflect.FileDescriptor

const file_pb_blockchain_block_block_proto_rawDesc = "" +
	"\n" +
	"\x1fpb/blockchain/block/block.proto\x12\x12pb.blockchain.core\x1a1pb/blockchain/block/transaction/transaction.proto\"s\n" +
	"\x05Block\x127\n" +
	"\x06header\x18\x01 \x01(\v2\x1f.pb.blockchain.core.BlockHeaderR\x06header\x121\n" +
	"\x04body\x18\x02 \x01(\v2\x1d.pb.blockchain.core.BlockBodyR\x04body\"\xa7\x02\n" +
	"\vBlockHeader\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x04R\achainId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12#\n" +
	"\rprevious_hash\x18\x03 \x01(\fR\fpreviousHash\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x04R\x06height\x12\x1f\n" +
	"\vmerkle_root\x18\x06 \x01(\fR\n" +
	"merkleRoot\x12\"\n" +
	"\n" +
	"state_root\x18\a \x01(\fH\x00R\tstateRoot\x88\x01\x01\x12\x14\n" +
	"\x05nonce\x18\b \x01(\fR\x05nonce\x12\x1e\n" +
	"\n" +
	"difficulty\x18\t \x01(\x04R\n" +
	"difficultyB\r\n" +
	"\v_state_root\"P\n" +
	"\tBlockBody\x12C\n" +
	"\ftransactions\x18\x01 \x03(\v2\x1f.pb.blockchain.core.TransactionR\ftransactions\"x\n" +
	"\x17ComputeBlockHashRequest\x12/\n" +
	"\x05block\x18\x01 \x01(\v2\x19.pb.blockchain.core.BlockR\x05block\x12,\n" +
	"\x12include_debug_info\x18\x02 \x01(\bR\x10includeDebugInfo\"\xa4\x01\n" +
	"\x18ComputeBlockHashResponse\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x19\n" +
	"\bis_valid\x18\x02 \x01(\bR\aisValid\x12J\n" +
	"\n" +
	"debug_info\x18\x03 \x01(\v2&.pb.blockchain.core.BlockHashDebugInfoH\x00R\tdebugInfo\x88\x01\x01B\r\n" +
	"\v_debug_info\"p\n" +
	"\x18ValidateBlockHashRequest\x12/\n" +
	"\x05block\x18\x01 \x01(\v2\x19.pb.blockchain.core.BlockR\x05block\x12#\n" +
	"\rexpected_hash\x18\x02 \x01(\fR\fexpectedHash\"\xbc\x01\n" +
	"\x19ValidateBlockHashResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12#\n" +
	"\rcomputed_hash\x18\x02 \x01(\fR\fcomputedHash\x12#\n" +
	"\rexpected_hash\x18\x03 \x01(\fR\fexpectedHash\x12(\n" +
	"\rerror_message\x18\x04 \x01(\tH\x00R\ferrorMessage\x88\x01\x01B\x10\n" +
	"\x0e_error_message\"\xa3\x02\n" +
	"\x12BlockHashDebugInfo\x12'\n" +
	"\x0fcanonical_bytes\x18\x01 \x01(\fR\x0ecanonicalBytes\x12)\n" +
	"\x10canonical_length\x18\x02 \x01(\x04R\x0fcanonicalLength\x12'\n" +
	"\x0fincluded_fields\x18\x03 \x03(\tR\x0eincludedFields\x12'\n" +
	"\x0fexcluded_fields\x18\x04 \x03(\tR\x0eexcludedFields\x121\n" +
	"\x14serialization_method\x18\x05 \x01(\tR\x13serializationMethod\x124\n" +
	"\x16computation_time_nanos\x18\x06 \x01(\x04R\x14computationTimeNanos2\xf3\x01\n" +
	"\x10BlockHashService\x12m\n" +
	"\x10ComputeBlockHash\x12+.pb.blockchain.core.ComputeBlockHashRequest\x1a,.pb.blockchain.core.ComputeBlockHashResponse\x12p\n" +
	"\x11ValidateBlockHash\x12,.pb.blockchain.core.ValidateBlockHashRequest\x1a-.pb.blockchain.core.ValidateBlockHashResponseB*Z(github.com/weisyn/v1/pb/blockchain/blockb\x06proto3"

var (
	file_pb_blockchain_block_block_proto_rawDescOnce sync.Once
	file_pb_blockchain_block_block_proto_rawDescData []byte
)

func file_pb_blockchain_block_block_proto_rawDescGZIP() []byte {
	file_pb_blockchain_block_block_proto_rawDescOnce.Do(func() {
		file_pb_blockchain_block_block_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_blockchain_block_block_proto_rawDesc), len(file_pb_blockchain_block_block_proto_rawDesc)))
	})
	return file_pb_blockchain_block_block_proto_rawDescData
}

var file_pb_blockchain_block_block_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pb_blockchain_block_block_proto_goTypes = []any{
	(*Block)(nil),                     // 0: pb.blockchain.core.Block
	(*BlockHeader)(nil),               // 1: pb.blockchain.core.BlockHeader
	(*BlockBody)(nil),                 // 2: pb.blockchain.core.BlockBody
	(*ComputeBlockHashRequest)(nil),   // 3: pb.blockchain.core.ComputeBlockHashRequest
	(*ComputeBlockHashResponse)(nil),  // 4: pb.blockchain.core.ComputeBlockHashResponse
	(*ValidateBlockHashRequest)(nil),  // 5: pb.blockchain.core.ValidateBlockHashRequest
	(*ValidateBlockHashResponse)(nil), // 6: pb.blockchain.core.ValidateBlockHashResponse
	(*BlockHashDebugInfo)(nil),        // 7: pb.blockchain.core.BlockHashDebugInfo
	(*transaction.Transaction)(nil),   // 8: pb.blockchain.core.Transaction
}
var file_pb_blockchain_block_block_proto_depIdxs = []int32{
	1, // 0: pb.blockchain.core.Block.header:type_name -> pb.blockchain.core.BlockHeader
	2, // 1: pb.blockchain.core.Block.body:type_name -> pb.blockchain.core.BlockBody
	8, // 2: pb.blockchain.core.BlockBody.transactions:type_name -> pb.blockchain.core.Transaction
	0, // 3: pb.blockchain.core.ComputeBlockHashRequest.block:type_name -> pb.blockchain.core.Block
	7, // 4: pb.blockchain.core.ComputeBlockHashResponse.debug_info:type_name -> pb.blockchain.core.BlockHashDebugInfo
	0, // 5: pb.blockchain.core.ValidateBlockHashRequest.block:type_name -> pb.blockchain.core.Block
	3, // 6: pb.blockchain.core.BlockHashService.ComputeBlockHash:input_type -> pb.blockchain.core.ComputeBlockHashRequest
	5, // 7: pb.blockchain.core.BlockHashService.ValidateBlockHash:input_type -> pb.blockchain.core.ValidateBlockHashRequest
	4, // 8: pb.blockchain.core.BlockHashService.ComputeBlockHash:output_type -> pb.blockchain.core.ComputeBlockHashResponse
	6, // 9: pb.blockchain.core.BlockHashService.ValidateBlockHash:output_type -> pb.blockchain.core.ValidateBlockHashResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pb_blockchain_block_block_proto_init() }
func file_pb_blockchain_block_block_proto_init() {
	if File_pb_blockchain_block_block_proto != nil {
		return
	}
	file_pb_blockchain_block_block_proto_msgTypes[1].OneofWrappers = []any{}
	file_pb_blockchain_block_block_proto_msgTypes[4].OneofWrappers = []any{}
	file_pb_blockchain_block_block_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_blockchain_block_block_proto_rawDesc), len(file_pb_blockchain_block_block_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_blockchain_block_block_proto_goTypes,
		DependencyIndexes: file_pb_blockchain_block_block_proto_depIdxs,
		MessageInfos:      file_pb_blockchain_block_block_proto_msgTypes,
	}.Build()
	File_pb_blockchain_block_block_proto = out.File
	file_pb_blockchain_block_block_proto_goTypes = nil
	file_pb_blockchain_block_block_proto_depIdxs = nil
}
