// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.1
// source: pb/blockchain/block/block.proto

package block

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlockHashService_ComputeBlockHash_FullMethodName  = "/pb.blockchain.core.BlockHashService/ComputeBlockHash"
	BlockHashService_ValidateBlockHash_FullMethodName = "/pb.blockchain.core.BlockHashService/ValidateBlockHash"
)

// BlockHashServiceClient is the client API for BlockHashService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// *
// BlockHashService 提供确定性的区块哈希计算和验证
//
// 设计原则：
// - 哈希计算必须是确定性的（相同输入 -> 相同输出）
// - 不依赖任何可变参数（算法、选项等）
// - 遵循协议固定的哈希标准
// - 保证跨平台一致性
//
// 哈希标准：
// - 区块哈希：仅对区块头进行SHA-256计算
// - 交易哈希：由Transaction服务负责
// - Merkle根：由区块构建过程内部计算
type BlockHashServiceClient interface {
	// 计算区块哈希（确定性）
	// 固定算法：SHA-256，仅计算区块头
	ComputeBlockHash(ctx context.Context, in *ComputeBlockHashRequest, opts ...grpc.CallOption) (*ComputeBlockHashResponse, error)
	// 验证区块哈希（确定性）
	// 重新计算哈希并与期望值比较
	ValidateBlockHash(ctx context.Context, in *ValidateBlockHashRequest, opts ...grpc.CallOption) (*ValidateBlockHashResponse, error)
}

type blockHashServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockHashServiceClient(cc grpc.ClientConnInterface) BlockHashServiceClient {
	return &blockHashServiceClient{cc}
}

func (c *blockHashServiceClient) ComputeBlockHash(ctx context.Context, in *ComputeBlockHashRequest, opts ...grpc.CallOption) (*ComputeBlockHashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComputeBlockHashResponse)
	err := c.cc.Invoke(ctx, BlockHashService_ComputeBlockHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockHashServiceClient) ValidateBlockHash(ctx context.Context, in *ValidateBlockHashRequest, opts ...grpc.CallOption) (*ValidateBlockHashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateBlockHashResponse)
	err := c.cc.Invoke(ctx, BlockHashService_ValidateBlockHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockHashServiceServer is the server API for BlockHashService service.
// All implementations must embed UnimplementedBlockHashServiceServer
// for forward compatibility.
//
// *
// BlockHashService 提供确定性的区块哈希计算和验证
//
// 设计原则：
// - 哈希计算必须是确定性的（相同输入 -> 相同输出）
// - 不依赖任何可变参数（算法、选项等）
// - 遵循协议固定的哈希标准
// - 保证跨平台一致性
//
// 哈希标准：
// - 区块哈希：仅对区块头进行SHA-256计算
// - 交易哈希：由Transaction服务负责
// - Merkle根：由区块构建过程内部计算
type BlockHashServiceServer interface {
	// 计算区块哈希（确定性）
	// 固定算法：SHA-256，仅计算区块头
	ComputeBlockHash(context.Context, *ComputeBlockHashRequest) (*ComputeBlockHashResponse, error)
	// 验证区块哈希（确定性）
	// 重新计算哈希并与期望值比较
	ValidateBlockHash(context.Context, *ValidateBlockHashRequest) (*ValidateBlockHashResponse, error)
	mustEmbedUnimplementedBlockHashServiceServer()
}

// UnimplementedBlockHashServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlockHashServiceServer struct{}

func (UnimplementedBlockHashServiceServer) ComputeBlockHash(context.Context, *ComputeBlockHashRequest) (*ComputeBlockHashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ComputeBlockHash not implemented")
}
func (UnimplementedBlockHashServiceServer) ValidateBlockHash(context.Context, *ValidateBlockHashRequest) (*ValidateBlockHashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateBlockHash not implemented")
}
func (UnimplementedBlockHashServiceServer) mustEmbedUnimplementedBlockHashServiceServer() {}
func (UnimplementedBlockHashServiceServer) testEmbeddedByValue()                          {}

// UnsafeBlockHashServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockHashServiceServer will
// result in compilation errors.
type UnsafeBlockHashServiceServer interface {
	mustEmbedUnimplementedBlockHashServiceServer()
}

func RegisterBlockHashServiceServer(s grpc.ServiceRegistrar, srv BlockHashServiceServer) {
	// If the following call panics, it indicates UnimplementedBlockHashServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlockHashService_ServiceDesc, srv)
}

func _BlockHashService_ComputeBlockHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeBlockHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockHashServiceServer).ComputeBlockHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockHashService_ComputeBlockHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockHashServiceServer).ComputeBlockHash(ctx, req.(*ComputeBlockHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockHashService_ValidateBlockHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateBlockHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockHashServiceServer).ValidateBlockHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockHashService_ValidateBlockHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockHashServiceServer).ValidateBlockHash(ctx, req.(*ValidateBlockHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlockHashService_ServiceDesc is the grpc.ServiceDesc for BlockHashService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlockHashService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.blockchain.core.BlockHashService",
	HandlerType: (*BlockHashServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ComputeBlockHash",
			Handler:    _BlockHashService_ComputeBlockHash_Handler,
		},
		{
			MethodName: "ValidateBlockHash",
			Handler:    _BlockHashService_ValidateBlockHash_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/blockchain/block/block.proto",
}
